Fix eraser status report for wacom bamboo
OpenTabletDriver/OpenTabletDriver pull request #1082
Opened 2021-05-02 15:41 UTC by Keltere

On the wacoom CTH-470 the eraser status was always true even when using the tip.
Credits to @X9VoiD for the solution.

2021-05-02 18:45 UTC, InfinityGhost requested changes
Only the Wacom MTE-450 uses this report parser, nothing else. This shouldn't have made any effect on the CTH-470.

This also breaks the eraser on the MTE-450.

2021-05-02 18:47 UTC, gonX commented
For context, a change to the CTH-470 parser was intended (based off a conversation today on Discord) but it does indeed seem that it is absent from this PR

2021-05-02 18:52 UTC, InfinityGhost commented
> For context, a change to the CTH-470 parser was intended (based off a conversation today on Discord) but it does indeed seem that it is absent from this PR.
> 
> Good to know that it breaks MTE-450 support, this requires the change to be split into its own parser and then making CTH-470 use that.

I own a CTH-470 as well and I'm unable to reproduce the parent issue either way.

2021-05-02 22:40 UTC, X9VoiD commented
Move this to another parser.

2021-05-03 14:35 UTC, Kuuuube requested changes
Parser name is misleading. The CTH-470 does not only go by the "Bamboo Capture" name and not all "Bamboo Capture" tablets are CTH-470's.

2021-07-11 21:11 UTC, InfinityGhost commented
This has since been resolved in a different PR.

2021-07-11 21:11 UTC, closed without merging