Add OpenTabletDriver.Analyzers project
OpenTabletDriver/OpenTabletDriver pull request #1083
Opened 2021-05-02 22:22 UTC by X9VoiD

## Changes

- Implements tablet configuration pre-compilation

The pre-compiled tablet configurations are meant to be used on osu! Lazer and other consumers of `OpenTabletDriver`.
These configs are accessible through `OpenTabletDriver.Driver.GetPreCompiledConfigurations()` and removes the need to parse any json.

2021-05-03 03:47 UTC, InfinityGhost requested changes

2021-05-03 03:47 UTC, InfinityGhost commented on OpenTabletDriver/Driver.cs
> +        }
Do this instead. It would provide a default method of grabbing tablet configurations which can be overridden to provide configurations manually, such as in the desktop implementation.

This also allows us to directly write a virtual `Detect()` method which will run through all configurations and match for each. Making this virtual allows the consumer to handle detection manually as well if desired.

```suggestion
        public virtual IEnumerable<TabletConfiguration> GetConfigurations() => CompiledTabletConfigurations.GetConfigurations();
```

2021-05-03 03:47 UTC, InfinityGhost commented on OpenTabletDriver.Tests/TabletConfigurationCompilerTests.cs
> +            Assert.IsTrue(!string.IsNullOrEmpty(tabletConfig.Name));
Might be a good idea to make sure *all* configurations enumerated are available, instead of just the first one. Wouldn't increase test time much and would make this much more reliable for test coverage.

2021-05-03 03:47 UTC, InfinityGhost commented on OpenTabletDriver.Analyzers/TabletConfigurationGenerator.cs
> +        private const string CLASS_NAME = "CompiledTabletConfig";
```suggestion
        private const string CLASS_NAME = "CompiledTabletConfigurations";
```

2021-05-03 03:47 UTC, InfinityGhost commented on OpenTabletDriver.Analyzers/TabletConfigurationGenerator.cs
> +";
Would like to see this made prettier if at all possible (could use `\n` and string addition), along with using the `CLASS_NAME` constant to avoid a possible mix up.

2021-05-03 08:25 UTC, X9VoiD commented on OpenTabletDriver.Analyzers/TabletConfigurationGenerator.cs
> +";
It'll be messier if I did it with push-pop style for indenting, so instead I started the string on a new line.

2021-05-03 19:45 UTC, InfinityGhost commented
Will have to wait until omnisharp resolves its issues with analyzers before I'll merge this. I'm still too comfortable with vscode to leave it broken.

2021-10-17 03:03 UTC, InfinityGhost commented
Is this even usable since we've switched to the separate project for this instead? I'd like to get a move on this.

2021-10-17 05:17 UTC, X9VoiD commented
Can still be used on the OpenTabletDriver.Configurations project. Though to fix slow omnisharp we need to update to .NET 6 for incremental generation feature (to skip code generation when nothing changed on the config files).

2022-07-31 09:58 UTC, jamesbt365 commented
Well we are on .NET 6 now

2022-10-16 01:21 UTC, InfinityGhost commented
> Well we are on .NET 6 now

Might as well, just needs rebased to master now

2022-12-11 14:55 UTC, doubledge-spec commented
Update?

2022-12-12 14:55 UTC, InfinityGhost commented
This needs bumped to the latest master branch

2022-12-14 20:51 UTC, X9VoiD commented on OpenTabletDriver/OpenTabletDriver.csproj
> -
This points to a non-existent folder, so I removed it.

2022-12-14 20:51 UTC, X9VoiD commented on OpenTabletDriver.Configurations/OpenTabletDriver.Configurations.csproj
> +  <Import Project="..\OpenTabletDriver.Analyzers\TabletConfigurationGenerator.props" />
We're not referencing the generator as a nuget package so the generator prop has to be imported manually.

2022-12-14 20:51 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/Huion/Kamvas Pro 16 (2.5k).json
> +      "InitializationStrings": []
`InitializationStrings` should never be null according to [`DeviceIdentifier`](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/10a3c07206028f7df5befbdeca6aadb30efe4cb3/OpenTabletDriver/Tablet/DeviceIdentifier.cs), it caused issues to the generator as well.

2022-12-14 20:51 UTC, X9VoiD commented on OpenTabletDriver.Analyzers/TabletConfigurationGenerator.cs
> +                var target = new ProviderTarget("DeviceConfigurationProvider", "OpenTabletDriver.Configurations");
I don't expect that we'll change the name of that class nor add another target so this is fine for now.

2022-12-14 20:51 UTC, X9VoiD commented on OpenTabletDriver.Analyzers/Formatters/WhitespaceHumanizer.cs
> +    public class WhitespaceHumanizer : CSharpSyntaxRewriter
This is a fun one, remove this, then see the test output lol.

2022-12-14 20:51 UTC, X9VoiD commented on OpenTabletDriver.Analyzers.Tests/Verifiers/IncrementalGeneratorVerifier.cs
> +    public partial class IncrementalGeneratorVerifier<TSourceGenerator>
This class is designed to be reusable for other projects that use and verify incremental generators (tho it doesn't support testing incremental changes yet, like the one I did in [osu-framework#5562](https://github.com/ppy/osu-framework/pull/5562)). Roslyn-provided verifiers do not support testing metadatas of `AdditionalText` which this one offers.

2022-12-14 21:13 UTC, InfinityGhost approved these changes

2022-12-16 04:44 UTC, InfinityGhost commented
Something's busted on my end with my rider install and .NET 7 so I'm unable to verify that the analyzers don't break development environments like in the past in vscode's C# extension.

2022-12-25 00:44 UTC, doubledge-spec commented
Boid has merge perms :trolley:

2022-12-25 22:39 UTC, merged