detect tablets after wake
OpenTabletDriver/OpenTabletDriver pull request #1112
Opened 2021-05-21 13:37 UTC by adryzz

Since #1093 didn't receive any updates in 2 weeks, i decided to do it myself
- [X] Power management abstraction (`OpenTabletDriver.Desktop.Interop.Power`)
- [X] Detect tablets on resume power event
- [ ] Dispose `PowerManager` on daemon exit

> This is needed on Windows to prevent memory leaks (see [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents.powermodechanged?view=net-5.0#remarks)) and likely on Linux and MacOS as well depending on their implementation

- [X] Implement Windows power event
- [ ] Implement Linux power event
- [ ] Implement MacOS power event

2021-05-25 02:43 UTC, InfinityGhost requested changes

2021-05-25 02:43 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Interop/Power/PowerEvent.cs
> +    }
Move this into its own file, or into the `PowerEventArgs` class (ideally the former).

2021-05-25 02:43 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Interop/Power/PowerEvent.cs
> +    }
Move this into its own file, or rename this file to match this class name.

2021-05-25 03:10 UTC, InfinityGhost commented
> * [ ]  Implement Linux power event
> * [ ]  Implement MacOS power event

These really aren't necessary for this pull request to be merged, but would be a nice touch.

2021-05-25 07:00 UTC, adryzz commented
> > * [ ]  Implement Linux power event
> > * [ ]  Implement MacOS power event
> 
> These really aren't necessary for this pull request to be merged, but would be a nice touch.
> 

Ok, so I'll do the requested changes this afternoon, and implement macOS and Linux power events in another PR.

for MacOS i already have a C++ `NSNotification` implementation done, just needs porting, and for Linux there's a few options to choose from

2021-05-25 07:19 UTC, adryzz commented on OpenTabletDriver.Desktop/Interop/Power/IPowerManager.cs
> +    }
what's the difference?

2021-05-25 07:21 UTC, adryzz commented on OpenTabletDriver.Desktop/Interop/Power/PowerEvent.cs
> +    }
Had to rename from `PowerEvent` to `PowerEventType`  because of conflicts and didn't change the file name

2021-05-25 07:26 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Interop/Power/IPowerManager.cs
> +    }
Formatting

2021-05-25 11:31 UTC, adryzz commented on OpenTabletDriver.Desktop/Interop/Power/IPowerManager.cs
> +    }
oh, just realized that the mobile GitHub app isn't showing tabs and spaces correctly, so they looked exactly the same

2021-05-25 15:08 UTC, adryzz commented
> It's not implemented yet on OTD.Daemon, is that intentional?

It is intentional, since the `PowerManager` should be disposed when closing the daemon, so the destructor should work just fine

2021-05-25 15:26 UTC, X9VoiD commented
That's not what I meant, I'm asking why it's not using `PowerManager` anywhere in this PR, accessing it will also create new `PowerManager` instance every time.

2021-05-25 15:31 UTC, adryzz commented
> That's not what I meant, I'm asking why it's not using `PowerManager` anywhere in this PR, accessing it will also create new `PowerManager` instance every time.

ooh, i did it locally and didn't stage the changes, my bad.

2021-07-18 02:12 UTC, InfinityGhost requested changes

2021-09-05 19:22 UTC, InfinityGhost commented
Superseded by #1290

2021-09-05 19:22 UTC, closed without merging