Add support for auxilliary buttons on Huion H430P
OpenTabletDriver/OpenTabletDriver pull request #1128
Opened 2021-05-28 14:32 UTC by ashblk

2021-06-01 12:16 UTC, X9VoiD requested changes
Have you already tried using UCLogicReportParser? Looking at what you did with H430 parser it seems that it does the exact same thing as UCLogicReportParser.

2021-06-01 17:25 UTC, X9VoiD approved these changes

2021-06-01 17:38 UTC, AbstractQbit approved these changes

2021-06-02 01:36 UTC, InfinityGhost approved these changes

2021-06-02 01:38 UTC, merged