feat: Added json file for XP Pen Deco Fun XS
OpenTabletDriver/OpenTabletDriver pull request #1173
Opened 2021-06-12 10:15 UTC by sarsembin

Added configuration file for XP Pen Deco Fun XS, tested with release  0.5.3.2 portable, working normally.

2021-06-12 10:19 UTC, AbstractQbit commented
Config format has changed since 0.5.3.2, please follow the new format.

2021-06-12 10:20 UTC, X9VoiD commented
Also, does it have buttons on the tablet? If yes, use the XP-Pen parser used on other tablets like G640S for example to add support to the tablet buttons.

2021-06-12 10:22 UTC, sarsembin commented
It doesn't have buttons.

> Also, does it have buttons on the tablet? If yes, use the XP-Pen parser used on other tablets like G640S for example to add support to the tablet buttons.

It doesn't have them.

2021-06-12 10:25 UTC, sarsembin commented
> Config format has changed since 0.5.3.2, please follow the new format.

What version do I need?

2021-06-12 10:27 UTC, AbstractQbit commented
> What version do I need?

The one you are targeting with this PR, i.e. master. You can download dev builds from Actions tab.

2021-06-12 13:18 UTC, InfinityGhost commented
![image](https://user-images.githubusercontent.com/39218853/121777112-62ce8c80-cb5e-11eb-8019-027bcecc3129.png)

Name should be changed to `XP-Pen CT430` to match the product model name.

2021-06-12 13:21 UTC, InfinityGhost requested changes
Update the `TABLETS.md` file adding this tablet, making sure that it is sorted correctly.

2021-06-12 13:21 UTC, InfinityGhost commented on OpenTabletDriver/Configurations/XP-Pen/Deco Fun XS.json
> +  "Name": "XP-Pen Deco Fun XS",
Change the name and update the filename to match.
```suggestion
  "Name": "XP-Pen CT430",
```

2021-06-13 06:59 UTC, sarsembin commented
@InfinityGhost thank you, I wasnt able to do those changes myself since I couldnt find 0.6 build and build script doesnt work on my computer, so cant check if the cfg file would work.

2021-06-13 11:41 UTC, X9VoiD approved these changes

2021-06-13 11:42 UTC, merged