Improve Veikk support
OpenTabletDriver/OpenTabletDriver pull request #1186
Opened 2021-06-14 18:19 UTC by X9VoiD

## Changes

- Add `VeikkReportParser`
- Add S640 V2 configuration

2021-06-14 18:27 UTC, adryzz approved these changes

2021-06-15 12:47 UTC, InfinityGhost requested changes

2021-06-15 12:57 UTC, X9VoiD commented on TABLETS.md
> +| VEIKK S640 V2          |     Untested     |
PR is updated now, [verification](https://discord.com/channels/615607687467761684/615611007951306863/854342974849941505) just came in.

2021-06-20 16:48 UTC, InfinityGhost approved these changes

2021-06-20 16:49 UTC, merged