Implement sleep detection
OpenTabletDriver/OpenTabletDriver pull request #1290
Opened 2021-07-27 08:02 UTC by X9VoiD

Supersedes #1083 and #1093

## Fixes

- Reruns detection logic when a wake-from-sleep/hibernate event is detected.

2021-08-02 03:33 UTC, InfinityGhost requested changes

2021-08-02 03:33 UTC, InfinityGhost commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +                Log.Write("Sleep", "Wakey wakey", LogLevel.Debug);
Change this lol

2021-08-02 03:33 UTC, InfinityGhost commented on OpenTabletDriver/Interop/SleepDetectionThread.cs
> +        }
Not huge on using a busy loop to detect if the PC went into sleep mode.

2021-08-02 05:10 UTC, X9VoiD commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +                Log.Write("Sleep", "Wakey wakey", LogLevel.Debug);
Nooooo why ;-;

2021-08-02 05:12 UTC, X9VoiD commented on OpenTabletDriver/Interop/SleepDetectionThread.cs
> +        }
It's not a "busy loop" technically and it doesn't "take over a thread" since it's an asynchronous Task. The CPU usage on this is nil.

2021-09-04 19:50 UTC, InfinityGhost commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +                Log.Write("Sleep", "Wakey wakey", LogLevel.Debug);
Change it.

2021-09-04 20:12 UTC, X9VoiD commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +                Log.Write("Sleep", "Wakey wakey", LogLevel.Debug);
Resolved.

2021-09-04 20:16 UTC, InfinityGhost approved these changes

2021-09-04 20:16 UTC, merged