Added new config UC-Logic WP5540U
OpenTabletDriver/OpenTabletDriver pull request #1309
Opened 2021-08-02 02:42 UTC by Sengkey

Added new config UC-Logic WP5540U

2021-08-02 02:48 UTC, InfinityGhost requested changes
Our configuration format has changed since v0.5, this needs to be updated to match the new format in order to add it to our list. We also require that a newly added tablet to be put into `TABLETS.md` since that's how we track what tablets are supported.

2021-08-02 03:20 UTC, Sengkey commented
Hi @InfinityGhost ,
As requested, I have adapted to the new format. 
Note: It is NOT working in v0.5.x.x macOS version. Only the old format earlier is working.

2021-08-02 03:23 UTC, InfinityGhost commented
> Note: It is NOT working in v0.5.x.x macOS version. Only the old format earlier is working.

You'd have to use a v0.6 development build in order to use the new configuration format, older versions don't know what to do with the new format.

2021-08-02 03:28 UTC, InfinityGhost reviewed
Everything looks good now, I just want to make sure that the configuration actually still works. If it works on macOS, its pretty safe to say it works on all platforms since macOS is the most difficult to get working.

2021-08-02 12:37 UTC, Sengkey commented
Only MacOS is supported. WinUSB implementation required. Linux is untested.

I have updated TABLETS.md

2022-11-07 13:54 UTC, gonX commented
This should be targeting the `configs` branch instead, and likely needs a rebase to the new 0.7 config standard.

Sorry for the delay in getting your change merged, I imagine it was simply an oversight that it wasn't seen.

2024-04-20 22:52 UTC, jamesbt365 requested changes
This needs rebasing and linting.

2025-01-31 21:06 UTC, closed without merging

2025-01-31 21:06 UTC, jamesbt365 commented
Author hasn't been seen in about 3 years now and this is more than just out of date.

If anybody has this tablet so this PR can be updated, please mention it so we can update this PR and reverify.