Add WinUSB support and fix RootHub abstraction
OpenTabletDriver/OpenTabletDriver pull request #1313
Opened 2021-08-04 09:03 UTC by X9VoiD

## Changes

- WinUSB support (Set/GetFeature heuristically implemented - we have no information about max feature lengths so assume caller is correct and directly write the array)
- RootHub fixed. All hardcoded HidSharp dependencies are now removed
- UX device list is now retrieved from Daemon instead of its own instance of RootHub
- Added APIs for future plugin-supplemented RootHub
- Added DevicesChanged debouncing (events fired within 20ms are aggregated to a single event)

## Quirks

- WinUSB device discovery requires that we know their device class GUID in advance, this PR uses 2 of the most common WinUSB class GUIDs
    - Standard (Zadig)
    - Huion (all Hawku configs use this)
- WinUSB have broken endpoint parsing for some reason, so devices might have different reported Input/Output lengths
    - We'll have to add those different stuff in the future
- **Hotplug only supports Windows 8 and up.**

## Minor fixes

- Fix missing logs when booting UX
- Specify upper-bound for UX log messages

## Sample Diagnostics

<details>
<summary>WinUSB</summary>
<pre>
{
  "App Version": "OpenTabletDriver v0.5.3.1",
  "Operating System": {
    "Platform": 2,
    "ServicePack": "",
    "Version": "10.0.22000.0",
    "VersionString": "Microsoft Windows NT 10.0.22000.0"
  },
  "Environment Variables": {
    "USERPROFILE": "C:\\Users\\oscar",
    "TMP": "C:\\Users\\oscar\\AppData\\Local\\Temp",
    "LANG": "en_US.UTF-8",
    "APPDATA": "C:\\Users\\oscar\\AppData\\Roaming",
    "OneDrive": "C:\\Users\\oscar\\OneDrive",
    "SystemRoot": "C:\\Windows",
    "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
    "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
    "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-a659907bff-sock",
    "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\oscar\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\Code - Insiders.exe",
    "TERM_PROGRAM_VERSION": "1.59.0-insider",
    "USERDOMAIN_ROAMINGPROFILE": "LAPPY",
    "LOCALAPPDATA": "C:\\Users\\oscar\\AppData\\Local",
    "SESSIONNAME": "Console",
    "ProgramData": "C:\\ProgramData",
    "USERNAME": "oscar",
    "ComSpec": "C:\\Windows\\system32\\cmd.exe",
    "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 58 Stepping 9, GenuineIntel",
    "HOMEPATH": "\\Users\\oscar",
    "windir": "C:\\Windows",
    "ALLUSERSPROFILE": "C:\\ProgramData",
    "ProgramW6432": "C:\\Program Files",
    "ProgramFiles": "C:\\Program Files",
    "PROCESSOR_REVISION": "3a09",
    "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
    "PSModulePath": "C:\\Users\\oscar\\Documents\\PowerShell\\Modules;C:\\Program Files\\PowerShell\\Modules;c:\\program files\\powershell\\7\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
    "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_9228_BCHYPKWCGFCIYMMA",
    "PROCESSOR_LEVEL": "6",
    "COMPUTERNAME": "LAPPY",
    "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\oscar\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
    "CommonProgramW6432": "C:\\Program Files\\Common Files",
    "HOMEDRIVE": "C:",
    "USERDOMAIN": "LAPPY",
    "POWERSHELL_DISTRIBUTION_CHANNEL": "MSI:Windows 10 Pro Education",
    "ProgramFiles(x86)": "C:\\Program Files (x86)",
    "TERM_PROGRAM": "vscode",
    "Path": "C:\\Program Files\\PowerShell\\7;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\PowerShell\\7\\;C:\\Users\\oscar\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\oscar\\.dotnet\\tools;C:\\Users\\oscar\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin",
    "CommonProgramFiles": "C:\\Program Files\\Common Files",
    "TEMP": "C:\\Users\\oscar\\AppData\\Local\\Temp",
    "LOGONSERVER": "\\\\LAPPY",
    "NUMBER_OF_PROCESSORS": "4",
    "OS": "Windows_NT",
    "PROCESSOR_ARCHITECTURE": "AMD64",
    "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
    "COLORTERM": "truecolor",
    "SystemDrive": "C:",
    "FPS_BROWSER_USER_PROFILE_STRING": "Default",
    "PUBLIC": "C:\\Users\\Public",
    "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
    "GIT_ASKPASS": "c:\\Users\\oscar\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\git\\dist\\askpass.sh"
  },
  "HID Devices": [
    {
      "DevicePath": "\\\\?\\usb#vid_28bd&pid_0906&mi_02#6&dfe76f7&0&0002#{dee824ef-729b-4a0e-9c14-b7117d33a817}",
      "Manufacturer": "UGTABLET",
      "ProductName": "6 inch PenTablet",
      "FriendlyName": "6 inch PenTablet",
      "ProductID": 2310,
      "VendorID": 10429,
      "InputReportLength": 10,
      "OutputReportLength": 10,
      "FeatureReportLength": 0,
      "SerialNumber": "Unknown Serial Number",
      "CanOpen": true
    },
    {
      "DevicePath": "\\\\?\\hid#vid_28bd&pid_0906&mi_00&col03#7&221b3f0d&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd",
      "Manufacturer": "UGTABLET",
      "ProductName": "6 inch PenTablet",
      "FriendlyName": "6 inch PenTablet",
      "ProductID": 2310,
      "VendorID": 10429,
      "InputReportLength": 8,
      "OutputReportLength": 0,
      "FeatureReportLength": 0,
      "SerialNumber": "",
      "CanOpen": false
    },
    {
      "DevicePath": "\\\\?\\hid#vid_1ea7&pid_0907&mi_00#7&5b581ed&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\kbd",
      "Manufacturer": "SEMITEK",
      "ProductName": "USB-HID Gaming Keyboard",
      "FriendlyName": "USB-HID Gaming Keyboard",
      "ProductID": 2311,
      "VendorID": 7847,
      "InputReportLength": 9,
      "OutputReportLength": 2,
      "FeatureReportLength": 0,
      "SerialNumber": "SN0000000001",
      "CanOpen": false
    },
    {
      "DevicePath": "\\\\?\\hid#vid_1ea7&pid_0907&mi_02&col04#7&65e2f90&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "Manufacturer": "SEMITEK",
      "ProductName": "USB-HID Gaming Keyboard",
      "FriendlyName": "USB-HID Gaming Keyboard",
      "ProductID": 2311,
      "VendorID": 7847,
      "InputReportLength": 7,
      "OutputReportLength": 0,
      "FeatureReportLength": 0,
      "SerialNumber": "SN0000000001",
      "CanOpen": false
    },
    {
      "DevicePath": "\\\\?\\hid#vid_046d&pid_c084&mi_01&col02#8&39e92dbc&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "Manufacturer": "Logitech",
      "ProductName": "G102 Prodigy Gaming Mouse",
      "FriendlyName": "G102 Prodigy Gaming Mouse",
      "ProductID": 49284,
      "VendorID": 1133,
      "InputReportLength": 5,
      "OutputReportLength": 0,
      "FeatureReportLength": 0,
      "SerialNumber": "115E38693135",
      "CanOpen": true
    },
    {
      "DevicePath": "\\\\?\\hid#vid_046d&pid_c084&mi_01&col03#8&39e92dbc&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "Manufacturer": "Logitech",
      "ProductName": "G102 Prodigy Gaming Mouse",
      "FriendlyName": "G102 Prodigy Gaming Mouse",
      "ProductID": 49284,
      "VendorID": 1133,
      "InputReportLength": 2,
      "OutputReportLength": 0,
      "FeatureReportLength": 0,
      "SerialNumber": "115E38693135",
      "CanOpen": true
    },
    {
      "DevicePath": "\\\\?\\hid#vid_28bd&pid_0906&mi_00&col02#7&221b3f0d&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "Manufacturer": "UGTABLET",
      "ProductName": "6 inch PenTablet",
      "FriendlyName": "6 inch PenTablet",
      "ProductID": 2310,
      "VendorID": 10429,
      "InputReportLength": 8,
      "OutputReportLength": 0,
      "FeatureReportLength": 0,
      "SerialNumber": "",
      "CanOpen": false
    },
    {
      "DevicePath": "\\\\?\\hid#vid_28bd&pid_0906&mi_00&col01#7&221b3f0d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}",
      "Manufacturer": "UGTABLET",
      "ProductName": "6 inch PenTablet",
      "FriendlyName": "6 inch PenTablet",
      "ProductID": 2310,
      "VendorID": 10 [...]

2021-08-04 09:52 UTC, turbedi commented on OpenTabletDriver/Devices/WinUSB/WinUSBInterfaceStream.cs
> +                ? readBuffer.AsSpan().Slice(0, (int)bytesRead).ToArray()
```suggestion
                ? readBuffer.AsSpan(0, (int)bytesRead).ToArray()
```

2021-08-04 09:54 UTC, turbedi commented on OpenTabletDriver/Devices/WinUSB/WinUSBInterfaceStream.cs
> +                writeBuffer.AsSpan().Fill(0);
```suggestion
                writeBuffer.AsSpan().Clear();
```

2021-09-05 19:42 UTC, InfinityGhost requested changes
Everything for the most part looks good, just some formatting changes and some general questions.

2021-09-05 19:42 UTC, InfinityGhost commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +            return Task.FromResult(tablet.GetDeviceString((byte)index));
Is this cast necessary?

2021-09-05 19:42 UTC, InfinityGhost commented on OpenTabletDriver/Devices/RootHub.cs
> +                           select type;
```suggestion
            var rootHubs = from type in Assembly.GetExecutingAssembly().DefinedTypes
                where type.GetCustomAttribute<RootHubAttribute>() != null
                where type.GetCustomAttribute<SupportedPlatformAttribute>()?.IsCurrentPlatform ?? true
                select type;
```

2021-09-05 19:42 UTC, InfinityGhost commented on OpenTabletDriver/Devices/WinUSB/WinUSBInterface.cs
> +                                 (ushort)sizeof(DeviceDescriptor));
```suggestion
                var packet = SetupPacket.MakeGetDescriptor(
                    RequestInternalType.Standard,
                    RequestRecipient.Device,
                    DescriptorType.Device, 0,
                    (ushort)sizeof(DeviceDescriptor)
                );
```

2021-09-05 19:42 UTC, InfinityGhost commented on OpenTabletDriver/Devices/WinUSB/WinUSBInterface.cs
> +                IntPtr.Zero);
```suggestion
                IntPtr.Zero
            );
```

2021-09-05 19:42 UTC, InfinityGhost commented on OpenTabletDriver/Devices/WinUSB/WinUSBInterfaceStream.cs
> +        public Stream Stream => throw new System.NotImplementedException();
This needs to be implemented or the exception needs to be changed.

2021-09-05 19:42 UTC, InfinityGhost commented on OpenTabletDriver/Devices/WinUSB/WinUSBRootHub.cs
> +            new("{62f12d4c-3431-4efd-8dd7-8e9aab18d30c}"),
I'm not a huge fan of `new()` without a type name unless its a really long type name.
```suggestion
            // Standard WinUSB (Zadig)
            new Guid("{dee824ef-729b-4a0e-9c14-b7117d33a817}"),
            // Huion WinUSB
            new Guid("{62f12d4c-3431-4efd-8dd7-8e9aab18d30c}"),
```

2021-09-05 19:42 UTC, InfinityGhost commented on OpenTabletDriver/OpenTabletDriver.csproj
> +    <ProjectReference Include="..\OpenTabletDriver.Native\OpenTabletDriver.Native.csproj" />
I think we have to expose this library as a NuGet package to do this, not a big deal but really not ideal for maintenance.

2021-09-05 19:56 UTC, X9VoiD commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +            return Task.FromResult(tablet.GetDeviceString((byte)index));
It is required. OTD won't compile without the cast.

2021-09-05 20:07 UTC, X9VoiD commented on OpenTabletDriver/OpenTabletDriver.csproj
> +    <ProjectReference Include="..\OpenTabletDriver.Native\OpenTabletDriver.Native.csproj" />
Not sure what you meant here, we're referencing `OTD.Plugin` here as another project, not the NuGet package of it. It's the same thing for `OTD.Native`. It is also actually recommended that we don't expose any p/invoke directly as public method in libraries. Creating a NuGet package full of public p/invokes doesn't seem right.

2021-09-05 20:09 UTC, InfinityGhost commented on OpenTabletDriver/OpenTabletDriver.csproj
> +    <ProjectReference Include="..\OpenTabletDriver.Native\OpenTabletDriver.Native.csproj" />
This library is used in osu!Framework, NuGet packages are not built with their dependencies included. You have to publish each dependency (like we did OpenTabletDriver.Plugin) in order for it to be able to build in o!f.

2021-09-05 20:12 UTC, X9VoiD commented on OpenTabletDriver/Devices/WinUSB/WinUSBInterfaceStream.cs
> +        public Stream Stream => throw new System.NotImplementedException();
There's no reason to implement it here (doing so requires that we convert the whole thing into an implementation of `Stream`, which should be for another PR), and `NotImplemented` is the best exception that describes the situation. We may also just remove`Stream` from the interface itself since it's not used anywhere.

2021-09-05 20:15 UTC, InfinityGhost commented on OpenTabletDriver/Devices/WinUSB/WinUSBInterfaceStream.cs
> +        public Stream Stream => throw new System.NotImplementedException();
Might just be worth removing it then. I wanted to expose it for future use but its unlikely it will get used.

2021-09-05 20:16 UTC, X9VoiD commented on OpenTabletDriver/OpenTabletDriver.csproj
> +    <ProjectReference Include="..\OpenTabletDriver.Native\OpenTabletDriver.Native.csproj" />
Then shouldn't `OTD.Plugin` be referenced through it's NuGet then rather than the project? Because right now it doesn't even use the `OTD.Plugin` NuGet package.

2021-09-05 20:18 UTC, X9VoiD commented on OpenTabletDriver/Devices/WinUSB/WinUSBInterfaceStream.cs
> +        public Stream Stream => throw new System.NotImplementedException();
Resolved by removing `Stream`.

2021-09-05 20:33 UTC, InfinityGhost commented on OpenTabletDriver/OpenTabletDriver.csproj
> +    <ProjectReference Include="..\OpenTabletDriver.Native\OpenTabletDriver.Native.csproj" />
> Then shouldn't `OTD.Plugin` be referenced through it's NuGet then rather than the project? Because right now it doesn't even use the `OTD.Plugin` NuGet package.

It does use it when implementing it outside of the project. It just needs a match for the assembly which the NuGet package provides and it compiles.

2021-09-06 21:40 UTC, InfinityGhost approved these changes

2021-09-06 21:40 UTC, merged