HS64 V2-re
OpenTabletDriver/OpenTabletDriver pull request #1364
Opened 2021-08-21 16:25 UTC by SnowLire

2021-08-30 15:11 UTC, InfinityGhost requested changes
File extension for the configuration should be `.json`, OpenTabletDriver ignores anything without it.

2021-08-30 15:18 UTC, SnowLire commented
Fixed

2021-09-05 23:29 UTC, InfinityGhost commented on OpenTabletDriver/Configurations/Huion/HS64 V2.json
> +  "Name": "Huion HS64 V2",
Is this really a V2 tablet or is it another identifier for the tablet?

2021-09-06 04:19 UTC, SnowLire commented on OpenTabletDriver/Configurations/Huion/HS64 V2.json
> +  "Name": "Huion HS64 V2",
Afaik it's a different device string so I went with the safe route and make a different config.

2021-09-06 22:30 UTC, InfinityGhost commented on OpenTabletDriver/Configurations/Huion/HS64 V2.json
> +  "Name": "Huion HS64 V2",
Makes more sense to just add another identifier IMO, as long as the specifications are the same there's no reason for it to change.

2021-09-07 08:29 UTC, SnowLire commented on OpenTabletDriver/Configurations/Huion/HS64 V2.json
> +  "Name": "Huion HS64 V2",
Done.

2021-10-17 03:33 UTC, InfinityGhost commented
Migrate to the new configuration directory.

2021-11-04 02:51 UTC, merged