Added XP-Pen Deco mini 4 config
OpenTabletDriver/OpenTabletDriver pull request #1373
Opened 2021-08-28 12:22 UTC by Ivanoks

2021-08-30 15:07 UTC, InfinityGhost requested changes
TABLETS.md must be updated to include this tablet. It should include any of its missing features, quirks, etc. in order to be accepted.

2021-09-03 20:27 UTC, Ivanoks commented
I asked a friend who has a Deco mini 4, he said that everything works.

2021-09-03 20:43 UTC, Mrcubix commented
You need to add a new entry in `Tablets.md` with the tablet, the status (which will be "Missing Features if the wheel doesn't work (if it has one)) and the note (if it's missing features, which ones).

Preferably add it before `XP-Pen Deco Mini7`.

2021-09-07 16:18 UTC, Ivanoks commented
I apologize very much for the delay, the school just caught up with me, in short, I updated the config, and it works too. (I fucked up with the push level.)

2021-09-07 16:28 UTC, X9VoiD requested changes

2021-09-07 16:28 UTC, X9VoiD commented on OpenTabletDriver/Configurations/XP-Pen/Deco mini 4.json
> +        "ArAEAAAAAAAAAAAA"
No need to specify trailing zeroes.

```suggestion
        "ArAE"

```

2021-09-07 16:29 UTC, Ivanoks commented on OpenTabletDriver/Configurations/XP-Pen/Deco mini 4.json
> +        "ArAEAAAAAAAAAAAA"
Oh okay, sorry.

2021-09-07 16:43 UTC, X9VoiD approved these changes
Ah, I mistakenly added a newline, other than that the config is fine now. Btw, what is the "missing feature"?

2021-09-07 16:52 UTC, Ivanoks commented
> Ah, I mistakenly added a newline, other than that the config is fine now. Btw, what is the "missing feature"?

Nothing, Deco mini7 has nothing written, although it is in missing feature.

2021-09-07 17:54 UTC, X9VoiD commented
Mark it is `Supported`.

2021-09-07 18:18 UTC, Ivanoks commented
> Mark it is `Supported`.

Did.

2021-11-04 02:47 UTC, merged