Do not setup device notification hooks on Windows 7 and below
OpenTabletDriver/OpenTabletDriver pull request #1415
Opened 2021-09-09 13:03 UTC by X9VoiD

## Changes

- Fixes daemon crash on Windows 7 and below.
- Log WinUSB warning when running on Windows 7 and below.

2021-09-26 16:43 UTC, InfinityGhost approved these changes

2021-09-26 16:44 UTC, InfinityGhost requested changes

2021-09-26 16:44 UTC, InfinityGhost commented on OpenTabletDriver/Devices/WinUSB/WinUSBRootHub.cs
> +                Log.Write(nameof(WinUSBRootHub), $"WinUSB device connections or disconnections won't be detected automatically and require Daemon restart.", LogLevel.Warning);
This is implemented in the core library, this won't fly in the osu!framework implementation.

2021-09-27 02:27 UTC, X9VoiD commented on OpenTabletDriver/Devices/WinUSB/WinUSBRootHub.cs
> +                Log.Write(nameof(WinUSBRootHub), $"WinUSB device connections or disconnections won't be detected automatically and require Daemon restart.", LogLevel.Warning);
Windows 7 is EOL, it shouldn't be mandatory to fully support Windows 7 anymore. If it's troubling you that o!f might not accept this quirk then talk to them rather than assuming. Anyways, the review is outside of this PR's scope as that implies that we should fix a very special edge case just to support Win7 and below, all of which are EOL.

2021-09-27 13:52 UTC, InfinityGhost commented on OpenTabletDriver/Devices/WinUSB/WinUSBRootHub.cs
> +                Log.Write(nameof(WinUSBRootHub), $"WinUSB device connections or disconnections won't be detected automatically and require Daemon restart.", LogLevel.Warning);
All I want is the message changed to be more generic for implementers.

2021-09-27 21:57 UTC, X9VoiD commented on OpenTabletDriver/Devices/WinUSB/WinUSBRootHub.cs
> +                Log.Write(nameof(WinUSBRootHub), $"WinUSB device connections or disconnections won't be detected automatically and require Daemon restart.", LogLevel.Warning);
Ah gotcha, Daemon name lmao. Almost thought I have to work with ancient APIs again

2021-09-30 02:42 UTC, X9VoiD commented on OpenTabletDriver/Devices/WinUSB/WinUSBRootHub.cs
> +                Log.Write(nameof(WinUSBRootHub), $"WinUSB device connections or disconnections won't be detected automatically and require Daemon restart.", LogLevel.Warning);
Resolved.

2021-09-30 03:55 UTC, InfinityGhost approved these changes

2021-09-30 03:55 UTC, merged