Added Chinese README
OpenTabletDriver/OpenTabletDriver pull request #1455
Opened 2021-09-23 11:43 UTC by Asiimoviet

2021-09-23 12:58 UTC, shugen002 requested changes
机翻明显，建议自行润色修改后再提交。

2021-09-23 13:31 UTC, Asiimoviet commented
@shugen002 草其实我是自己翻的，我改一改吧，水平不足

2021-09-24 00:38 UTC, shugen002 requested changes

2021-09-24 00:38 UTC, shugen002 commented on README_CN.md
> +所有已经被支持的、未测试的、以及计划被支持的数位板都可以在这里被找到。如果您的数位板无法正常工作的话可以在Wiki之中寻找一些解决方法
```suggestion
所有已经被支持的、未测试的、以及计划被支持的数位板都可以在这里被找到。如果您的数位板在您的平台上无法正常工作的话可以在Wiki之中寻找一些解决方法
```

2021-09-24 00:38 UTC, shugen002 commented on README_CN.md
> +OpenTabletDriver有两个独立的进程共同工作。主程序`OpenTabletDriver.Daemon`会处理所有的数位板的数据，而GUI前端则是由`OpenTabletDriver.UX.*`负责（这里的`*`取决于您的平台<sup>1</sup>）。主进程必须被启动程序才能工作，可是GUI进程则是可选的。如果您已经配置好了，他们则会在主进程启动的时候自动生效。
```suggestion
OpenTabletDriver有两个独立的进程共同工作。主程序`OpenTabletDriver.Daemon`会处理所有的数位板的数据，而GUI前端则是由`OpenTabletDriver.UX.*`负责（这里的`*`取决于您的平台<sup>1</sup>）。主进程必须被启动，程序才能工作，不过GUI进程则是可选的。如果您已经配置好了设置，他们将会在主进程启动的时候自动生效。
```

2021-09-24 00:38 UTC, shugen002 commented on README_CN.md
> +# 自己编译OpenTabletDriver
```suggestion
# 从源码编译OpenTabletDriver
```

2021-09-24 00:38 UTC, shugen002 commented on README_CN.md
> +### 全平台
```suggestion
### 所有平台
```

2021-09-24 00:38 UTC, shugen002 commented on README_CN.md
> +OpenTabletDriver的要求在各个平台是一样的。而本软件在不同平台则是会有不同的依赖：
```suggestion
编译OpenTabletDriver的要求在各个平台是一样的，在不同的平台运行本软件需要有不同的依赖：
```

这句我也稍微有点纠结。。。

2021-09-24 00:38 UTC, shugen002 commented on README_CN.md
> +  - 外接设备的自定义
？？？

2021-09-24 00:38 UTC, shugen002 commented on README_CN.md
> +  - 通过`%localappdata%`或者`.config`里的`settings.json`自动加载用户的设置
```suggestion
  - 自动加载当前用户的 `%localappdata%` 或者 `.config` 中 `settings.json` 保存的设置
```

2021-09-24 00:38 UTC, shugen002 commented on README_CN.md
> +  - Tools
```suggestion
  - 过滤器
  - 输出模式
  - 工具
```

2021-09-24 00:38 UTC, shugen002 commented on README_CN.md
> +OpenTabletDriver是一个开源的，跨平台的数位板驱动。其目标是在拥有直观的可自定义的界面的同时能跨平台地兼容尽可能多的设备。
```suggestion
OpenTabletDriver是一个开源的，跨平台的数位板驱动。其目标是在拥有直观的可自定义的界面的同时能跨平台并兼容尽可能多的设备。
```

2021-09-24 00:39 UTC, shugen002 commented on README_CN.md
> +如果你有任何的问题和建议，欢迎在[Issue中提出](https://github.com/OpenTabletDriver/OpenTabletDriver/issues/new/choose)。
```suggestion
如果你有任何的问题和建议，欢迎在[Issue](https://github.com/OpenTabletDriver/OpenTabletDriver/issues/new/choose)中提出。
```

2021-09-24 00:45 UTC, shugen002 commented
如果你觉得我的建议不太好的话，欢迎指出，毕竟我也不是职业翻译，🤣🤣🤣。

2021-09-24 00:56 UTC, Asiimoviet commented on README_CN.md
> +  - 外接设备的自定义
我不知道binding怎么翻 不是按键自定义吗？

2021-09-24 00:57 UTC, Asiimoviet commented
> 如果你觉得我的建议不太好的话，欢迎指出，毕竟我也不是职业翻译，🤣🤣🤣。

没有没有 我第一次翻译 很多东西不知道怎么翻 多谢指教

2021-09-24 01:15 UTC, shugen002 commented on README_CN.md
> +  - 外接设备的自定义
我觉得翻译成绑定比较合适
![image](https://user-images.githubusercontent.com/10257291/134603298-f12338f2-12ca-46d2-8921-0ceb8837070d.png)
![image](https://user-images.githubusercontent.com/10257291/134603392-063f00e7-1d4c-4ba0-a883-35f68a9c20ef.png)

机器翻译不是不能用，只是机器翻译对于上下文及日常语法处理不太好，需要进行修改才能使用。（这个谷歌翻译的结果我也是不满意的）

另外一个不一定要完全对应原文，如果觉得不舒服，抛开原文，用自己的表达来描述同样的东西也不是不行。

2021-09-24 01:25 UTC, Asiimoviet commented on README_CN.md
> +  - 外接设备的自定义
那如果是这样的话我觉得还是自定义合适一点 把它改通顺一点就好了

2021-09-24 01:27 UTC, Asiimoviet commented on README_CN.md
> +  - 外接设备的自定义
你看看最新的commit

2021-09-24 01:49 UTC, shugen002 requested changes

2021-09-24 01:49 UTC, shugen002 commented on README_CN.md
> +  - 外接设备
理解有点偏差，同时原文分点好像不太好？

2021-09-24 02:02 UTC, Asiimoviet commented on README_CN.md
> +  - 外接设备
好的 等中午下课我加进去

2021-09-24 05:47 UTC, Asiimoviet commented on README_CN.md
> +  - 外接设备
我不知道为什么上不去discord
要不这些分点就不要了吧 就写按键自定义

2021-09-30 05:04 UTC, shugen002 commented on README_CN.md
> +  - 外接设备
```
支持将笔尖压力、笔的快捷按钮和数位板上的快捷键映射为鼠标按键、键盘按键或插件提供的操作
```
你觉得这样怎么样？

2021-10-04 13:28 UTC, Asiimoviet commented on README_CN.md
> +  - 外接设备
可以

2021-10-04 13:31 UTC, Asiimoviet commented
可以了 看看还有没有修正？可以merge一下

2021-10-05 07:15 UTC, shugen002 commented
LGTM。

2021-10-05 07:18 UTC, shugen002 commented
LGTM

2021-10-06 20:15 UTC, merged