Intuos 1 mouse support
OpenTabletDriver/OpenTabletDriver pull request #1472
Opened 2021-10-01 01:09 UTC by EriDere

**Summary of changes:**
- Adds a basic mouse parser for Intuos 1 tablets, based on the existing Intuos 3 mouse parser. 
- Updates Intuos 1 tablet configs to add mouse options.

**Current issues/limitations:**
- Scrollwheel parser is an imperfect placeholder as it ignores the intended analogue reports and simply outputs a definite direction.
- Mouse parsing is slightly messy due to parsing empty mouse reports that occur every other report as "null."
- There is a small chance that this parser change may cause unintended behaviour for other tablets that use the IntuosV1 parser due to the sheer number of tablets that share the same parser. I have no way of testing other models myself, so this should be checked by those who are able.

2021-10-01 03:05 UTC, X9VoiD requested changes

2021-10-01 03:05 UTC, X9VoiD commented on OpenTabletDriver/Vendors/Wacom/IntuosV1/IntuosV1MouseReport.cs
> +                    Y = report[8].IsBitSet(3) && report[6] > 0 ? 1 : report[6] > 0 ? -1 : 0 // ignores analogue mouse wheel info and simply reports whether the mouse wheel is spun upwards or downward
```suggestion
            var scrollAmount = (report[6] << 2) | ((report[7] >> 6) & 0b11);
            Scroll = new Vector2
            {
                    Y = report[8].IsBitSet(3) ? scrollAmount : -scrollAmount
```

2021-10-01 03:05 UTC, X9VoiD commented on OpenTabletDriver/Vendors/Wacom/IntuosV1/IntuosV1ReportParser.cs
> +                return null;
See if this works better.
```suggestion
            if (((report[1] >> 1) & 0x0F) == 0x04)
                return new IntuosV1MouseReport(report);
```

2021-10-04 16:27 UTC, InfinityGhost requested changes

2021-10-04 16:27 UTC, InfinityGhost commented on OpenTabletDriver/Vendors/Wacom/IntuosV1/IntuosV1MouseReport.cs
> +            };
Fix formatting
```suggestion
            Scroll = new Vector2
            {
                Y = report[8].IsBitSet(3) ? scrollAmount : -scrollAmount
            };
```

2021-10-04 20:10 UTC, EriDere commented on OpenTabletDriver/Vendors/Wacom/IntuosV1/IntuosV1ReportParser.cs
> +                return null;
Discussed this on Discord the other day, but figured I'd note the same things here for the sake of organization.

This parser change works aside from the mouse sometimes immediately sending and holding whatever left click is bound to when it enters range of the tablet, particularly from the edges of the tablet area. From the Discord conversation, it sounded as if this was a known issue with all tablet tools and is something that is beyond the scope of this particular parser, so if that is confirmed to be the case then this change can be committed.

2021-10-31 18:29 UTC, EriDere commented
Went ahead and committed the parser change suggestion I'd been holding out on. This change does still have the issue of sometimes randomly "locking" the pen tip binding while using the mouse (particularly upon entry and exit of the mouse into range of the tablet), but it sounds as if this issue is due to the way OTD handles out of range reports and is entirely out of the scope of this parser unless reports are manually nullified like I originally had in my parser solution (which certainly isn't a clean or optimal implementation). 

But assuming the randomly sticking pen tip binding is due to the suspected out of range report issue, this parser works on all other accounts. It is just a bit buggy and annoying to use with its current functionality when you have pen tip bound to something.

2021-12-01 02:51 UTC, gonX commented
Is your last comment perhaps addressed by #1676 ?

2021-12-02 05:25 UTC, EriDere commented
It may help solve some issues if functional beyond Artist Mode on Linux (all my testing with this parser has been on Windows), but it in all likelihood won't solve the specific issue here. The parser is currently hard-coded in IntuosV1ReportParser based on certain bytes the tablet gives while using the mouse rather than using the tablet tool system like it likely should be. This is both due to the current Intuos 3 mouse parser using a similar system as well as tablet tools not working properly (or at all) on Windows in general (which may have been fixed since last time this was brought up on Discord; need to check master). But if the tool handling on Windows is fixed and out of range reports are made more resilient against some of the weird states that can occur, I think a rewrite of this (and possibly also the Intuos 3 mouse parser) to use the tablet tool system would both fix all major issues and make the mouse parser more consistent with the parsing of other tablet tools. 

So TLDR, it should help but I think a future rewrite of this parser is the best solution.

2021-12-02 05:29 UTC, EriDere commented
I'll leave this pr as-is for the time being since it does match the current Intuos 3 mouse parser, but may switch to draft if Windows tool reports and out of range stuff are confirmed to be fixed soon since I don't think this is the optimal parser solution if those two things get fixed.

2022-11-07 13:35 UTC, gonX commented
Any updates on this PR? I'm not sure if we have anything on our end that is being held up here

2022-11-07 15:16 UTC, EriDere commented
Closing, as the way this parser is handled isn't optimal, and parser improvements such as #2260 will supercede functionality if expanded to include mouse/tool support.

2022-11-07 15:16 UTC, closed without merging