Colorize entries in console tab based on LogLevel
OpenTabletDriver/OpenTabletDriver pull request #1568
Opened 2021-10-29 22:26 UTC by Sublimelime

A small enhancement PR to add code to colorize entries in the Console tab based on their LogLevel severity. Creates greater visual clarity (easy to spot errors quickly) and uses black text on light pastel colors to ensure readability with the exception of Fatal errors, which use white text on a dark red to really stand out.

An image of how it looks with different types of LogLevel messages printed out manually is attached. Open to feedback on the colors, and whether or not the Debug level should be colorized or remain black on white like Info still is.

![Console coloration](https://user-images.githubusercontent.com/10090332/139507727-702ee59e-5ff6-407e-a89c-cae9595aff34.png)

2021-10-29 22:36 UTC, jamesbt365 commented
How does this handle with gtk themes?

2021-10-29 22:49 UTC, jamesbt365 commented
Turns out, they don't.
![image](https://user-images.githubusercontent.com/22662856/139509271-8970ba31-9c1c-424f-8d58-da860f759beb.png)

2021-10-29 23:39 UTC, Sublimelime commented
Converting to draft until we can make sure this change plays nice with themes and all 3 platforms.

2021-10-30 00:19 UTC, InfinityGhost requested changes

2021-10-30 00:19 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/LogView.cs
> +                        break;
Remove this so it will conform with the native theme instead.

2021-10-30 00:32 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/LogView.cs
> +                        break;
```suggestion
                    default:
                        entry.ForegroundColor = SystemColors.ControlText;
                        entry.BackgroundColor = SystemColors.ControlBackground;
                        break;
```

2021-10-30 01:55 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/LogView.cs
> +            if (OpenTabletDriver.Interop.SystemInterop.CurrentPlatform != PluginPlatform.MacOS)
```suggestion
            if (Interop.SystemInterop.CurrentPlatform != PluginPlatform.MacOS)
```

2021-10-30 04:20 UTC, Sublimelime commented on OpenTabletDriver.UX/Controls/LogView.cs
> +            if (OpenTabletDriver.Interop.SystemInterop.CurrentPlatform != PluginPlatform.MacOS)
Hah, still getting used to C#'s access and stuff. Didn't know Interop was directly accessible, sorry for making you fix something so simple... ;P

2021-11-10 15:39 UTC, Sublimelime commented
![WPF weird log borders](https://user-images.githubusercontent.com/10090332/141143256-0669c3f5-9e9f-478f-9cf8-d55755bd2476.png)

@Kuuuube I may have a fix for this if it's still happening after 2afdc47, I'm gonna do some testing today on my windows machine (as I don't get this on linux at all -- seems GTK doesn't show those borders) and see if I can make it look clean on windows too (like the screenshot in the PR message).

2021-11-11 01:29 UTC, Sublimelime commented
Drafting once again as there's still unresolved minor issues with windows (though GTK works fine). Current appearance on Windows: 

![Capture](https://user-images.githubusercontent.com/10090332/141220437-d46858b8-c410-4759-9557-fa2c6d6829ee.PNG)

Notable problems:

- Selecting rows only highlights the borders in blue, instead of inverting the entire row to white on blue
- Ugly white borders around each row and column, especially noticeable on colored rows

2021-12-29 17:29 UTC, Sublimelime commented
Closing this due to unresolved issues, and impending gui rewrite in 0.7.0. Will revisit once rewrite to MAUI is complete, it may be easier or doable with icons instead of changing the background color.

2021-12-29 17:29 UTC, closed without merging