BindingState: Only invoke IInterruptBinding handler when state has changed
OpenTabletDriver/OpenTabletDriver pull request #1577
Opened 2021-10-31 18:07 UTC by gonX

This caused some headaches in attempting to implement passthrough aux keys, as the binding handler seems to iterate over all aux keys bindings when any key is pressed, resulting in `IInterruptBinding`s being invoked when they weren't actually intended to be.

Pre-PR:
`IInterruptBinding`s are invoked if any key in the matrix is activated, even if that key itself isn't bound to it; ie binding 1 has pen passthrough but binding 3 does not - clicking binding 3 still activated the pen passthrough feature.

Post-PR
`IInterruptBinding`s are only invoked when state has changed, likely resulting in more accurate results.

As a side note, if you're using a tablet which supports multiple held keys simultaneously, it is possible to get non-Passthrough buttons "stuck" in an activated state. This can also happen pre-PR on non-Aux buttons so this PR brings it more in line with IStateBindings.

2021-10-31 18:23 UTC, X9VoiD requested changes

2021-10-31 18:23 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Binding/BindingState.cs
> +                if ((newState && !PreviousState) || (!newState && PreviousState))
Won't something like this be enough?
```suggestion
                if (newState != PreviousState)
```

2021-10-31 18:28 UTC, gonX commented
Actually, one breaking change I noticed is that this breaks pen passthrough tip bindings resulting in pressure not being continually updated.

2021-10-31 18:36 UTC, gonX commented
Closing for now since that is such a breaking change for preparation that might not even be necessary.

2021-10-31 18:36 UTC, closed without merging

2021-12-07 08:07 UTC, gonX commented
Something something to link #1578 to this