Add contribution guidelines
OpenTabletDriver/OpenTabletDriver pull request #1590
Opened 2021-11-01 22:51 UTC by InfinityGhost

Added contribution guidelines, along with associated branch rules.

2021-11-01 22:59 UTC, EXtremeExploit commented
what about end of line at the end of files?

2021-11-01 23:09 UTC, Sublimelime requested changes

2021-11-01 23:09 UTC, Sublimelime commented on CONTRIBUTING.md
> +- Follow the language's documented formatting guidelines.
I would add a link to said guidelines (are we using Microsoft's?) or an explanation of what we do, like the whole "curly brackets on their own line" and "space between 'if' and condition", etc

2021-11-01 23:09 UTC, Sublimelime commented on CONTRIBUTING.md
> +
I would add:

- Avoid merging master into your branch, unless it's to fix a merge conflict
- If your PR fixes an issue, include the keyword to make it auto-close the issue on merge ("fixes \#number")
- Keep PRs to one fix/purpose, to ease merging

2021-11-01 23:09 UTC, Sublimelime commented on CONTRIBUTING.md
> +
I would add 

> Include contact info of the person asking for support, such as an @ for their account on github, a discord username, etc, for functionality verification"

2021-11-02 15:56 UTC, Sublimelime approved these changes

2021-11-02 16:09 UTC, MishterKirby approved these changes

2021-11-04 00:25 UTC, jamesbt365 approved these changes

2021-11-04 01:19 UTC, merged