Add FR README
OpenTabletDriver/OpenTabletDriver pull request #1595
Opened 2021-11-02 10:10 UTC by Biokax

Hi,

this is a proposal for the french translation of the readme file.
I will try to make native peoples reviews this before merge

may check links because the copy of the readme was old

2021-11-02 12:52 UTC, Mrcubix requested changes
Most of the translation is fine, i would however ask you to make the following changes

2021-11-02 12:52 UTC, Mrcubix commented on README_FR.md
> +# Exécuter un binaire OpenTabletDriver
I don't think you can translate it that way, at the end of the day, some french users are going to ask themselves, what is software binary? The answer is simple, in this case, it's an executable.
So i a think a better translation would be simply the following:
```suggestion
# Executer OpenTabletDriver
```

2021-11-02 12:52 UTC, Mrcubix commented on README_FR.md
> +  - Raccourcis express
```suggestion
  - Raccourcis touches express
```

2021-11-02 12:52 UTC, Mrcubix commented on README_FR.md
> +Pour build un ARM Linux, exécutez le 'build.sh' fourni
```suggestion
Pour build sur ARM Linux, exécutez le 'build.sh' fourni 
```

2021-11-02 12:55 UTC, Biokax commented on README_FR.md
> +# Exécuter un binaire OpenTabletDriver
Indeed that better

2021-11-02 13:00 UTC, Mrcubix commented on README_FR.md
> +# Executer OpenTabletDriver
small mistake on my part missing an accent is missing
```suggestion
# Exécuter OpenTabletDriver
```

2021-11-02 16:06 UTC, Sublimelime commented on README_FR.md
> +Commande symlink utilisée sur Fedora 34:
This part about symlinking the library potentially shouldn't be included as it was fixed in #1505 and shouldn't be necessary anymore.... though we kinda have the issue that it's fixed for 0.6 but is still necessary on stable 0.5. @X9VoiD or @InfinityGhost should advise whether or not to include it.

2021-11-04 00:28 UTC, InfinityGhost commented on README_FR.md
> +Commande symlink utilisée sur Fedora 34:
It is no longer required so I wouldn't mention it anymore.

2021-11-04 09:58 UTC, Biokax commented on README_FR.md
> +Commande symlink utilisée sur Fedora 34:
I removed it

2021-11-04 14:21 UTC, Sublimelime approved these changes
Note for the future that it's unnecessary to merge our master into your branch/master unless there's merge conflicts you have to resolve, git handles it fine.

2021-11-05 02:09 UTC, InfinityGhost approved these changes

2021-11-05 02:26 UTC, Mrcubix requested changes
Second review of stuff i've missed, Should be merged after the suggested modifications are applied.

2021-11-05 02:26 UTC, Mrcubix commented on README_FR.md
> +OpenTabletDriver est un driver de tablette en mode utilisateur, open source et multiplateforme. Le but d'OpenTabletDriver est d'être compatible avec le plus de plateforme possibles, et ce avec une in
```suggestion
OpenTabletDriver est un driver de tablette en mode utilisateur, open source et multiplateforme. Le but d'OpenTabletDriver est d'être compatible avec le plus de plateforme possibles, et ce grâce à une interface graphique utilisateur facilement configurable.
```

2021-11-05 02:26 UTC, Mrcubix commented on README_FR.md
> +cela va également produire des binaires utilisables dans 'OpenTabletDriver/bin'.
```suggestion
cela va également produire des exécutables utilisables dans 'OpenTabletDriver/bin'.
```

2021-11-08 17:20 UTC, merged