Update contributing information in README
OpenTabletDriver/OpenTabletDriver pull request #1608
Opened 2021-11-05 14:03 UTC by Sublimelime

Small PR to update the main readme with information on the new CONTRIBUTING.md and some info on the process of adding support for a new tablet.

2021-11-05 14:13 UTC, X9VoiD approved these changes

2021-11-08 20:57 UTC, InfinityGhost requested changes

2021-11-08 20:57 UTC, InfinityGhost commented on README.md
> +back-and-forth involved*.
```suggestion
[discord](https://discord.gg/9bcMaPkVAR) asking for support. *We generally
prefer that adding support for a tablet be done through discord, due to the
back-and-forth involved*.
```

2021-11-09 16:23 UTC, InfinityGhost approved these changes

2021-11-09 16:24 UTC, merged