Fix incorrect log
OpenTabletDriver/OpenTabletDriver pull request #1618
Opened 2021-11-09 15:20 UTC by X9VoiD

2021-11-09 15:38 UTC, Sublimelime commented on OpenTabletDriver.Desktop/DesktopDeviceConfigurationProvider.cs
> +                Log.Write("Detect", $"The configuration overrides directory '{AppInfo.Current.ConfigurationDirectory}' exist.", LogLevel.Debug);
Grammar/rephrase:

`$"Configuration overrides exist in '{AppInfo.Current.ConfigurationDirectory}', overriding built-in configs.`

If no rephrase is necessary, just add an S to "exist".

2021-11-09 16:38 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/DesktopDeviceConfigurationProvider.cs
> +                Log.Write("Detect", $"The configuration overrides directory '{AppInfo.Current.ConfigurationDirectory}' exist.", LogLevel.Debug);
Made edits to @Sublimelime's review.

2021-11-09 16:38 UTC, InfinityGhost requested changes
Apply @Sublimelime's changes.

2021-11-09 17:18 UTC, Sublimelime commented on OpenTabletDriver.Desktop/DesktopDeviceConfigurationProvider.cs
> +                Log.Write("Detect", $"The configuration overrides directory '{AppInfo.Current.ConfigurationDirectory}' exist.", LogLevel.Debug);
Thanks, still don't know how to make github do that...

2021-11-09 17:26 UTC, Sublimelime approved these changes

2021-11-11 01:22 UTC, InfinityGhost approved these changes

2021-11-11 01:23 UTC, merged