Fix logging UI deadlock
OpenTabletDriver/OpenTabletDriver pull request #1619
Opened 2021-11-09 16:23 UTC by InfinityGhost

The blocking collection causes the UI to freeze when logging from separate threads, this returns it to a concurrent collection to mitigate this.

2021-11-09 17:32 UTC, X9VoiD requested changes
Currently there are two copies of the same log, one in Daemon, the other in UX. Eto.Forms also allocates separately for displaying the logs itself. All of this is *never trimmed*, and will grow indefinitely until host memory is exhausted. Should do something about that.

2021-11-09 17:32 UTC, X9VoiD commented on OpenTabletDriver.UX/Controls/LogView.cs
> +            foreach (var message in currentMessages.Take(150))
This creates a bug where *only the first 150 logs* will be taken from Daemon, causing inconsistent logging. It will look as if there's a hole in the logs after that first 150.

2021-11-09 17:32 UTC, X9VoiD commented on OpenTabletDriver.UX/Tools/LogDataStore.cs
> +        private readonly ConcurrentQueue<LogMessage> messages = new ConcurrentQueue<LogMessage>();
It's not trimming the logs so this will grow indefinitely, causing memory hogging problems.

2021-11-11 04:46 UTC, InfinityGhost commented on OpenTabletDriver.UX/Tools/LogDataStore.cs
> +        private readonly ConcurrentQueue<LogMessage> messages = new ConcurrentQueue<LogMessage>();
Fixed.

2021-11-11 04:52 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/LogView.cs
> +            foreach (var message in currentMessages.Take(150))
Resolved.

2021-11-11 05:06 UTC, X9VoiD requested changes

2021-11-11 05:06 UTC, X9VoiD commented on OpenTabletDriver.UX/Tools/LogDataStore.cs
> +            messages = new ConcurrentQueue<LogMessage>(messageList);
```suggestion
            messages = new ConcurrentQueue<LogMessage>(currentMessages.TakeLast(MAX_NUM_MESSAGES));
```

2021-11-11 05:12 UTC, InfinityGhost commented on OpenTabletDriver.UX/Tools/LogDataStore.cs
> +            messages = new ConcurrentQueue<LogMessage>(messageList);
Honestly no idea how I forgot that function existed

2021-11-11 05:18 UTC, Sublimelime commented
This only effects the display of the log in the console tab, right? Exporting diags and viewing daemon.log to see the full console output still works fine?

2021-11-11 05:18 UTC, X9VoiD commented
Yes

2021-11-11 05:19 UTC, X9VoiD approved these changes

2021-11-11 05:20 UTC, merged