Brazzilian Portuguese translation
OpenTabletDriver/OpenTabletDriver pull request #1642
Opened 2021-11-13 19:16 UTC by purplerockamethyst

Created `README_PT-BR.md`, translation is based off `README.MD`

2021-11-16 22:44 UTC, zsinx6 reviewed
Just hit this PR and decided to make some contributions, since I'm also from Brazil. Thanks for you contribution, the translation is very good!

2021-11-16 22:44 UTC, zsinx6 commented on README_PT-BR.md
> +O OpenTabletDriver é um driver em modo de usuário, código-aberto e multi plataforma. O objetivo de OpenTabletDriver é ser multi-plataforma com a maior compatibilidade em uma interface gráfica configu
```suggestion
O OpenTabletDriver é um driver em modo de usuário, código-aberto e multi plataforma. O objetivo do OpenTabletDriver é ser multi-plataforma com a maior compatibilidade em uma interface gráfica configurável e fácil de usar. 
```

2021-11-16 22:44 UTC, zsinx6 commented on README_PT-BR.md
> +Todos os estados das mesas serão suportado, não testado, e planejado á ter suporte podem ser encontrados aqui. Soluções para problemas comuns podem ser encontrados na wiki para sua plataforma.
```suggestion
Todos os estados das mesas que estão suportadas, não testado, e planejado a ter suporte podem ser encontrados aqui. Soluções para problemas comuns podem ser encontrados na wiki para sua plataforma. 
```

2021-11-16 22:44 UTC, zsinx6 commented on README_PT-BR.md
> +O OpenTabletDriver funciona como dois processos separados que se interagem entre si perfeitamente. O programa ativo que cuida de toda a informação da mesa é o `OpenTabletDriver.Daemon`, enquanto a in
```suggestion
O OpenTabletDriver funciona como dois processos separados que se interagem entre si perfeitamente. O programa ativo que cuida de toda a informação da mesa é o `OpenTabletDriver.Daemon`, enquanto a interface é `OpenTabletDriver.UX.*`, onde `*` depende de sua plataforma<sup>1</sup>. O Daemon deve ser iniciado para tudo funcionar, mas a interface é desnecessária. Se você tem configurações existentes, elas vão se aplicar assim que o daemon iniciar.
```

2021-11-16 22:44 UTC, zsinx6 commented on README_PT-BR.md
> +> <sup>1</sup>Windows usa o `Wpf`, Linux usa o `Gtk`, e MacOS usa  `MacOS` respectivamente. Isso por maior parte pode ser ignorada se você não o compilar do código fonte, como a versão correta será f
```suggestion
> <sup>1</sup>Windows usa o `Wpf`, Linux usa o `Gtk`, e MacOS usa  `MacOS` respectivamente. Essa parte pode ser ignorada se você não o compilar do código fonte, já que a versão correta será fornecida na instalação.
```

2021-11-16 22:44 UTC, zsinx6 commented on README_PT-BR.md
> +Os requerimentos para compilar o OpenTabletDriver é consistente entre todas as plataformas, A execução do OpenTabletDriver em cada plataforma requer dependências diferentes.
```suggestion
Os requerimentos para compilar o OpenTabletDriver são consistente entre todas as plataformas, A execução do OpenTabletDriver em cada plataforma requer dependências diferentes.
```

2021-11-16 22:44 UTC, zsinx6 commented on README_PT-BR.md
> +Nenhuma outra depedência
```suggestion
Nenhuma outra depedência.
```

2021-11-16 22:44 UTC, zsinx6 commented on README_PT-BR.md
> +  - External plugin bindings
```suggestion
```

2021-11-16 22:44 UTC, zsinx6 commented on README_PT-BR.md
> +  - Auto-loads user settings via `settings.json` in the active user `%localappdata%` or `.config` settings root directory.
```suggestion
```

2021-11-17 16:18 UTC, purplerockamethyst commented
I knew it probably had some stuff wrong, since i'm not really the best at translating stuff... thank you for fixing these small errors that i made

2021-11-18 03:20 UTC, zsinx6 commented
@purplerockamethyst You need to click in the commit buttons to add my suggestions to the PR

2021-11-24 17:58 UTC, zsinx6 commented
@purplerockamethyst can you change the PR title from Brazzilian to Brazilian?

2021-11-25 18:22 UTC, purplerockamethyst commented
yeah, i forgot about this, i clicked the commit buttons to add the suggestions

2022-03-29 23:51 UTC, nekoraw reviewed
made some spelling changes and translated everything that has been added since last time
i'd like some feedback from people to check this
im also a native brazilian speaker (yeah)

2022-11-07 13:36 UTC, gonX commented
@rockyamethyst Please respond to the suggested changes above. Once there are no more comments on the translation we can merge this.

2022-11-07 14:15 UTC, rockyamethyst commented
Yeah will commit everything to the branch, i only got an email because you mentioned me again

thanks github

btw sorry nekoraw for taking so long

2024-03-17 19:51 UTC, jamesbt365 requested changes
squash commits after please

2024-03-17 19:51 UTC, jamesbt365 commented on README_PT-BR.md
> +Para problemas e PRs relacionados ao empacotamento do OpenTabletDriver, por favor veja [este](https://github.com/OpenTabletDriver/OpenTabletDriver.Packaging) repositório.
Remove this line, packaging is done in this repo now since #2787.

2024-03-17 19:51 UTC, jamesbt365 commented on README_PT-BR.md
> +Para problemas e PRs relacionados à [página na web](https://opentabletdriver.net) do OpenTabletDriver, veja [este](https://github.com/OpenTabletDriver/OpenTabletDriver.Web) repositório.
Point this at opentabletdriver.github.io instead of OpenTabletDriver.Web, this repo is archived and no longer worked on since the move to github pages.

2024-03-17 20:09 UTC, jamesbt365 commented
I forgot to mention that the building OpenTabletDriver part has changed drastiscally since this was written, please take a look at that.

2024-03-17 20:46 UTC, jamesbt365 commented on README_PT-BR.md
> +- .NET 5 SDK
This should be dotnet 7 instead now.

2024-05-10 00:59 UTC, InfinityGhost commented
Superseded by #2494

2024-05-10 00:59 UTC, closed without merging