Add support for the Huion new 1060 plus 2048.
OpenTabletDriver/OpenTabletDriver pull request #1648
Opened 2021-11-15 01:27 UTC by jamesbt365

Verification:
https://canary.discord.com/channels/615607687467761684/615611007951306863/909609554482958377
https://canary.discord.com/channels/615607687467761684/615611007951306863/909613160141574205

2021-11-19 06:36 UTC, X9VoiD requested changes

2021-11-19 06:36 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/Huion/new 1060 plus 2048.json
> +  "Name": "Huion new 1060 plus (2048)",
```suggestion
  "Name": "Huion New 1060 Plus (2048)",
```
and rename the file to `New 1060 Plus (2048)`.

2021-11-19 06:36 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/Huion/new 1060 plus 2048.json
> +      "MaxY": 25000.0
What LPI is this tablet? Verify that the width and height is physically correct.

2021-11-21 20:41 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/Huion/New 1060 Plus (2048).json
> +  "Name": "Huion New 1060 plus (2048)",
Big Plus

2021-11-21 20:46 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/Huion/New 1060 Plus (2048).json
> +  "Name": "Huion New 1060 plus (2048)",
corrected.

2021-11-21 20:48 UTC, X9VoiD approved these changes

2021-11-21 20:49 UTC, merged