Add BuildDate attribute to track date of build
OpenTabletDriver/OpenTabletDriver pull request #1672
Opened 2021-11-28 03:02 UTC by Sublimelime

This is a small PR to add a build date attribute to OpenTabletDriver.Plugin, which can be accessed in-code through Plugin's assembly to obtain the date the binary was built.

This has been added in two places, the about screen and the export of a diagnostic.

Note that the version display in the window header, "OpenTabletDriver v0.6.0.0", hasn't changed.

The exported diag now looks like this....

```
{
  "App Version": "OpenTabletDriver v0.6.0.0, built on 11/27/2021",
  "Operating System": {
    "Platform": 4,
    "ServicePack": "",

.....
```

2021-11-28 03:36 UTC, InfinityGhost commented
This doesn't necessarily close #1221 however, we really want the git tag to be able to pinpoint a build. The method described in that issue is probably the best way to handle that issue, but this is a welcome addition anyway.

2021-11-28 03:57 UTC, Sublimelime commented
([Relevant discord convo](https://discord.com/channels/615607687467761684/628651971267788800/914359719957766145), putting this here for record keeping)

TLDR: PR is good but we should also include the git commit SHA in the InformationalVersion, to be done with build scripts, something like:

`/p:SourceRevisionId=$(git rev-parse --short HEAD)`

2021-11-28 04:15 UTC, InfinityGhost requested changes
Add the revision hash to all action builds.

2021-11-28 08:51 UTC, X9VoiD requested changes
Shell expansion won't work with single quotes, shell expansion also don't work within github's `env`, and using arrays when we're not addressing them as an array just makes it look complicated than it should be.

2021-11-28 08:51 UTC, X9VoiD commented on .github/workflows/dotnet.yml
> +          $options=@('--configuration Release', '-p:DebugType=embedded', '--no-self-contained', '-p:SourceRevisionId=$(git rev-parse --short HEAD)')
Revert all the future changes to just this.

and

```
options="--configuration Release -p:DebugType=embedded --no-self-contained -p:SourceRevisionId=$(git rev-parse --short HEAD)"
```

2021-11-28 08:51 UTC, X9VoiD commented on .github/workflows/dotnet.yml
> +          $options=@('--configuration Release', '-p:DebugType=embedded', '-p:PublishTrimmed=false', '--no-self-contained', '-p:SourceRevisionId=$(git rev-parse --short HEAD)')
Same for here

2021-11-28 09:01 UTC, X9VoiD requested changes

2021-11-28 09:01 UTC, X9VoiD commented on OpenTabletDriver.UX/App.cs
> +            Version = $"v{Version}, Built on {BuildDate}",
```suggestion
            Version = $"v{Version}, built on {BuildDate}",
```
But this in itself is a weird change for me, build date is not part of a version. The date that a software is built does not indicate the version, nor change its behaviour. We can have the same "version" of a software built on different dates.

This should be moved out to another entry in diagnostics, and removed from UX.

2021-11-28 15:09 UTC, Sublimelime commented on OpenTabletDriver.UX/App.cs
> +            Version = $"v{Version}, Built on {BuildDate}",
> This should be moved out to another entry in diagnostics, and removed from UX.

You're right, as we've added the git hash to the version we don't really need to have the build date in the UX, just the exported diag. I'll do that.

2021-11-28 15:39 UTC, X9VoiD approved these changes

2021-11-30 00:56 UTC, gonX requested changes
Just that one thing in `build.sh` then it's okay.

2021-11-30 00:56 UTC, gonX commented on build.sh
> +/p:SuppressNETCoreSdkPreviewMessage=true /p:PublishTrimmed=false --runtime=$runtime -p:SourceRevisionId=$(git rev-parse --short HEAD))
```suggestion
    /p:SuppressNETCoreSdkPreviewMessage=true /p:PublishTrimmed=false --runtime=$runtime -p:SourceRevisionId=$(git rev-parse --short HEAD))
```
It's more obvious its continuing last line this way.

2021-11-30 00:56 UTC, gonX commented on OpenTabletDriver.UX/App.cs
> -
Does this try to accommodate some sort of styling preference we have or is this a mistake?

2021-11-30 05:08 UTC, Sublimelime commented on OpenTabletDriver.UX/App.cs
> -
It was a mistake, likely caused by the several failed commits that I squashed. I'll undo the changes to App.cs with the commit that fixes the indentation in build.sh, one moment....

2021-11-30 11:36 UTC, gonX approved these changes

2021-12-24 16:22 UTC, InfinityGhost approved these changes

2021-12-24 16:31 UTC, merged