Update configurations and parsers
OpenTabletDriver/OpenTabletDriver pull request #1679
Opened 2021-11-29 20:11 UTC by X9VoiD

2021-11-29 20:43 UTC, gonX approved these changes

2021-11-29 20:43 UTC, gonX commented on OpenTabletDriver.Configurations/Configurations/Parblo/A610 Pro.json
> +      "FeatureInitReport": null,
```suggestion
      "FeatureInitReport": null,
```
cosmetic

2021-11-29 20:43 UTC, gonX commented on OpenTabletDriver.Configurations/Parsers/Genius/GeniusTabletReport.cs
> +                    report[5].IsBitSet(4)
```suggestion
               report[5].IsBitSet(3),
               report[5].IsBitSet(4)
```
one tab too much, might want to just autoindent this file

2021-11-29 20:54 UTC, gonX approved these changes

2021-12-03 18:36 UTC, InfinityGhost requested changes
Formatting is wrong in the following configurations:
- Acepen AP 1060
- Gaomon M10K
- Genius G-Pen 560
- Genius i608x
- Huion 420
- Huion HS64
- Huion Kamvas 16
- Parblo A610
- Wacom ET-0405-U
- XP-Pen Deco 03
- XP-Pen Innovator 16
- XP-Pen Star 03
- XP-Pen Star G430

After required changes are applied, the entire configuration list should be run through the configuration editor to enforce formatting.

2021-12-03 18:36 UTC, InfinityGhost commented on OpenTabletDriver.Configurations/Configurations/ViewSonic/WoodPad PF0730.json
> +  "Name": "Woodpad PF0730",
```suggestion
  "Name": "ViewSonic Woodpad PF0730",
```

2021-12-03 18:36 UTC, InfinityGhost commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist 22HD.json
> +  "Name": "Xp-Pen Artist 22HD",
```suggestion
  "Name": "XP-Pen Artist 22HD",
```

2021-12-03 18:36 UTC, InfinityGhost commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Deco mini 4.json
> +  "Name": "XP-Pen Deco Mini 4",
Filename does not match name property

2021-12-05 00:10 UTC, X9VoiD commented
Should get CI or console lint.

2021-12-05 03:55 UTC, InfinityGhost commented
> Should get CI or console lint.

Transferring this to an issue

2021-12-06 06:31 UTC, gonX commented
Closes #1448 when merged, since b74dbce3 was added

2021-12-06 20:25 UTC, gonX commented
Will also close #1101 because of f111a2a5858

2021-12-06 20:46 UTC, gonX commented
..and #1282 because of e4a08ee856d2

2021-12-08 00:54 UTC, gonX commented
Some more for the list:

Closes #1545 because of 6c75c3512a
Closes #1338 because of 4bbddbc
Closes #1435 because of 6112c53
Closes #1500 because of ffea0c1

2021-12-13 01:49 UTC, gonX commented
Now also closes #1401 because of 5184d421631

2021-12-13 06:03 UTC, InfinityGhost requested changes

2021-12-13 06:03 UTC, InfinityGhost commented on OpenTabletDriver.Configurations/ReportParserProvider.cs
> +namespace OpenTabletDriver.ComponentProviders
This file is left over, or hasn't been moved to the correct path.

2021-12-13 06:41 UTC, InfinityGhost approved these changes

2021-12-13 06:41 UTC, merged