Presets to be able to quickly switch between configs
OpenTabletDriver/OpenTabletDriver pull request #1715
Opened 2021-12-10 22:34 UTC by vedattt

Hey, this PR is a feature request.
## Why?
I've become increasingly irritated with how many steps there are to switch between existing json settings files, considering that I have to switch _very_ frequently to suit what I'm using my tablet for at the time. Every time you need to switch to some other settings file you have saved, you need at least 6 clicks in different menus. This pull request reduces this amount down to two clicks, namely, one right click on the tray icon, and one final left click to switch to a _preset_.

## How?
I tried to implement the feature as similarly as I could to the existing code base, and I mirrored quite a few things from how plugins are managed and how settings are loaded. I also tried my best not to be too intrusive by modifying existing classes just for this feature, if that makes a difference.

The feature works by scanning a Presets folder under the program data directory, and loading any valid settings json file into the PresetManager. These presets are listed in the tray icon context menu, to allow very quick and hassle-free switching. There is also one additional item under the File menu on the main window, to refresh the presets by loading from the folder again.

Any user should be able to drop a nicely configured json file into the presets folder and thereafter be able to switch between use cases quickly. If the user has no need for presets and does not use the folder, the feature shouldn't affect them in any way I can see.

There may be some issues like the new settings format migration being overlooked, or the length of preset file names, or the amount of preset files within the folder, and so on. But these should be easy enough to fix, possibly with the exception of v6 migration?

(Disclaimer; I have no real previous experience with C# or .NET or Eto.Forms, so do beware. Though I think I've managed to get around most potential issues just by looking at the existing code?)

2021-12-10 22:46 UTC, jamesbt365 commented
Does this take into account all platforms of otd including Linux and macos?

2021-12-10 22:54 UTC, vedattt commented
> Does this take into account all platforms of otd including Linux and macos?
Though I considered this while working on it, I'll be honest, I did nothing special to make certain it works on non-Windows.
My wishful thinking was that since what is happening underneath is pretty simple, it should be fine. I don't think there should be incompatibilities as long as tray icons and the app folder work similarly on other platforms?

2021-12-10 22:55 UTC, jamesbt365 commented
As fair as i know there is no tray icons for the other platforms.

2021-12-10 22:58 UTC, jamesbt365 commented
In reality this needs a new tab in the UX, with console support and a bunch of other stuff that doesn't make this a small addition

2021-12-10 23:09 UTC, vedattt commented
If tray icons are exclusive to Windows, the addition there shouldn't pose a problem but there may be a need to look for some other place to tuck the presets? Since I'm not exactly familiar with the workflow on those platforms, I'm not sure what the best way to go about it would be.

Does it really need its own tab though? It's just an integrated way to load settings from a folder. It doesn't add any new methods to work with the presets, it uses what already exists (like SetSettings in DriverDaemon). Isn't the different tablet issue identical to loading other settings through the file dialog? I think all this addition really does is to store specific settings files on the UI instead of loading them through the file picker every time, the inner workings should be the same.

As for the console support, I'm not familiar with that part of the project so I can't say much.

2021-12-10 23:37 UTC, vedattt commented
https://github.com/OpenTabletDriver/OpenTabletDriver/blob/4b9e63f58ba5c1a271daa995acdf51eb2fb623de/OpenTabletDriver.UX/App.cs#L96
Looks like tray icons are exclusively non-Linux. I don't think this feature, as it is, is incompatible with macOS in that case. As for Linux, either the feature would be hidden away, or somewhere practical to place presets would need to be found.

2021-12-10 23:38 UTC, jamesbt365 commented
This is why this should be integrated into its own tab in the UX with proper functionality.

2021-12-10 23:45 UTC, vedattt commented
Yeah, I agree that it would be best across all platforms to make it into its own tab or at least a simple `MenuBar`. But at the same time, it would somewhat defeat the practicality this has on Windows and macOS. It's hard to beat simply right clicking the tray icon.

I would propose to keep the tray icon, but move the same menu over to the `MenuBar` on Linux. Just a thought.

2021-12-11 00:04 UTC, X9VoiD requested changes
Add presets to the File menu, not in a tab as initially proposed by James.

Preferably with this structure:
```
File menu
... schtuff
- Refresh presets
- Presets
  - a preset
  - another preset
  - i like this third preset
... schtuff
```

Other than that, code looks good.

2021-12-11 01:35 UTC, vedattt commented on OpenTabletDriver.UX/Controls/Generic/ScheduledDrawable.cs
> +                if (base.ParentWindow == null || base.ParentWindow.WindowState == WindowState.Minimized)
This one is only a problem when the trayicon interacts with the mainform while it is minimized.
May not be necessary if we're going the File menu route, but I can PR it later anyway.

2021-12-11 01:40 UTC, vedattt commented
@X9VoiD Does this last commit look good?
![image](https://user-images.githubusercontent.com/12011884/145659372-c82990ce-d74c-4595-a44a-a9fc06c7a59c.png)

~~P.S. I still think tray icons are super practical but I guess I won't go against the cross-platform unity of the project here :p.~~

2021-12-11 01:54 UTC, Sublimelime commented
>P.S. I still think tray icons are super practical but I guess I won't go against the cross-platform unity of the project here :p.

They are - on windows (mac too?). However many linux distros have desktop environments that don't have trays to hold tray icons (i3 for example), so things either break or the functionality isn't available. Any solution has to work for all platforms, and have "don't do this on X platform" conditionals as a last resort (and usually with a "do this instead" clause).

2021-12-11 01:55 UTC, X9VoiD commented
> @X9VoiD Does this last commit look good? 

You don't have to move it over, having both is fine.

2021-12-11 01:56 UTC, X9VoiD commented on OpenTabletDriver.UX/Controls/Generic/ScheduledDrawable.cs
> +                if (base.ParentWindow == null || base.ParentWindow.WindowState == WindowState.Minimized)
I see, should be fine here then.

2021-12-11 02:14 UTC, vedattt commented
I think this last commit is the best of both worlds. All platforms have the menu under File, but non-Linux also have it on the tray icon. No tedious conditional OS checks either, only one to see if tray icon is null (Linux).

2021-12-11 02:30 UTC, X9VoiD approved these changes

2021-12-12 19:39 UTC, InfinityGhost requested changes
lg2m, some minor changes though

2021-12-12 19:39 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/PresetManager.cs
> +        }
Extract class, nested public classes are annoying to reference.

2021-12-12 19:39 UTC, InfinityGhost commented on OpenTabletDriver.UX/MainForm.cs
> +            var presets = AppInfo.PresetManager.GetPresets();
```suggestion
            // Update File submenu
            var presets = AppInfo.PresetManager.GetPresets();
```

2021-12-13 07:40 UTC, gonX reviewed
Looks okay at a quick glance. Can someone with write perms authorize an action build so non-devs can test?

2021-12-13 16:44 UTC, InfinityGhost approved these changes
lg2m

2021-12-13 17:04 UTC, vedattt commented
Rebased #1716 onto this PR as per @gonX's suggestion.
Relevant commits:
- c812d066002c8e5f5b49f17beaf5273167ea40ba
- 7c7226393aebf319225caf379b957ff18bf9064c
- 6d48ea087687dd643a27414987977a3024397ccd

2021-12-13 17:06 UTC, InfinityGhost approved these changes

2021-12-13 17:49 UTC, X9VoiD approved these changes

2021-12-13 20:01 UTC, merged

2021-12-16 05:18 UTC, AkiSakurai commented
I think you should add a command to save preset.
It is not clear where to save the preset with "Save settings as".

2021-12-16 05:44 UTC, InfinityGhost commented
> I think you should add a command to save preset. It is not clear where to save the preset with "Save settings as".

Create an issue with this