PluginManager: Force Configurations and Native assemblies to be loaded
OpenTabletDriver/OpenTabletDriver pull request #1739
Opened 2021-12-15 21:53 UTC by InfinityGhost

Patch fix for loading required assembly for plugins

- Closes #1730
- Closes #1732

2021-12-15 22:50 UTC, gonX commented
Brief check on what best practices are to force assemblies to load seems to give the same type of approach. I don't mind it either as long as its adequately commented.

Will test later.

2021-12-16 05:49 UTC, X9VoiD commented
If this is working then this will suffice for now. We should create a backlog issue for investigating why exactly the issue happens after this one is merged.

2021-12-16 06:21 UTC, InfinityGhost commented
Doesn't actually appear to work as intended, drafting for now.

2021-12-16 06:31 UTC, X9VoiD requested changes
On another thought, we should just load the internal types from assemblies that we need to speed up the reflection and finally fix the annoying false positive plugin error on Eto.WPF.

2021-12-16 19:19 UTC, InfinityGhost commented
> On another thought, we should just load the internal types from assemblies that we need to speed up the reflection and finally fix the annoying false positive plugin error on Eto.WPF.

If we can find a cleaner way to do it, we can go that route. I don't like the method I'm currently using to hotfix this issue, so that would be great.

2021-12-16 19:30 UTC, X9VoiD commented
#1743

2021-12-17 21:26 UTC, merged