Switch to manually adding/removing tabs instead of TabPage.Visible
OpenTabletDriver/OpenTabletDriver pull request #1750
Opened 2021-12-16 15:06 UTC by vedattt

## Changes

- Stopped relying on `TabPage.Visible` entirely in `ControlForm.cs`. All tab pages are constructed into a dictionary, and are added onto the `TabControl` depending on the changing conditions.
- Used a dictionary instead of a list so that the code remains both readable and safe. Safe as in, every dictionary element has the tab label as its key, and every element's `TabPage.Text` property is consequently set to the key value.
- Tab labels are contained a private nested class `TabLabels` which is the only place where labels can be changed.

## Issues

- Closes #1723

2021-12-16 15:15 UTC, X9VoiD requested changes
Seems fine.

But it's probably safer and cleaner to introduce a new class that holds all of the tabs so that the "keys" are enforced via type information instead of strings.

```cs
internal class TabPageStore : IEnumerable<IForgotTheInterfaceOfTabPages>
{
    // Put the nullable tab pages here.
    // Then use yield return to enumerate the non-null contents of the store in order.
    // If Clear() is really needed then...
    public void Clear()
    {
        // Set pages to null to disable
    }
}
```

2021-12-16 16:38 UTC, vedattt commented
Hmm, I'm having some trouble understanding the change here, let me try to tell you what I think I understood. 

`TabPageStore` would basically be `tabPages` but moved into its own class, and it would be a direct substitute for `TabControl.Pages`. Instead of controlling what gets added into `TabControl.Pages`, we would control tabs by setting them to null in `TabPageStore`, which would effectively hide them away from any iterators. 

So for example, we point `tabControl.Pages` to an instance of `TabPageStore`, and if the profile change event is triggered, we use some method in `TabPageStore` to `null`ify its tab elements that are not needed.

Assuming my understanding is correct, I have a question though:
I thought since `TabControl.Pages` is readonly, there wouldn't be a way to directly set `TabPageStore` as its actual page store.
As a workaround, maybe iterate its contents into a cleared `tabControl.Pages` upon every change, would that be a good idea?

2021-12-16 18:27 UTC, vedattt commented
Okay, after trying my hand at a `TabPageStore` implementation, I realized I was just doing the dictionary stuff from within another class and wasn't really getting anywhere. I took a step back and realized this was way overkill from the very beginning, so I rebased the entire PR from scratch.

2021-12-16 18:30 UTC, X9VoiD approved these changes

2021-12-16 18:35 UTC, Sublimelime commented
I like this, pretty clean. Haven't seen `new()` before like that, guessing it just creates a new instance of whatever's on the left like `var` does for what's on the right?

2021-12-16 18:36 UTC, vedattt commented
> Haven't seen `new()` before like that, guessing it just creates a new instance of whatever's on the left like `var` does for what's on the right?

Yep;
![image](https://user-images.githubusercontent.com/12011884/146429115-67dd2367-cbdd-4027-b3a7-43f7416c5efc.png)

2021-12-23 05:20 UTC, InfinityGhost approved these changes

2021-12-23 05:20 UTC, merged