Fix `detect tablet` not disposing outdated pipelines
OpenTabletDriver/OpenTabletDriver pull request #1751
Opened 2021-12-16 20:01 UTC by vedattt

Seems to work on my end, #1745 is no longer reproducible after following the steps in the video.
Haven't noticed any other side effects.

## Changes

- Add a call to `Dispose` during tablet detection in `Driver`.
- Modify `Dispose` to use `List`s since .NET doesn't allow modifications during enumeration.

## Issues
- Closes #1745

2021-12-16 20:05 UTC, InfinityGhost requested changes

2021-12-16 20:05 UTC, InfinityGhost commented on OpenTabletDriver/Driver.cs
> +            Dispose();
While this is a fix, I don't think this is the right way to go about things. We should probably create a class for `InputDevices` based on a list that disposes all of them on `Clear()` rather than disposing the Driver class itself.

2021-12-16 20:56 UTC, vedattt commented
> We should probably create a class for InputDevices based on a list that disposes all of them on Clear() rather than disposing the Driver class itself.

Was this (3dd3f0e51b11b415151de7378267f96a2a1baec9) what you had in mind?

2021-12-17 12:52 UTC, vedattt commented
Oops, made a mistake with the list implementation, will adjust according to this: [Collection.Clear - Notes to inheritors](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.collection-1.clear?view=net-6.0#notes-to-inheritors)

2021-12-17 21:27 UTC, InfinityGhost approved these changes

2021-12-17 21:27 UTC, merged