Added German readme.
OpenTabletDriver/OpenTabletDriver pull request #1777
Opened 2021-12-21 19:03 UTC by OniCado

2021-12-21 19:34 UTC, jamesbt365 commented on README_DE.md
> +#### MacOS [Experimental]
Does experimental translate?

2021-12-21 19:34 UTC, jamesbt365 commented on README_DE.md
> +- [Supported Tablets](https://opentabletdriver.net/Tablets)
You missed a translation here.

2022-01-22 14:45 UTC, C0D3-M4513R requested changes
The German has a few spelling mistakes, and a few sentences, that are not really good German.
I commented, what I could find.

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +OpenTabletDriver ist ein open source, platformübergreifender, Benutzermodus Tablet Driver. Das Ziel von OpenTabletDriver ist es so cross platform wie möglich zu sein mit der höchsten Kompatibilität u
Driver=>Treiber,Cross-Platform
grafsichen=>grafischen
`und einer einfach konfigurierbaren grafsichen Benutzeroberfläche.` is a little unclean wording.  maybe say instead
'und mit einer einfach zu konfigurierenden grafischen Benutzeroberfläche.'

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +Der Status aller unterstützten, ungestesteten und zur Ünterstützung geplanten Tablets kann hier eingesehen werden. Häufige Fehler und deren Lösungen sind auf den wikis der jeweiligen Platform zu find
wikis=>Wikis

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +OpenTabletDriver arbeitet als zwei unabhängige Prozesse, welche nahtlos miteinender interagieren. Der aktive Prozess `OpenTabletDriver.Daemon` geht mit allen Tabetdaten um, während `OpenTabletDriver.
'OpenTabletDriver arbeitet als zwei unabhängige Prozesse'
is not good German. I would suggest something like this:
'OpenTabletDriver besteht aus zwei unabhängigen Prozessen'

'während `OpenTabletDriver.UX.*` das die grafische Benutzeroberfläche ist' => 'während der `OpenTabletDriver.UX.*` Prozess die grafische Benutzeroberfläche darstellt'

Der daemon=>Der Daemon
der daemon=>der Daemon

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +- .NET 6 SDK (kann [hier](https://dotnet.microsoft.com/download/dotnet/6.0) heruntergeladen werden - Die SDK für die jeweilige Platform wird benötigt, Linuxnutzer sollten die SDK nach möglichkeit mit
not certain on this one, but still suggesting this
package manager => Package-Manager

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +Benötigte packages (manche packages können bei Ihrer Distribution vorinstalliert sein)
packages=>Packages

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +und ausführbare Dateien werden in 'OpenTabletDriver/bin' erstellt.
unclear. Change this, to more closely reflect the english readme.

Es werden die gleichen 'dotnet publish' Befehle ausgefürt, die auch für das AUR-Package verwendet werden. Die ausführbare Dateien werden dann in dem 'OpenTabletDriver/bin'  Ordner erstellt.

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +  - Schnelles ändern, laden und speichern von Einstellungen
ansehen=aquire

Schnelles ansehen, ändern, laden und speichern con Einstellungen

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +  - Autoladen von Benutzereinstellungen aus `settings.json` in den momentan aktiven Benutzer `%localappdata%` oder `.config` für das Root-Verzeichnis.
oder `.config` für das Root-Verzeichnis => oder '.config' im Root-Verzeichnís

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +# zu OpenTabletDriver beitragen
zu=>Zu

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +Wenn Sie zu OpenTabletDriver beitragen wollen, besuchen Sie den [issue
Translation for issue tracker?

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +ein pull request erstellen wollen, folgen Sie den Richtlinien unter [Beitragsrichtlinien](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/CONTRIBUTING.md).
Is there a translation for pull request? - idk myself

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +Wenn Sie Probleme oder Vorschläge haben, [Erstellen Sie ein issue
Translation for issue ticket?

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +Fällen ist er relativ einfach, neue Tablets zu unterstützen.
er=>es

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +### neue Tablets unterstützen
neue=>Neue

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +und füllen Sie die Vorlage mit relevanten Informationen aus. Bug reports sowie
Better German wording for 'Bug reports'?

2022-01-22 14:45 UTC, C0D3-M4513R commented on README_DE.md
> +Sie können auch gerne ein pull request erstellen und Überstützung selbst hinzufügen,
Translation for pull request again

2022-01-22 14:50 UTC, OniCado commented on README_DE.md
> +### neue Tablets unterstützen
Tablets is the noun, not neue

2022-01-22 14:58 UTC, C0D3-M4513R commented on README_DE.md
> +### neue Tablets unterstützen
> from OniCado
> Tablets is the noun, not neue

true, but neue is at the start of a sentence. Sentence beginnings are always capitalised

2022-01-26 14:11 UTC, OniCado commented on README_DE.md
> +### neue Tablets unterstützen
> > from OniCado
> > Tablets is the noun, not neue
> 
> true, but neue is at the start of a sentence. Sentence beginnings are always capitalised

it is not the beginning of a sentence either, but due to the new line it might seem like that at first, the sentence starts w/ 'Bug reports' as far as i can see.

2022-01-26 14:29 UTC, C0D3-M4513R commented on README_DE.md
> +### neue Tablets unterstützen
Oh, I meant neue on line 119. Not neue on line 116 or 117.

2022-01-26 14:31 UTC, OniCado commented on README_DE.md
> +### neue Tablets unterstützen
so treat headlines as sentences and capitalize their beginning? got it ty

2022-01-26 15:00 UTC, C0D3-M4513R commented
The Fix for linux compilation instructions still needs to happen, as well as the two fixes in the Feature section. Otherwise no issues.

2022-01-27 15:23 UTC, Sublimelime commented on README_DE.md
> +OpenTabletDriver besteht aus zwei unabhängigen Prozessen, welche nahtlos miteinender interagieren. Der aktive Prozess `OpenTabletDriver.Daemon` geht mit allen Tabetdaten um, während der 'OpenTabletDr
```suggestion
OpenTabletDriver besteht aus zwei unabhängigen Prozessen, welche nahtlos miteinender interagieren. Der aktive Prozess `OpenTabletDriver.Daemon` geht mit allen Tabetdaten um, während der `OpenTabletDriver.UX.*` Prozess die grafische Benutzeroberfläche darstellt, wobei `*` platformabhängig ist <sup>1</sup>. Der Daemon muss laufen, damit OpenTabletDriver funktioniert, die Benutzeroberfläche allerdings nicht. Bestehende Einstellungen werden angewendet, wenn der Daemon startet.
```

Backticks, not apostrophes, should be used for code or similar (the english readme already has this, potentially a mistake from the act of translating) - otherwise the markdown interpreter interprets the asterisks as italic text markdown.

2022-03-19 16:43 UTC, C0D3-M4513R requested changes
There are still some issues. Overall though, this is close, to being good.

2022-03-19 16:43 UTC, C0D3-M4513R commented on README_DE.md
> +und ausführbare Dateien werden in 'OpenTabletDriver/bin' erstellt.
The `wie` here is still bad German. The sentence above is an example, of how I'd phrase it.
It can be understood, but it is not very clear.

2022-03-19 16:43 UTC, C0D3-M4513R commented on README_DE.md
> +  - Autoladen von Benutzereinstellungen aus `settings.json` in den momentan aktiven Benutzer `%localappdata%` oder `.config` für das Root-Verzeichnis.
This still.

2022-03-19 16:43 UTC, C0D3-M4513R commented on README_DE.md
> +  - Schnelles ändern, laden und speichern von Einstellungen
I'm pedantic, sorry. This is technically also in the english doc. This is not blocking the merge of this pr imo tho.

2022-03-19 18:00 UTC, C0D3-M4513R approved these changes

2022-03-25 19:38 UTC, merged