Added 10moon 1060 Configurations
OpenTabletDriver/OpenTabletDriver pull request #1819
Opened 2021-12-28 19:46 UTC by Mrcubix

# Verification:

anything before https://discord.com/channels/615607687467761684/922220574531534848/922948452139298866

# Changes

- Add TenMoonReportParser
- Add 10moon 1060 Configurations

# Note

- Doesn't meet any of the advertised specs (Only 6.52 lines per mm instead of the advertised 200 for example)
- Require multiple Feature Init
- An offset is required for pressure on aux press
- Cannot press multiple keys at the same time due to the fact bits get overwritten once a new aux key is pressed
(leading me to using bytes instead of checking for bits)

2022-01-02 17:02 UTC, gonX reviewed
Is it our init that makes it go 4096x4096? Or does the official driver on Win Ink result in similar accuracy?

2022-01-02 17:02 UTC, gonX commented on TABLETS.md
> +| 10moon 1060                   |     Supported     | Doesn't meet any of it's advertised specs
Grammar:
```suggestion
| 10moon 1060                   |     Supported     | Doesn't meet any of its advertised specs
```

Though, I'd prefer the comment to be reworded instead

2022-01-04 17:44 UTC, X9VoiD requested changes

2022-01-04 17:44 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Parsers/10moon/10moonAuxParser.cs
> +
```suggestion
```

2022-01-04 17:49 UTC, X9VoiD requested changes

2022-01-04 17:49 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/10moon/1060N.json
> +  "Name": "10moon 1060N",
1060N or 1060? Update `TABLETS.md` if this is 1060N.

2022-01-04 18:01 UTC, merged