Notify user on daemon startup when vanguard is running
OpenTabletDriver/OpenTabletDriver pull request #1820
Opened 2021-12-28 21:36 UTC by Sublimelime

Small PR to add a warning notification when the daemon starts, if vanguard (valorant's anti cheat) is found to be running. It's fairly common for this to cause issues even when the user isn't actually playing valorant - this might allow a struggling user to self-troubleshoot, or give us a head's up in diagnostics.

Opened as draft as I can't personally test this (don't have valorant installed as I don't play it, not sure if I have the process name right), will open fully once someone can confirm it works.

2021-12-28 23:16 UTC, X9VoiD approved these changes

2021-12-28 23:18 UTC, Sublimelime commented
If anyone's got valorant installed and can check that this works (code should be fine but need to know if I got the process name right), I'd appreciate it.

2022-01-02 16:55 UTC, gonX commented
Not sure if its just me but marking it as draft makes me think it's not ready on your end, rather than it needs testing.

2022-01-02 20:36 UTC, Sublimelime commented
You're right, it does say "ready for review" when you click the button, and a review is exactly what it needs. Fixed.

2022-03-28 12:00 UTC, C0D3-M4513R commented
I just tested this pr, as I do have valorant installed. (I just had to start vanguard manually).
Detecting Vanguard worked. 
For sanity I also checked without having vanguard open.
However after detecting a tablet, the driver crashes:
```
[Detect:Warning]        Another tablet driver found: Wacom
[IOException:Error]     Cannot create a file when that file already exists.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileInfo.MoveTo(String destFileName, Boolean overwrite)
   at OpenTabletDriver.Desktop.Reflection.DesktopPluginManager.Clean() in C:\Users\XXX\Downloads\OpenTabletDriver\OpenTabletDriver.Desktop\Reflection\DesktopPluginManager.cs:line 54
[Plugin:Debug]  Loading plugin 'Kuuube's_CHATTER_EXTERMINATOR'
[Plugin:Debug]  Loading plugin 'OemKill'
[Plugin:Debug]  Loading plugin 'RadialFollow'
[Detect:Info]   Searching for tablets...
[Detect:Debug]  Searching for tablet 'Acepen AP 1060'
[Detect:Debug]  Searching for tablet 'Artisul M0610 Pro'
[Detect:Debug]  Searching for tablet 'Gaomon 1060 Pro'
[Detect:Debug]  Searching for tablet 'Gaomon M106K Pro'
[Detect:Debug]  Searching for tablet 'Gaomon M106K'
[Detect:Debug]  Searching for tablet 'Gaomon M10K Pro'
[Detect:Debug]  Searching for tablet 'Gaomon M10K'
[Detect:Debug]  Searching for tablet 'Gaomon M1220'
[Detect:Debug]  Searching for tablet 'Gaomon PD1161'
[Detect:Debug]  Searching for tablet 'Gaomon PD1560'
[Detect:Debug]  Searching for tablet 'Gaomon S56K'
[Detect:Debug]  Searching for tablet 'Gaomon S620'
[Detect:Debug]  Searching for tablet 'Gaomon S630'
[Detect:Debug]  Searching for tablet 'Genius G-Pen 560'
[Detect:Debug]  Searching for tablet 'Genius i608x'
[Detect:Debug]  Searching for tablet 'Huion 1060 Plus'
[Detect:Debug]  Searching for tablet 'Huion 420'
[Detect:Debug]  Searching for tablet 'Huion G10T'
[Detect:Debug]  Searching for tablet 'Huion GC610'
[Detect:Debug]  Searching for tablet 'Huion H1060P'
[Detect:Debug]  Searching for tablet 'Huion H1161'
[Detect:Debug]  Searching for tablet 'Huion H420X'
[Detect:Debug]  Searching for tablet 'Huion H430P'
[Detect:Debug]  Searching for tablet 'Huion H610 Pro V2'
[Detect:Debug]  Searching for tablet 'Huion H610 Pro'
[Detect:Debug]  Searching for tablet 'Huion H640P'
[Detect:Debug]  Searching for tablet 'Huion H950P'
[Detect:Debug]  Searching for tablet 'Huion HC16'
[Detect:Debug]  Searching for tablet 'Huion HS610'
[Detect:Debug]  Searching for tablet 'Huion HS611'
[Detect:Debug]  Searching for tablet 'Huion HS64'
[Detect:Debug]  Searching for tablet 'Huion Kamvas 13'
[Detect:Debug]  Searching for tablet 'Huion Kamvas 16'
[Detect:Debug]  Searching for tablet 'Huion Kamvas 22 Plus'
[Detect:Debug]  Searching for tablet 'Huion Kamvas Pro 13'
[Detect:Debug]  Searching for tablet 'Huion Kamvas Pro 16'
[Detect:Debug]  Searching for tablet 'Huion Kamvas Pro 20'
[Detect:Debug]  Searching for tablet 'Huion New 1060 Plus (2048)'
[Detect:Debug]  Searching for tablet 'Huion New 1060 Plus'
[Detect:Debug]  Searching for tablet 'Huion osu!tablet'
[Detect:Debug]  Searching for tablet 'Huion Q11K V2'
[Detect:Debug]  Searching for tablet 'Huion Q11K'
[Detect:Debug]  Searching for tablet 'Huion Q620M'
[Detect:Debug]  Searching for tablet 'Huion WH1409 V2'
[Detect:Debug]  Searching for tablet 'Huion WH1409'
[Detect:Debug]  Searching for tablet 'Parblo A610 Pro'
[Detect:Debug]  Searching for tablet 'Parblo Intangbo M'
[Detect:Debug]  Searching for tablet 'Parblo Intangbo S'
[Detect:Debug]  Searching for tablet 'Parblo Ninos M'
[Detect:Debug]  Searching for tablet 'Parblo Ninos S'
[Detect:Debug]  Searching for tablet 'UC-Logic 1060N'
[Detect:Debug]  Searching for tablet 'UC-Logic PF1209'
[Detect:Debug]  Searching for tablet 'UGTABLET M708'
[Detect:Debug]  Searching for tablet 'VEIKK A15 Pro'
[Detect:Debug]  Searching for tablet 'VEIKK A15'
[Detect:Debug]  Searching for tablet 'VEIKK A30'
[Detect:Debug]  Searching for tablet 'VEIKK A50'
[Detect:Debug]  Searching for tablet 'VEIKK S640 V2'
[Detect:Debug]  Searching for tablet 'VEIKK S640'
[Detect:Debug]  Searching for tablet 'VEIKK VK640'
[Detect:Debug]  Searching for tablet 'ViewSonic Woodpad PF0730'
[Detect:Debug]  Searching for tablet 'Wacom CTE-430'
[Detect:Debug]  Searching for tablet 'Wacom CTE-440'
[Detect:Debug]  Searching for tablet 'Wacom CTE-450'
[Detect:Debug]  Searching for tablet 'Wacom CTE-460'
[Detect:Debug]  Searching for tablet 'Wacom CTE-630'
[Detect:Debug]  Searching for tablet 'Wacom CTE-640'
[Detect:Debug]  Searching for tablet 'Wacom CTE-650'
[Detect:Debug]  Searching for tablet 'Wacom CTF-430'
[Detect:Debug]  Searching for tablet 'Wacom CTH-460'
[Detect:Debug]  Searching for tablet 'Wacom CTH-461'
[Detect:Debug]  Searching for tablet 'Wacom CTH-470'
[Detect:Debug]  Searching for tablet 'Wacom CTH-480'
[Detect:Debug]  Searching for tablet 'Wacom CTH-490'
[Detect:Debug]  Searching for tablet 'Wacom CTH-661'
[Detect:Debug]  Searching for tablet 'Wacom CTH-670'
[Detect:Debug]  Searching for tablet 'Wacom CTH-680'
[Detect:Debug]  Searching for tablet 'Wacom CTH-690'
[Detect:Debug]  Searching for tablet 'Wacom CTL-4100'
[Detect:Debug]  Searching for tablet 'Wacom CTL-4100WL'
[Detect:Debug]  Searching for tablet 'Wacom CTL-460'
[Detect:Debug]  Searching for tablet 'Wacom CTL-470'
[Detect:Debug]  Searching for tablet 'Wacom CTL-471'
[Detect:Debug]  Searching for tablet 'Wacom CTL-472'
[Detect:Debug]  Searching for tablet 'Wacom CTL-480'
[Detect:Debug]  Searching for tablet 'Wacom CTL-490'
[Detect:Debug]  Searching for tablet 'Wacom CTL-6100WL'
[Detect:Debug]  Searching for tablet 'Wacom CTL-671'
[Detect:Debug]  Searching for tablet 'Wacom CTL-672'
[Detect:Debug]  Searching for tablet 'Wacom CTL-680'
[Detect:Debug]  Searching for tablet 'Wacom CTL-690'
[Detect:Debug]  Searching for tablet 'Wacom ET-0405-U'
[Detect:Debug]  Searching for tablet 'Wacom ET-0405A-U'
[Detect:Debug]  Searching for tablet 'Wacom FT-0405-U'
[Detect:Debug]  Searching for tablet 'Wacom GD-0405-U'
[Detect:Debug]  Searching for tablet 'Wacom GD-0608-U'
[Detect:Debug]  Searching for tablet 'Wacom GD-0912-U'
[Detect:Debug]  Searching for tablet 'Wacom GD-1212-U'
[Detect:Debug]  Searching for tablet 'Wacom GD-1218-U'
[Detect:Debug]  Searching for tablet 'Wacom MTE-450'
[Detect:Debug]  Searching for tablet 'Wacom PTH-450'
[Detect:Debug]  Searching for tablet 'Wacom PTH-451'
[Detect:Debug]  Searching for tablet 'Wacom PTH-460'
[Detect:Debug]  Searching for tablet 'Wacom PTH-650'
[Detect:Debug]  Searching for tablet 'Wacom PTH-651'
[Detect:Debug]  Searching for tablet 'Wacom PTH-660'
[Detect:Debug]  Searching for tablet 'Wacom PTH-850'
[Detect:Debug]  Searching for tablet 'Wacom PTH-851'
[Detect:Debug]  Searching for tablet 'Wacom PTH-860'
[Detect:Debug]  Searching for tablet 'Wacom PTK-1240'
[Detect:Debug]  Searching for tablet 'Wacom PTK-440'
[Detect:Debug]  Searching for tablet 'Wacom PTK-450'
[Detect:Debug]  Searching for tablet 'Wacom PTK-540WL'
[Detect:Debug]  Searching for tablet 'Wacom PTK-640'
[Detect:Debug]  Searching for tablet 'Wacom PTK-650'
[Detect:Debug]  Searching for tablet 'Wacom PTK-840'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-1230'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-1231W'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-430'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-431W'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-630'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-631W'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-930'
[Detect:Debug]  Searching for tablet 'Wacom XD-0405-U'
[Detect:Debug]  Searching for tablet 'Wacom XD-0608-U'
[Detect:Debug]  Searching for tablet 'Wacom XD-0912-U'
[Detect:Debug]  Searching for tablet 'Wacom XD-1212-U'
[Detect:Debug]  Searching for tablet 'Wacom XD-1218-U'
[Detect:Debug]  Searching for tablet 'XenceLabs Pen Tablet Medium'
[Detect:Debug]  Searching for tablet 'XP-Pen Artist 12 Pro'
[Detect:Debug]  Searching for tablet 'XP-Pen Artist 12'
[Detect:Debug]  Searching for tablet [...]

2022-03-28 18:01 UTC, Sublimelime commented
If it detects correctly then that's great, means I got the name of the process correct. If the crash still happens without this PR then it's probably unrelated (a breakage with your setup?). 

I guess that makes this ready for merge, though I don't know if this will collide with the rewrite.

2022-03-28 18:44 UTC, InfinityGhost requested changes

2022-03-28 18:44 UTC, InfinityGhost commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +        }
Function should be moved to the bottom of the file with the other `private void` methods.

2022-03-28 18:44 UTC, InfinityGhost commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +                if (Process.GetProcessesByName("vgc").Length > 0)
Always use `.Any()` as it checks the enumerator itself providing better performance in (most) cases
```suggestion
                if (Process.GetProcessesByName("vgc").Any())
```

2022-03-28 18:44 UTC, InfinityGhost commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +            await Task.Run(CheckForProblematicProcesses);
Unnecessary to run this asynchronously

2022-03-29 15:06 UTC, C0D3-M4513R commented
@Sublimelime 
Sorry unclear wording. the pr chrashes, when trying to initialise a tablet. the commit this pr is based upon has the same issue. master works as expected though.
So likely an issue, that has already been solved.

2022-04-01 00:45 UTC, gonX commented
Removing verification label as it seems that the code works as intended

2022-04-02 15:52 UTC, Sublimelime commented
This could probably be wrapped into 0.6.1, add it to the milestone would ya?

2022-04-24 15:18 UTC, InfinityGhost approved these changes

2022-04-24 15:38 UTC, InfinityGhost approved these changes
lg2m

2022-04-24 15:39 UTC, merged