DriverDaemon.cs: Check for stdout before blindly assuming it exists
OpenTabletDriver/OpenTabletDriver pull request #1857
Opened 2022-01-03 06:42 UTC by gonX

On some systems stdout might be missing.

This handles that by submitting an empty line during the constructor and checking whether that succeeds, and then for log output not using `Console.WriteLine` if stdout is unavailable.

Fixes OpenTabletDriver#1855

2022-01-03 07:49 UTC, gonX commented
Probably worth noting that this doesn't cover if stdout closes after startup. I wonder if replacing `Console.WriteLine` with `Console.Out?.WriteLine` would fix that.

2022-01-04 20:01 UTC, InfinityGhost commented
> I wonder if replacing `Console.WriteLine` with `Console.Out?.WriteLine` would fix that.

I would suggest this in place of this setup, since it's able to check at any point if it can write to stdout.

2022-01-04 20:01 UTC, InfinityGhost requested changes
Apply discussed changes.

2022-01-04 21:00 UTC, vedattt commented
[Relevant Discord convo](https://discord.com/channels/615607687467761684/628651971267788800/928020159271170159)

`Console.Out` is never null due to its dotnet implementation, so direct nullchecks won't achieve anything.
Instead, the discussed alternative is to nullcheck the `BaseStream` of the `StreamWriter` instance, which also seems to be the preferred way from what I've seen looking around online.

2022-01-10 16:08 UTC, gonX commented
Updated to use new approach

2023-11-06 17:09 UTC, gonX commented
Closing as stale, there are probably better ways to solve the linked issue.

2023-11-06 17:09 UTC, closed without merging