Add support for XP-Pen Star 05 V3
OpenTabletDriver/OpenTabletDriver pull request #1877
Opened 2022-01-07 17:39 UTC by jamesbt365

Verification: https://canary.discord.com/channels/615607687467761684/615611007951306863/929063146155560980

2022-01-07 17:46 UTC, X9VoiD requested changes

2022-01-07 17:46 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Star 05 V3.json
> +      "OutputReportLength": null,
This config uses an output report, so this shouldn't be `null` to be on the safe side.

2022-01-10 16:08 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Star 05 V3.json
> +      "OutputReportLength": null,
should this be 8, 8?

2022-01-12 16:01 UTC, Mrcubix requested changes

2022-01-12 16:01 UTC, Mrcubix commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Star 05 V3.json
> +      "OutputReportLength": null,
```suggestion
      "OutputReportLength": 8,
```

2022-01-12 21:32 UTC, Mrcubix approved these changes

2022-01-13 13:49 UTC, merged