Add support for XP-Pen Dco 01 V2 V2
OpenTabletDriver/OpenTabletDriver pull request #1936
Opened 2022-01-13 21:52 UTC by jamesbt365

Verification: https://discord.com/channels/615607687467761684/930837536585187360/930961622250434601

This tablet is a V2 V2 due to XP-Pen calling this tablet a V2 and this is a variant of this, so therefore this is a V2 V2, however their may be a better way of naming this, but i'm following previous variants that have been added.

2022-01-14 03:27 UTC, InfinityGhost commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Deco 01 V2 V2.json
> +  "Name": "XP-Pen Deco 01 V2 V2",
I really don't know how to feel about this name, might be better to call it something like `XP-Pen Deco 01 V2 Rev B` or anything that could help differentiate it. Really annoying that manufacturers do this an don't update their model names.

2022-01-16 03:23 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Deco 01 V2 V2.json
> +  "Name": "XP-Pen Deco 01 V2 V2",
Should probably change scheme to `Tablet Model (variant 1)`

Since these are not guaranteed a revision, nor a version, unless specified by OEM. This scheme rolls off the tongue much better too for this tablet.

`XP-Pen Deco 01 V2 (variant 1)`
`XP-Pen Deco 01 V2 (variant 2)`

We may hide variant name from UX.

Or just integrate spec variants directly in configs. Depending on traction here we'll raise this to a new feature issue.

2022-01-16 21:08 UTC, InfinityGhost commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Deco 01 V2 V2.json
> +  "Name": "XP-Pen Deco 01 V2 V2",
For now I'm in favor of referring to it as such 
```suggestion
  "Name": "XP-Pen Deco 01 V2 (variant 2)",
```
TODO in the future to add a better system for this variant issue.

2022-01-16 21:36 UTC, InfinityGhost requested changes

2022-01-16 21:36 UTC, InfinityGhost commented on TABLETS.md
> +| XP-Pen Deco 01 V2 V2          |  Missing Features | Tilt is unsupported
Fix name

2022-01-16 21:56 UTC, InfinityGhost approved these changes

2022-01-16 21:56 UTC, merged