InputDevice: Add support for feature initialization delay
OpenTabletDriver/OpenTabletDriver pull request #1943
Opened 2022-01-14 12:30 UTC by gonX

This is one of many commits that's going to help out with #1717 - this enables the usage of the tablet configuration attribute `FeatureInitDelayMs`

This is undergoing testing and as such is marked draft for now

2022-01-16 22:53 UTC, Sublimelime commented on OpenTabletDriver/InputDevice.cs
> +                    Log.Debug("Device", $"Could not parse '{delayStr}' from attribute {DelayAttributeKeyName}");
```suggestion
                    Log.Write("Device", $"Could not parse '{delayStr}' from attribute {DelayAttributeKeyName}", LogLevel.Warning);
```

This should be Warning not Debug, as it shouldn't happen if the config is working.

2022-01-18 11:05 UTC, gonX commented
I can't find the Discord conversation right now but I seem to recall that the affected user has a functioning fix by simply waiting after initializing the string index.

That means the sleep should be done _before_ running SetFeature. This would also fix the unneeded last sleep the current version of the code does.

2022-02-07 07:10 UTC, X9VoiD requested changes
Probably also worth it to generalize the attribute instead to `InitializationDelayMs` and add the delay in all calls to GetString, SetFeature and Write within `Initialize()`.

2022-02-07 07:10 UTC, X9VoiD commented on OpenTabletDriver/InputDevice.cs
> +                        Thread.Sleep((int)FeatureInitDelayMs);
```suggestion
                    if (FeatureInitDelayMs != 0)
                        Thread.Sleep((int)FeatureInitDelayMs);
                    ReportStream.SetFeature(report);
                    Log.Debug("Device", "Set device feature: " + BitConverter.ToString(report));
```
There should be a delay in between the GetString call and SetFeature.

2022-02-07 18:57 UTC, Sublimelime commented on OpenTabletDriver/InputDevice.cs
> +            if (FeatureInitDelayMs != 0)
Is this check even necessary? Does calling `Thread.Sleep(0);` result in undefined behavior? Theoretically if it doesn't cause issues it'd be better to just always call it, and if it's 0, it just sleeps for 0, which _should_ be a no op? Unless that's not allowed, I haven't looked at the Thread.Sleep docs.

2022-02-07 19:18 UTC, vedattt commented on OpenTabletDriver/InputDevice.cs
> +            if (FeatureInitDelayMs != 0)
It looks like you meant to comment on line 81. This check right here is in fact necessary to avoid a redundant log message.

2022-02-07 19:32 UTC, vedattt commented on OpenTabletDriver/InputDevice.cs
> +            if (FeatureInitDelayMs != 0)
Anyway, the check may be significant because `Sleep(0)` is not a no op statement. As per the docs, it yields execution to any thread of equal priority waiting to run.

2022-02-23 13:20 UTC, jamesbt365 commented
This pr works with the PTZ-630 (thanks @OniCado) with 125ms delay (115 works as well). This was tested with Voids patch on top of this.

2022-03-26 08:49 UTC, gonX commented
I prefer testing this without VoiD's patch first. We don't want to add more lines than necessary.

2022-03-26 08:49 UTC, gonX commented
Marking as ready btw since I'm pretty sure it should work

2022-03-26 13:29 UTC, X9VoiD approved these changes

2022-04-06 03:04 UTC, Kuuuube requested changes
Edit: I misunderstood what this PR is doing but if it is just adding a new option to configs it should either make the changes to fix #1717 or have a PR depending on it that fixes #1717.

~~Does not fix the issue. I assume this was not tested with a config that had multiple inits or it was not tested plugging in a tablet while otd is running.~~

~~Those are the two things this pr should fix.~~

~~For further testing:~~
~~1. These are configs this should be tested with:
[configurations.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8423299/configurations.zip)~~
~~2. The tablet should only be plugged in while otd is running. Plugging in the tablet then starting otd will not replicate the issue in #1717.~~

2022-04-06 03:28 UTC, Kuuuube approved these changes
Tested this with PTZ-431W and was able to get this working with as low as 70ms. Not sure what the time needed depends on. Would be good to have more testing and this really should have a pr based off it for the needed config changes.

2022-04-13 16:08 UTC, InfinityGhost requested changes

2022-04-13 16:08 UTC, InfinityGhost commented on OpenTabletDriver/InputDevice.cs
> +        private readonly string DelayAttributeKeyName = "FeatureInitDelayMs";
Don't directly apply this suggestion, refactor from within your IDE.
```suggestion
        private uint _featureInitDelayMs;
        private const string DELAY_ATTRIBUTE_KEY_NAME = "FeatureInitDelayMs";
```

2022-04-13 16:42 UTC, merged

2022-04-13 17:17 UTC, X9VoiD commented
Resolved by #2183