Updater: Add file IncludeList
OpenTabletDriver/OpenTabletDriver pull request #1956
Opened 2022-01-15 18:28 UTC by InfinityGhost

This stops the updater from backing up files that are not related to OpenTabletDriver when updating.

2022-01-15 19:15 UTC, Kuuuube commented
Getting errors while trying to update with this even without any excess files present:
[error1.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7875721/error1.txt)
[error2.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7875722/error2.txt)

2022-01-15 21:54 UTC, X9VoiD requested changes

2022-01-15 21:54 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Updater/WindowsUpdater.cs
> +            "Configurations"
We don't need to move `Configurations`

2022-01-15 21:54 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Updater/Updater.cs
> +        protected virtual void ExclusiveFileOp(string source, string rollbackDir, string versionRollbackDir, string target,
This is a random change.

2022-01-15 21:54 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Updater/WindowsUpdater.cs
> +using System.IO;
A

2022-01-15 21:54 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Updater/Updater.cs
> +                childEntries = childEntries.Intersect(IncludeList);
The `IncludeList` here will erroneously exclude `appdata` backups.

2022-01-15 21:54 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Updater/Updater.cs
> +                childEntries = childEntries.Intersect(IncludeList);
```suggestion
                childEntries = childEntries.Intersect(IncludeList.Select(Path.Join(source, IncludeList)));
```

2022-01-15 21:54 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Updater/Updater.cs
> +        protected virtual string[]? IncludeList { get; } = null;
Convert to abstract, remove `?` and `null`. Implement `IncludeList` in MacOS.

2022-01-15 22:15 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Updater/Updater.cs
> +        protected virtual string[]? IncludeList { get; } = null;
IncludeList on macOS would be ~100 files. Nah.

2022-01-15 22:23 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Updater/Updater.cs
> +        protected virtual void ExclusiveFileOp(string source, string rollbackDir, string versionRollbackDir, string target,
IncludeList is not static. The virtual change was unintentional.

2022-01-15 22:25 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Updater/WindowsUpdater.cs
> +            "Configurations"
When broken configurations are left over don't expect me to be surprised.

2022-01-16 15:44 UTC, Kuuuube reviewed
Upon first launch I got these errors:
[error1.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7877268/error1.txt)
[error2.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7877269/error2.txt)
It was run with an empty userdata folder present and nothing else. Couldn't seem to replicate it again... not sure if this is a potential concern or not. 

The includelist stuff all works as intended it seems. No clue what the error I got initially was caused by.

2022-01-16 15:49 UTC, Kuuuube approved these changes

2022-01-16 18:48 UTC, X9VoiD approved these changes

2022-01-16 19:52 UTC, merged