On MacOS, prevent user from launching the app when it is translocated.
OpenTabletDriver/OpenTabletDriver pull request #1976
Opened 2022-01-17 16:10 UTC by AkiSakurai

The app doesn't work properly with App Translocation [^1].

[^1]: https://lapcatsoftware.com/articles/app-translocation.html

2022-02-03 13:03 UTC, vedattt requested changes

2022-02-03 13:03 UTC, vedattt commented on OpenTabletDriver.UX.MacOS/Program.cs
> +                    "such as to the Applications folder.");
```suggestion
                    "OpenTabletDriver cannot be run from this folder (/private/var/folders). " +
                    "Please move it elsewhere, such as to the Applications folder.");
```
Rewording and clarification.

2022-02-03 14:09 UTC, AkiSakurai commented on OpenTabletDriver.UX.MacOS/Program.cs
> +                    "such as to the Applications folder.");
The path /private/var/folders is invisible to the user.

From the users point of view, the app is still in Downloads folder. 

The system silently copy the app to that folder and launch from there if the app is downloaded from internet.

2022-02-03 14:17 UTC, vedattt commented on OpenTabletDriver.UX.MacOS/Program.cs
> +                    "such as to the Applications folder.");
Ah, I see, I'm not really familiar with macOS.
Probably still worth considering clarifying it without the path though:
```suggestion
                    "OpenTabletDriver cannot be run from this folder for security reasons. " +
                    "Please move it elsewhere, such as to the Applications folder.");
```

2022-02-03 14:34 UTC, vedattt approved these changes

2022-02-09 01:37 UTC, InfinityGhost requested changes

2022-02-09 01:37 UTC, InfinityGhost commented on OpenTabletDriver.UX.MacOS/Program.cs
> +                    "Please move it elsewhere, such as to the Applications folder.");
```suggestion
                MessageBox.Show("OpenTabletDriver must be installed to the Applications folder.");
```

2022-11-07 13:36 UTC, gonX commented
need rebase

2023-01-02 18:06 UTC, jamesbt365 approved these changes

2023-01-02 18:51 UTC, merged