Libinput quirks generator
OpenTabletDriver/OpenTabletDriver pull request #1983
Opened 2022-01-18 20:00 UTC by gonX

This is going to be useful (and hopefully mandatory) for packagers to ship (and adjust) a libinput quirks file. 

This fixes #1514 if maintainers are gentle and don't re-enable the smoothing option.

I've left the option in should an expert user decide to keep it

Unrelated to the PR but we should probably check for the presence of this file, or probe quirk behavior for virtual tablet endpoint on daemon start so that we can ensure behavior is as expected.

If anyone is aware of setting these quirks _in code_ instead of in packaging this would be greatly appreciated, as it'd ensure that we can get a consistent experience across all distros without having to worry about packaging.

2022-01-19 00:29 UTC, gonX commented
This needs to also update README.md similar to how ./generate-rules.sh did

2022-01-20 18:38 UTC, Sublimelime requested changes

2022-01-20 18:38 UTC, Sublimelime commented on OpenTabletDriver.Tools.LibinputQuirks/Program.cs
> +            unclean |= filenameContainsQuirks;
I dislike this - instead of having that conditional in a boolean, just put that directly into the if conditional. The "unclean" thing is also not good - not only will this redundantly log (if filenameContainsQuirks is false, you mention it won't be parsed by libinput.... so fix that for them, or fail out lmao - plus you then use "unclean" to log again that there might be issues - they already know.)

I would simply check if the filename ends in .quirks, and if it doesn't, append it for them. Simple. Nix the unclean thing too, we should either autofix errors like the above, or just fail out. Generating a likely useless file is bad.

2022-01-20 18:38 UTC, Sublimelime commented on OpenTabletDriver.Tools.LibinputQuirks/Program.cs
> +        static async Task WriteQuirksAsync(uint tipDownPressurePermille, uint tipUpPressurePermille, bool smoothing, bool skipPressure, FileInfo output, bool verbose)
Large amount of parameters here, and makes line 33 above hard to read too with it's long "<uint, uint, bool, bool....".

I would collapse the first 4 into a struct that you could pass to it instead. Something like QuirkDetails or something.

2022-01-20 18:48 UTC, X9VoiD commented on OpenTabletDriver.Tools.LibinputQuirks/Program.cs
> +            unclean |= filenameContainsQuirks;
`unclean` variable here is used just in case there will be future other "warnings".

The best compromise here imo is to notify user of the rename but not as a warning, and therefore it won't be "unclean".

I see an exception a few lines before this, and I'd argue using the unclean thing for that instead of throwing an exception there to keep the `unclean`. Humans parse sentences better than a sentence in a stack trace.

2022-01-20 18:48 UTC, gonX commented on OpenTabletDriver.Tools.LibinputQuirks/Program.cs
> +        static async Task WriteQuirksAsync(uint tipDownPressurePermille, uint tipUpPressurePermille, bool smoothing, bool skipPressure, FileInfo output, bool verbose)
Ok. I'll do a class though. I don't think a struct makes sense, we're not really modifying any values. So a class should be more performant - not that it matter though.

2022-01-20 18:48 UTC, gonX commented on OpenTabletDriver.Tools.LibinputQuirks/Program.cs
> +            unclean |= filenameContainsQuirks;
I don't like assuming things about a users environment. It's mostly meant to be used by packagers but with the flexibility of being usable on random distros having niche requirements or doing things differently. The udev tool has no similar check and will fail in a similar way if not named correctly, so I think it's better to err on the side of caution here.



As for the `unclean` variable that mostly exists if further error checking is needed down the line, then the final error check line does not look messy.

If there is more opposition to `unclean` I'll remove it.

Btw, since this is 2 issues in 1 conversation it's hard for me to really resolve this.

2022-01-20 18:54 UTC, Sublimelime commented on OpenTabletDriver.Tools.LibinputQuirks/Program.cs
> +        static async Task WriteQuirksAsync(uint tipDownPressurePermille, uint tipUpPressurePermille, bool smoothing, bool skipPressure, FileInfo output, bool verbose)
Sure, whatever works, In c++ structs and classes are basically the same thing with the same performance but structs are used for simple groups of variables - I'm used to c++ so I guess use whatever the c# equivalent is.

2023-05-31 21:05 UTC, doubledge-spec commented
update?

2023-10-24 22:18 UTC, gonX commented on OpenTabletDriver.Tools.LibinputQuirks/Program.cs
> +        static string GeneratePressureRange(uint tipDownPressure, uint tipUpPressure) => tipDownPressure + ":" + tipUpPressure;
Resolved in e3e5cf8ae

2023-10-24 22:18 UTC, gonX commented on OpenTabletDriver.Tools.LibinputQuirks/Program.cs
> +            unclean |= filenameContainsQuirks;
Both resolved in 7e24c4c652 - I personally don't like the current implementation since the output name is "magically" changed. I'm not sure the current warning message is clear enough, so please take a look.

Ironically, the `unclean` variable may have a comeback to indicate that changes have occurred, at the end of the program.

2023-10-25 00:15 UTC, gonX commented
Rebased and resolved convos.

Remaining steps will be added to the OP.

I've opted to remove the defaulting of the pressure range - this seems unfeasible to set with the current implementation of OpenTabletDriver and that particular feature has seen 0 interest from anyone as far as I know, but if nothing else it is reasonable to leave it in should a user want to change this with some convenience (as it's set referenced to the pressure range OTD will report)

2023-10-25 00:46 UTC, Sublimelime approved these changes
Looks solid and readable. Little bit out of the loop, but nothing jumps out to me as wrong, for what it's worth.

2024-11-14 23:08 UTC, gonX commented
Thinking about it, this is probably better as a standalone application. Only real use is that we can grab the virtual tablet name and its max pressure from code, but we can honestly do both of those too by just having it loosely copy+pasted and then using some sort of test script to ensure it matches whenever a PR changes this, without the maintenance burden that is a full CLI app.

2024-11-14 23:08 UTC, closed without merging