Artistmode revamp
OpenTabletDriver/OpenTabletDriver pull request #1984
Opened 2022-01-18 22:28 UTC by gonX

This cleans up and enhances some code related to Linux Artist Mode. I'm not doing a big writeup like last time but will try to argue for some of the changes.

## Add and implement `IToolReport`
This allows tool serial and ID to be reported on supported tablets (currently only IntuosV1 parser)

There's some quirkiness with tool ID sometimes not submitting correctly. Debugging the code makes me think the `ABS_MISC` report is getting dropped at some point in uinput because even `evtest` isn't always seeing it. We could also be emitting it incorrectly, someone please help find the relevant documentation for this.

Stock Wacom driver IIRC has worse functionality than this so it is at least an upgrade over that, but we may consider not emitting `ABS_MISC` for the time being.

## Don't send `BTN_TOUCH` on nonzero pressure
It's more intuitive for the user to have to bind a button, so we're moving the responsibility of emitting `BTN_TOUCH` to a binding handler instead.

In practice, libinput was handling this fine (despite my initial pessimism)

## Reintroduce pen tip support in `LinuxArtistModeButtonBinding`
This mostly exists because some users have gotten confused over no bindings being the correct solution

While we still can't rewrite pressure, this at least allows the user to control when `BTN_TOUCH` is emitted which should hopefully cover any remaining edge cases with incorrect tip down detection

## Allow "usage" of the 3 standard mouse buttons in artist mode
This allows users to switch from absolute mode to artist mode without being required to change their bindings

However, we are sending the tablet-equivalent events to mouse buttons, and not actually sending LMB/RMB/etc events.

This is because libinput silently drops mouse events from endpoints that passes the libinput tablet sanity check.

The user is incorrectly still able to bind Forward/Backwards mouse buttons which are unimplemented. I have not tested passing those buttons through, however.

**This part of the commit needs extra testing under X11 and other Wayland compositors that isn't Sway.**

## Expose `ABS_DISTANCE` to uinput
For now, I've set a maximum height of 100 as I doubt any tablet is going to go above this. `libwacom` seems to assign the max on a per-tablet basis.

The only way to enhance this would be if we knew the max distance of the tablet ahead of time, similar to how we have MaxPressure at the moment.

libinput seems to drop this, but the same seems to be the case with the upstream driver, so I don't think we're doing anything wrong in that regard. It's still visible in evdev.

## Drop the lift-off height restriction
This previously existed because we needed some way to report negative tool proximity. After we've had `Reset()` and `OutOfRangeReport`s introduced this is no longer necessary.

We have no good events to report for `IProximityReport`s so it's just returning nothing for now and upstream driver seems to have similar behavior (that, or I missed the event it's emitting).

# Footnotes

Test test test even if you think your setup is generic

2022-01-20 18:23 UTC, Sublimelime requested changes

2022-01-20 18:23 UTC, Sublimelime commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/EvdevVirtualTablet.cs
> +            return;
This shouldn't fail silently - if this is supposed to be impossible, we should either straight up remove the function or `throw new NotSupportedException`, unless I'm misunderstanding.

Just silently returning in a void function without doing anything spells hard to find breaks later.

2022-01-20 18:29 UTC, gonX commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/EvdevVirtualTablet.cs
> +            return;
Ah, I forgot after the rework X9VoiD did that we now have `IProximityHandler`, so I'll just not inherit from that interface

2022-01-20 18:29 UTC, gonX commented
I am tracking down some issue with stuck pen tip so this should not be merged for now

2022-01-20 18:33 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Binding/LinuxArtistMode/LinuxArtistModeButtonBinding.cs
> +            "Pen Tip"
Put "Pen Tip" as the first valid button.

2022-01-20 18:34 UTC, gonX commented
X9VoiD suggested that we just get rid of the `IProximityHandler` interface since the PR removes the only bit of code that was actually using that interface, and `NearProximity` is still usable with plugins if we remove that.

2022-11-19 17:08 UTC, gonX commented
Superseded by #2503 #2504 #2505 #2506 #2507 #2508

Some later commits in this PR were not implemented as they were (unsuccessful) attempts at fixing the weird behavior noted in the bottom of the OP, so they've been split so they can be tested individually.

2022-11-19 17:08 UTC, closed without merging