Add RobotPen T9A Support
OpenTabletDriver/OpenTabletDriver pull request #2008
Opened 2022-01-25 16:00 UTC by fangxx3863

A niche tablet support
Official website -> https://www.robotpen.com/product/wk

2022-01-25 16:27 UTC, X9VoiD requested changes

2022-01-25 16:27 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/RobotPen/T9A.json
> +      "MaxY": 16896.0
The ratios for Width/Height and MaxX/MaxY do not match. These also doesn't represent a sensible LPI/LPmm, but it's near 2000 LPI.

Did you mean:
```suggestion
      "Width": 289.36,
      "Height": 214.58,
      "MaxX": 22784.0,
      "MaxY": 16896.0
```

2022-01-25 16:27 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Parsers/RobotPen/RobotPenTabletReport.cs
> +                Y = Unsafe.ReadUnaligned<ushort>(ref report[8]) | (report[9] << 8)
The extra fluff here is redundant.

```suggestion
                X = Unsafe.ReadUnaligned<ushort>(ref report[6]),
                Y = Unsafe.ReadUnaligned<ushort>(ref report[8])
```

2022-01-25 16:27 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Parsers/RobotPen/RobotPenReportParser.cs
> +        }
Do *not* use strings to compare numerics ever again.

I'm assuming that non-`0x42` reports are out-of-range. Please do correct me if I'm wrong.

```suggestion
        {
            if (report[1] == 0x42)
                return new RobotPenTabletReport(report);

            return new OutOfRangeReport(report);
        }
```

2022-01-25 16:27 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Parsers/RobotPen/RobotPenTabletReport.cs
> +            Eraser = report[11].IsBitSet(6);
This doesn't make any sense.

Pressure is a `ushort` which spans two bytes, however Eraser is parsed from the same byte that Pressure uses. Are you sure about this? If yes, then apply bit-wise mask to Pressure and avoid conflicting reads.

2022-01-25 16:27 UTC, X9VoiD commented on OpenTabletDriver/SystemDrivers/Providers/RobotPenDriverInfoProvider.cs
> +        protected override string LinuxModuleName => "hid_uclogic";
I'd like to see this tested on Linux if this tablet is actually supported by `hid_uclogic`.

2022-01-25 16:27 UTC, X9VoiD commented on OpenTabletDriver/SystemDrivers/Providers/RobotPenDriverInfoProvider.cs
> +        };
I wanna see proof if these process names are correct.

So basically:

- Install OEM driver.
- Find OEM driver executables.
- Send proof here (preferably a screenshot) of the process names.

2022-01-25 16:27 UTC, X9VoiD commented on OpenTabletDriver/SystemDrivers/Providers/RobotPenDriverInfoProvider.cs
> +        };
I also wanna see proof for this.

- Install OEM driver.
- Run `pnputil -e`.
- Send output here.

2022-01-25 16:27 UTC, X9VoiD commented on TABLETS.md
> +| RobotPen T9A                  |     Supported     |
Alphabetical order please.

2022-01-26 05:50 UTC, fangxx3863 commented
I got the real xy from the official SDK 
But the strange thing is that my actual measurements cannot satisfy the aspect ratio 
Do I take an approximation like the picture below?
![image](https://user-images.githubusercontent.com/48589001/151110438-9226ffa6-a2d7-4624-a0c8-8b598df4d930.png)
![IMAGE 2022-01-26 13:48:55](https://user-images.githubusercontent.com/48589001/151110500-c8ef41ac-730a-4758-9c6e-57a61d900831.jpg)
![IMAGE 2022-01-26 13:49:00](https://user-images.githubusercontent.com/48589001/151110512-9b5fa79e-20f6-43f6-8289-33f1569bba3e.jpg)
![IMAGE 2022-01-26 13:49:07](https://user-images.githubusercontent.com/48589001/151110524-5e33acd5-5771-4d6b-aab9-276376fe2b1e.jpg)

2022-01-26 08:59 UTC, X9VoiD commented
- Go to OTD -> Tablet -> Tablet Debugger
- Press "Enable recording"
- *Slowly* hover your pen from top left to bottom right of the physical tablet
- Go to `%localappdata%/OpenTabletDriver`
- Upload `tablet-data.txt`

2022-01-26 13:50 UTC, fangxx3863 commented
This is `tablet-data.txt` 
[tablet-data.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7942115/tablet-data.txt)
I also write a python script and this picture shows the coordinates where the pen was last detached 
![image](https://user-images.githubusercontent.com/48589001/151174854-e4cac35f-6f88-4dc8-b4cf-34322339ec6e.png)

2022-01-26 16:19 UTC, X9VoiD requested changes

2022-01-26 16:19 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/RobotPen/T9A.json
> +      "MaxY": 16650.0
```suggestion
      "Width": 295.11,
      "Height": 216.69,
      "MaxX": 22656.0,
      "MaxY": 16636.0
```

The MaxX, and MaxY here are final. I assumed that the device has `1950 LPI` resolution to get the new Width and Height, do they look closer to the "truth"?

2022-01-26 16:19 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/RobotPen/T9A.json
> +        "ButtonCount": 3
The pen has three buttons?

Go to Tablet Debugger, then record yourself pressing on the pen buttons three times each. Then upload `tablet-data.txt` here again.

2022-01-26 16:19 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/RobotPen/T9A.json
> +      "ButtonCount": 1
Does the tablet itself (not the pen) only have one button on it?

Go to Tablet Debugger, then record yourself pressing on the tablet buttons. Make sure that the pen is *out of range* of the tablet during recording. Then upload `tablet-data.txt` here again

2022-01-26 16:19 UTC, X9VoiD commented on OpenTabletDriver/SystemDrivers/Providers/RobotPenDriverInfoProvider.cs
> +    internal class RobotPenDriverInfoDriver : ProcessModuleQueryableDriverInfoProvider
Delete this whole class for now.

2022-01-27 02:22 UTC, fangxx3863 commented on OpenTabletDriver.Configurations/Configurations/RobotPen/T9A.json
> +        "ButtonCount": 3
Thanks for the edit, the pen has only one button

2022-01-27 14:44 UTC, fangxx3863 commented on OpenTabletDriver/SystemDrivers/Providers/RobotPenDriverInfoProvider.cs
> +        protected override string LinuxModuleName => "hid_uclogic";
![IMAGE 2022-01-27 22:43:45](https://user-images.githubusercontent.com/48589001/151381502-508be881-d38f-48fd-9e01-61aa30298e6f.jpg) 
The third row

2022-01-29 06:14 UTC, fangxx3863 commented on OpenTabletDriver.Configurations/Parsers/RobotPen/RobotPenTabletReport.cs
> +                (report[11] & (1 << 1)) != 0
YES

2022-02-07 07:21 UTC, X9VoiD commented
I still have some doubts with some parts of this PR, but will merge as is and just hotfix when bugs to the report parser are reported in the future.

2022-02-07 07:21 UTC, merged

2022-02-07 08:27 UTC, fangxx3863 commented
OK, thanks for your reply