Overhaul debugger report recording UI
OpenTabletDriver/OpenTabletDriver pull request #2009
Opened 2022-01-25 19:38 UTC by Sublimelime

Medium PR to overhaul the UI for making recordings of tablet reports.

- Fixes #2000 
- Fixes #2006 

Notable changes:

- Data recording is now a start/stop button system instead of a checkbox. Buttons flip "Enabled" status to clearly indicate when a recording is happening (and prevents starting/stopping recordings twice ofc)
- File to write to can be selected when start button is pressed, and file is closed when stop button is pressed, or when the debugger is closed. This allows for multiple independent recordings to different files, however currently this does not reset the "Reports recorded" value back to 0 each time, let me know if this would be wise to do as well.
- Addressing the issues in #2000, said reports recorded value is hidden until a recording is made in that debug session (re-hidden when the debugger is closed).

2022-01-25 19:47 UTC, X9VoiD requested changes

2022-01-25 19:47 UTC, X9VoiD commented on OpenTabletDriver.UX/Windows/Tablet/TabletDebugger.cs
> +            }
Handle cases where `File.OpenWrite` has thrown an exception, etc.

2022-01-25 19:47 UTC, X9VoiD commented on OpenTabletDriver.UX/Windows/Tablet/TabletDebugger.cs
> +        private void startRecording() => Application.Instance.AsyncInvoke(() =>
Reset "Reports Recorded" to zero every start.

2022-01-25 20:20 UTC, X9VoiD approved these changes

2022-01-26 03:16 UTC, Sublimelime commented on OpenTabletDriver.UX/Windows/Tablet/TabletDebugger.cs
> +            Text = "Start Recording",
```suggestion
            Text = "⏵Start Recording",
```

I considered adding a unicode triangle to the start recording button (and a unicode square symbol for the stop recording button) - but was unsure if this would display correctly on all platforms, or if it'd look right.

@InfinityGhost thoughts?

2022-01-26 19:55 UTC, Sublimelime commented on OpenTabletDriver.UX/Windows/Tablet/TabletDebugger.cs
> +            Text = "Start Recording",
After some experimentation it seems that unicode symbols aren't universal, and many platforms cannot display them, or use emojis instead - so cancel this idea.

2022-01-27 17:33 UTC, InfinityGhost commented on OpenTabletDriver.UX/Windows/Tablet/TabletDebugger.cs
> +        private void startRecording() => Application.Instance.AsyncInvoke(() =>
```suggestion
        private void StartRecording() => Application.Instance.AsyncInvoke(() =>
```

2022-01-27 17:33 UTC, InfinityGhost commented on OpenTabletDriver.UX/Windows/Tablet/TabletDebugger.cs
> +            stopRecording();
```suggestion
            StopRecording();
```

2022-01-27 17:34 UTC, InfinityGhost commented on OpenTabletDriver.UX/Windows/Tablet/TabletDebugger.cs
> +            stopDataRecordingButton.Click += (sender, e) => stopRecording();
```suggestion
            startDataRecordingButton.Click += (sender, e) => StartRecording();
            stopDataRecordingButton.Click += (sender, e) => StopRecording();
```

2022-01-28 16:53 UTC, gonX commented
Screenshots would be cool

2022-01-28 21:34 UTC, Sublimelime commented
> Screenshots would be cool

Added

2022-07-29 20:06 UTC, Sublimelime commented
Superseded by #2352

2022-07-29 20:06 UTC, closed without merging