Overhaul/rewrite CONTRIBUTING.md
OpenTabletDriver/OpenTabletDriver pull request #2019
Opened 2022-01-27 19:30 UTC by Sublimelime

Changed some wording around, formatted long lines, added clarification to
config contribution area, added way more information to code
contribution area.

Opened as draft to gather more feedback for now. Feel free to suggest additional things to add, correct me, etc.

2022-01-27 22:15 UTC, vedattt requested changes
Massive review huh

2022-01-27 22:15 UTC, vedattt commented on CONTRIBUTING.md
> +the daemon part of the driver, which performs the bulk of the "work" and thus is critical to test.
```suggestion
Our CI runs unit tests on each new commit pushed on a PR, but if you'd like to test OpenTabletDriver locally, you can do so by running the command `dotnet test OpenTabletDriver` from the project root, which will run all tests and report status.
The unit tests for the most part concern the daemon part of the driver, which performs the bulk of the "work" and thus is critical to test.
```
Rewording. Also specified the project of the test command, in case it is needed as is the case with dotnet format.

2022-01-27 22:15 UTC, vedattt commented on CONTRIBUTING.md
```suggestion

With any contribution you make, we ask that your commits are named sensibly and similarly to the ones in our [history](https://github.com/OpenTabletDriver/OpenTabletDriver/commits/master).
At the very least, sentence-case your commits, and do consider prefixing the commit message with a component name in similar fashion to `Updater: Add file IncludeList`.
If the reasoning for a commit is potentially cryptic, consider adding a commit description to it, succinctly explaining why it was needed.

```

2022-01-27 22:30 UTC, Sublimelime commented on CONTRIBUTING.md
> +Tablet configurations are the core at what defines a tablet within OpenTabletDriver. It provides
Dislike this wording. How about instead:

```suggestion
Tablet configurations define tablets OpenTabletDriver can detect and operate. They provide
```

2022-01-27 22:31 UTC, vedattt commented on CONTRIBUTING.md
> +Tablet configurations are the core at what defines a tablet within OpenTabletDriver. It provides
LGTM

2022-01-27 22:32 UTC, Sublimelime commented on CONTRIBUTING.md
> +make another (as your new PR will contain commits from your previous).
osu!'s repo recommends similar, as well as "git best practices" that I've read. Your fork's master should pretty much always stay in line with upstream's master.

2022-01-27 22:33 UTC, vedattt commented on CONTRIBUTING.md
> +make another (as your new PR will contain commits from your previous).
Fair enough, safe to call this one resolved then.

2022-03-03 21:29 UTC, InfinityGhost requested changes

2022-03-03 21:29 UTC, InfinityGhost commented on CONTRIBUTING.md
> +  without verifying.
```suggestion
  by manufacturers have unfortunately been known to be wrong on occasion - do not trust them
  without verifying them first.
```

2022-03-03 21:29 UTC, InfinityGhost commented on CONTRIBUTING.md
> +are all suitable. Note that VSCode will require you to install C# extensions first.
May be worth stating that most use JetBrains Rider, along with linking each of the listed IDEs.

2022-03-03 21:29 UTC, InfinityGhost commented on CONTRIBUTING.md
> +`build.sh` (for Linux). If successful, these scripts will produce executables in a newly created
```suggestion
`build.sh` (for Linux and macOS). If successful, these scripts will produce executables in a newly created
```

2022-03-03 21:58 UTC, vedattt requested changes

2022-03-03 21:58 UTC, vedattt commented on CONTRIBUTING.md
> +Rider](https://www.jetbrains.com/community/opensource/#support) can be obtained.
```suggestion
OpenTabletDriver is a fairly simple project to set up for development. As it's a .NET project, you
ideally want an IDE capable of working with C# and .NET projects, such as:

- [VSCode](https://code.visualstudio.com/) (with C# extensions installed)
- [Rider](https://www.jetbrains.com/rider/) (used by many C# developers and is our recommended IDE)
- [Visual Studio](https://visualstudio.microsoft.com/)

Note that OpenTabletDriver being an open source project means [a permanent free license to use
Rider](https://www.jetbrains.com/community/opensource/#support) can be obtained.
```
Paragraph was a bit of a mess with all the parentheses and links inline.
Also a few touches, like capturing the entire noun with adjectives when linking the Rider license.

2022-03-03 22:16 UTC, InfinityGhost commented on CONTRIBUTING.md
> +Rider](https://www.jetbrains.com/community/opensource/#support) can be obtained.
> permanent free license to use

It must be updated yearly, and only free to use for open source projects.

2022-03-07 20:15 UTC, InfinityGhost approved these changes

2022-03-07 20:15 UTC, merged