Relative mode reset fix
OpenTabletDriver/OpenTabletDriver pull request #2053
Opened 2022-02-07 05:09 UTC by Blue-FlipFlop

The current relative mode positioning does not reset as intended. When lifting a pen from a tablet and placing it down again, the cursor moves instead of remaining in the same location, as shown below.
https://user-images.githubusercontent.com/57815456/152726588-c85d3781-6cbc-414f-bbb7-f1a63a8e1149.mp4

I believe the issue is that while pos is set to the zero vector, the lastPos attribute does not change when the position is supposed to be reset. This leads to delta being the new pen position instead of being zero. My change adds a new attribute, resetNext, which indicates whether next Transform call should have no movement. This results in the intended behaviour, shown below.
https://user-images.githubusercontent.com/57815456/152727704-d1e27d96-9c6f-4b42-b449-ec3fefbf206b.mp4

2022-02-07 06:53 UTC, X9VoiD approved these changes

2022-02-07 10:05 UTC, AkiSakurai commented
I think the problem is that your tablet is sending cached report when the pen is in range.
Your solution works when the tablet only send one cached report.

I have another tablet Parblo a640 v2 that is sending two cached report.
```
Report:02 A0 1F 43 82 25 00 00  17183 9602 timestamp:  113249199
Report:02 A0 C4 42 82 25 00 00  17092 9602 timestamp:  113249204
Report:02 A0 65 42 82 25 00 00  16997 9602 timestamp:  113249209
Report:02 A0 02 42 96 25 00 00  16898 9622 timestamp:  113249214
Report:02 A0 96 41 AE 25 00 00  16790 9646 timestamp:  113249220
Report:02 A0 2E 41 C8 25 00 00  16686 9672 timestamp:  113249225
Report:02 A0 CC 40 E0 25 00 00  16588 9696 timestamp:  113249229
Report:02 C0 CC 40 E0 25 00 00  16588 9696 timestamp:  113249245


Move away for a while


Report:02 A0 CC 40 E0 25 00 00  16588 9696 timestamp:  113252757
Report:02 A0 CC 40 E0 25 00 00  16588 9696 timestamp:  113252761
Report:02 A0 DB 35 E7 3E 00 00  13787 16103 timestamp:  113252766
Report:02 A0 C0 35 E7 3E 00 00  13760 16103 timestamp:  113252771
Report:02 A0 9E 35 E7 3E 00 00  13726 16103 timestamp:  113252776
Report:02 A0 74 35 E7 3E 00 00  13684 16103 timestamp:  113252782
```

2022-02-07 18:54 UTC, Blue-FlipFlop commented
@AkiSakurai Thanks for the response. I have not considered tablets sending different numbers of reports. I don't know how to fix the issue for multiple cached reports.

2022-03-11 17:48 UTC, InfinityGhost requested changes

2022-03-11 17:48 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Output/RelativeOutputMode.cs
> +        private Boolean resetNext = false;
```suggestion
        private bool resetNext = false;
```

2022-11-07 13:37 UTC, gonX commented
This needs a rebase to the new codebase

2023-05-22 16:59 UTC, X9VoiD commented
Superseded by #2719

2023-05-22 16:59 UTC, closed without merging