Add support for Huion H642
OpenTabletDriver/OpenTabletDriver pull request #2063
Opened 2022-02-12 12:29 UTC by jamesbt365

Verification: https://discord.com/channels/615607687467761684/723399565780189234/942034357990850601

2022-02-12 12:30 UTC, jamesbt365 commented
This seems to share the name with the rts-300.

2022-02-23 06:24 UTC, X9VoiD requested changes

2022-02-23 06:24 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/Huion/H642.json
> +      "MaxPressure": 9181,
```suggestion
      "MaxPressure": 8191,
```

2022-02-23 10:14 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/Huion/H642.json
> +      "MaxPressure": 9181,
oops.

2022-02-24 04:28 UTC, merged