Add support for Parblo A609
OpenTabletDriver/OpenTabletDriver pull request #2079
Opened 2022-02-18 20:39 UTC by jamesbt365

Verification: https://canary.discord.com/channels/615607687467761684/723399565780189234/944331750614646794

2022-02-23 06:27 UTC, X9VoiD requested changes

2022-02-23 06:27 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/Parblo/A609.json
> +      "ReportParser": "OpenTabletDriver.Configurations.Parsers.Wacom.IntuosV1.IntuosV1ReportParser",
Are you sure about this?

2022-02-23 10:13 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/Parblo/A609.json
> +      "ReportParser": "OpenTabletDriver.Configurations.Parsers.Wacom.IntuosV1.IntuosV1ReportParser",
see [here](https://discord.com/channels/615607687467761684/723399565780189234/944316013908987914) for why a wacom parser was used, the xp pen parser which other parblos use just causes the movement to be mapped to pressure and pen tilt.

2022-02-24 04:31 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/Parblo/A609.json
> +      "ReportParser": "OpenTabletDriver.Configurations.Parsers.Wacom.IntuosV1.IntuosV1ReportParser",
I don't want to believe that another company has gotten hold of patented hardware that they don't own, but, given the amount of evidence there, I'll merge. We'll get back to this if somebody reported otherwise.

2022-02-24 04:31 UTC, X9VoiD approved these changes

2022-02-24 04:32 UTC, merged