add support for huion 1060 plus
OpenTabletDriver/OpenTabletDriver pull request #2133
Opened 2022-03-20 21:41 UTC by WebFreak001

Before the tablet would not have been recognized (most closely related to "New huion 1060 plus" with all the device strings, but input report length is 8)

Behavior is pretty weird where it sometimes doesn't properly detect the tablet and instead uses some built-in X11/libinput for the pointer device, but pressing aux buttons (seems important to properly reset) and reconnecting the USB makes it use otd again. When otd is not running the tablet seems to randomly be detected as mouse or not after fresh reboot, where then it may or may not be broken when first running otd.

Aux buttons all work and is detected properly in tablet debugger now:
![tablet debugger](https://wfr.moe/f69VpO.png)

2022-03-20 21:43 UTC, jamesbt365 commented
![image](https://user-images.githubusercontent.com/22662856/159187162-e53c584c-1510-40ac-a98a-fec070dde820.png)
?

2022-03-20 21:43 UTC, jamesbt365 commented
wait they are different ignore me

2022-03-20 21:52 UTC, jamesbt365 commented
Upon further inspection this is actually the same as the [New Huion 1060 Plus](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/OpenTabletDriver.Configurations/Configurations/Huion/New%201060%20Plus%20(2048).json#L32), the only difference is you picked a different length and the size. I remember adding this configuration myself. Mind exporting a diagnostic? (that button issue is your system i'm pretty sure)

2022-03-20 22:33 UTC, WebFreak001 commented
the tablet wasn't detected with 16 on input length, I started off with the new huion 1060 plus, but it seems on the old one the input length was 8.

2022-03-20 22:35 UTC, jamesbt365 commented
Throw on another identifer on the other configuration is the ideal solution as this tablet is the same other than report lengths.

2022-03-20 22:37 UTC, WebFreak001 commented
diagnostics (with irrelevant usb devices removed):

```json
{
  "App Version": "OpenTabletDriver v0.6.0.3+3a35c859",
  "Build Date": "3/20/2022",
  "Operating System": {
    "Platform": 4,
    "ServicePack": "",
    "Version": "5.16.13.1",
    "VersionString": "Unix 5.16.13.1"
  },
  "Environment Variables": {
    "USER": "webfreak",
    "TEMP": null,
    "TMP": null,
    "TMPDIR": null,
    "DISPLAY": ":0",
    "WAYLAND_DISPLAY": null,
    "PWD": "/home/webfreak/dev/OpenTabletDriver",
    "PATH": "/home/webfreak/.local/bin:/home/webfreak/.npm-packages/bin:/home/webfreak/etc-bin:/usr/share/dotnet/sdk/6.0.102/Sdks:/usr/share/dotnet:/home/webfreak/.local/bin:/home/webfreak/.npm-packages/bin:/home/webfreak/etc-bin:/usr/share/dotnet/sdk/6.0.102/Sdks:/usr/share/dotnet:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/android-sdk/emulator:/home/webfreak/.dotnet/tools:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/rocm-5.0.0/bin:/opt/rocm-5.0.0/hip/bin"
  },
  "HID Devices": [
    /* ... mouse, keyboard and mainboard LED here */
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4.1/1-4.1:1.0/0003:256C:006E.0032/hidraw/hidraw10",
      "Manufacturer": "Unknown Manufacturer",
      "ProductName": "PenTablet ",
      "SerialNumber": "",
      "FriendlyName": "PenTablet ",
      "VendorID": 9580,
      "ProductID": 110,
      "InputReportLength": 8,
      "OutputReportLength": 0,
      "FeatureReportLength": 0,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4.1/1-4.1:1.2/0003:256C:006E.0034/hidraw/hidraw19",
      "Manufacturer": "Unknown Manufacturer",
      "ProductName": "PenTablet ",
      "SerialNumber": "",
      "FriendlyName": "PenTablet ",
      "VendorID": 9580,
      "ProductID": 110,
      "InputReportLength": 8,
      "OutputReportLength": 0,
      "FeatureReportLength": 0,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4.1/1-4.1:1.1/0003:256C:006E.0033/hidraw/hidraw12",
      "Manufacturer": "Unknown Manufacturer",
      "ProductName": "PenTablet ",
      "SerialNumber": "",
      "FriendlyName": "PenTablet ",
      "VendorID": 9580,
      "ProductID": 110,
      "InputReportLength": 8,
      "OutputReportLength": 0,
      "FeatureReportLength": 6,
      "CanOpen": true
    }
  ],
  "Console Log": [
    {
      "Time": "2022-03-20T23:35:13.4723983+01:00",
      "Group": "Detect",
      "Message": "Searching for tablets...",
      "StackTrace": null,
      "Level": 1,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4724549+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet '10moon 1060N'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4724695+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Acepen AP 1060'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4724822+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Artisul A1201'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.472493+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Artisul M0610 Pro'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4725033+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon 1060 Pro'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4725119+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon M106K Pro'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4725202+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon M106K'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.472531+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon M10K Pro'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4725543+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon M10K'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.472581+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon M1220'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4725962+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon M1230'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4726174+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon PD1161'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4726352+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon PD1560'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.472664+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon PD1561'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4726813+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon S56K'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4726908+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon S620'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4726998+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Gaomon S630'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4727112+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Genius G-Pen 560'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4727283+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Genius i608x'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.47274+01:00",
      "Group": "Detect",
      "Message": "Searching for tablet 'Huion 1060 Plus'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4727491+01:00",
      "Group": "Detect",
      "Message": "More than 1 matching device has been found.",
      "StackTrace": null,
      "Level": 2,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.472758+01:00",
      "Group": "Device",
      "Message": "Initializing device 'PenTablet ' /sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4.1/1-4.1:1.2/0003:256C:006E.002E/hidraw/hidraw18",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.4727676+01:00",
      "Group": "Device",
      "Message": "Using report parser type 'OpenTabletDriver.Configurations.Parsers.UCLogic.UCLogicReportParser'",
      "StackTrace": null,
      "Level": 0,
      "Notification": false
    },
    {
      "Time": "2022-03-20T23:35:13.472776+01:00",
      "Group": "Device",
      "Message": "Initialized string in [...]

2022-03-20 22:44 UTC, InfinityGhost commented
> uses some built-in X11/libinput for the pointer device, but pressing aux buttons 

Regenerate the udev rules and install them, should resolve the oddities with libinput hooking into it.

2022-03-20 22:45 UTC, jamesbt365 commented
revert the changes on the tablets.MD or correct them, I've already proved they worked mine when I originally supported the tablet

2022-03-20 22:47 UTC, InfinityGhost requested changes

2022-03-20 22:47 UTC, InfinityGhost commented on TABLETS.md
> +| Huion 1060 Plus               |    Has Quirks     | User may have to press Aux buttons and replug their tablet until the pen properly works.
Should be resolved by installing the udev rules, therefore this should be reverted.

2022-03-20 22:58 UTC, WebFreak001 commented
the issues with xinput clashing are gone, but still seems like I need to hit aux buttons a few times, replug and restart otd (can't find a great reproducible way) to make it work, basically it doesn't work every time I restart otd

2022-03-20 23:03 UTC, jamesbt365 commented
Does the data change every time you press a button in the debugger, if so then its your system and not the tablet and therefore you can remove the change to the tablets.md

2022-03-20 23:05 UTC, WebFreak001 commented
the tablet isn't visible in the debugger until it gets properly connected (when everything works), pressing the aux buttons just seems to me to make the next reconnect more likely to work, but that could also just be my imagination

2022-03-20 23:07 UTC, jamesbt365 commented
tablet > device string reader, 9580 top box 110 in the middle box, dump all, do this a few times and compare the differences between them, there should be none however if there is constant changes then this tablet has a random sense of rng to it otherwise still seems like your system is not liking it

2022-03-20 23:12 UTC, WebFreak001 commented
"dump all" never seems to work (says "Please replug the tablet, and then press OK to continue" and pressing OK just makes it pop up again, no matter if I replugged or not)

I tried that before my changes with standard OpenTabletDriver as well where it didn't work just like this.

Also for the debugger in the broken state: OTD recognizes that the tablet is connected, but the GTK debugger doesn't show anything because it seems it only shows anything when I do any inputs with the tablet (which in the broken state happens neither with the pen nor with the aux buttons)

2022-03-20 23:14 UTC, jamesbt365 commented
export a diagnostic when your tablet isn't functioning correctly, i want to get this checked.

2022-03-20 23:16 UTC, WebFreak001 commented
diagnostic in broken state (full USB devices this time):

<details>

<summary>diagnostics broken</summary>

```json
{
  "App Version": "OpenTabletDriver v0.6.0.3+ad9d0f84",
  "Build Date": "3/20/2022",
  "Operating System": {
    "Platform": 4,
    "ServicePack": "",
    "Version": "5.16.13.1",
    "VersionString": "Unix 5.16.13.1"
  },
  "Environment Variables": {
    "USER": "webfreak",
    "TEMP": null,
    "TMP": null,
    "TMPDIR": null,
    "DISPLAY": ":0",
    "WAYLAND_DISPLAY": null,
    "PWD": "/home/webfreak/dev/OpenTabletDriver",
    "PATH": "/home/webfreak/.local/bin:/home/webfreak/.npm-packages/bin:/home/webfreak/etc-bin:/usr/share/dotnet/sdk/6.0.102/Sdks:/usr/share/dotnet:/home/webfreak/.local/bin:/home/webfreak/.npm-packages/bin:/home/webfreak/etc-bin:/usr/share/dotnet/sdk/6.0.102/Sdks:/usr/share/dotnet:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/android-sdk/emulator:/home/webfreak/.dotnet/tools:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/rocm-5.0.0/bin:/opt/rocm-5.0.0/hip/bin"
  },
  "HID Devices": [
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb3/3-3/3-3.1/3-3.1:1.1/0003:046D:C08F.0008/hidraw/hidraw7",
      "Manufacturer": "Logitech",
      "ProductName": "G403 HERO Gaming Mouse",
      "SerialNumber": "087D39783434",
      "FriendlyName": "G403 HERO Gaming Mouse",
      "VendorID": 1133,
      "ProductID": 49295,
      "InputReportLength": -1,
      "OutputReportLength": -1,
      "FeatureReportLength": -1,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-3/1-3:1.0/0003:28DE:1142.0001/hidraw/hidraw1",
      "Manufacturer": "Valve Software",
      "ProductName": "Steam Controller",
      "SerialNumber": "",
      "FriendlyName": "Steam Controller",
      "VendorID": 10462,
      "ProductID": 4418,
      "InputReportLength": 9,
      "OutputReportLength": 2,
      "FeatureReportLength": 0,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-3/1-3:1.1/0003:28DE:1142.0011/hidraw/hidraw2",
      "Manufacturer": "Valve Software",
      "ProductName": "Steam Controller",
      "SerialNumber": "",
      "FriendlyName": "Steam Controller",
      "VendorID": 10462,
      "ProductID": 4418,
      "InputReportLength": 65,
      "OutputReportLength": 65,
      "FeatureReportLength": 65,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-3/1-3:1.2/0003:28DE:1142.0012/hidraw/hidraw3",
      "Manufacturer": "Valve Software",
      "ProductName": "Steam Controller",
      "SerialNumber": "",
      "FriendlyName": "Steam Controller",
      "VendorID": 10462,
      "ProductID": 4418,
      "InputReportLength": 65,
      "OutputReportLength": 65,
      "FeatureReportLength": 65,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4.1/1-4.1:1.1/0003:256C:006E.0021/hidraw/hidraw11",
      "Manufacturer": "Unknown Manufacturer",
      "ProductName": "PenTablet ",
      "SerialNumber": "",
      "FriendlyName": "PenTablet ",
      "VendorID": 9580,
      "ProductID": 110,
      "InputReportLength": 8,
      "OutputReportLength": 0,
      "FeatureReportLength": 6,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4.1/1-4.1:1.0/0003:256C:006E.0020/hidraw/hidraw10",
      "Manufacturer": "Unknown Manufacturer",
      "ProductName": "PenTablet ",
      "SerialNumber": "",
      "FriendlyName": "PenTablet ",
      "VendorID": 9580,
      "ProductID": 110,
      "InputReportLength": 8,
      "OutputReportLength": 0,
      "FeatureReportLength": 0,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb3/3-3/3-3.4/3-3.4:1.0/0003:24F0:0140.0009/hidraw/hidraw8",
      "Manufacturer": "Metadot - Das Keyboard",
      "ProductName": "Das Keyboard",
      "SerialNumber": "",
      "FriendlyName": "Das Keyboard",
      "VendorID": 9456,
      "ProductID": 320,
      "InputReportLength": -1,
      "OutputReportLength": -1,
      "FeatureReportLength": -1,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-3/1-3:1.4/0003:28DE:1142.0014/hidraw/hidraw5",
      "Manufacturer": "Valve Software",
      "ProductName": "Steam Controller",
      "SerialNumber": "",
      "FriendlyName": "Steam Controller",
      "VendorID": 10462,
      "ProductID": 4418,
      "InputReportLength": 65,
      "OutputReportLength": 65,
      "FeatureReportLength": 65,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-3/1-3:1.3/0003:28DE:1142.0013/hidraw/hidraw4",
      "Manufacturer": "Valve Software",
      "ProductName": "Steam Controller",
      "SerialNumber": "",
      "FriendlyName": "Steam Controller",
      "VendorID": 10462,
      "ProductID": 4418,
      "InputReportLength": 65,
      "OutputReportLength": 65,
      "FeatureReportLength": 65,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4.1/1-4.1:1.2/0003:256C:006E.0022/hidraw/hidraw12",
      "Manufacturer": "Unknown Manufacturer",
      "ProductName": "PenTablet ",
      "SerialNumber": "",
      "FriendlyName": "PenTablet ",
      "VendorID": 9580,
      "ProductID": 110,
      "InputReportLength": 8,
      "OutputReportLength": 0,
      "FeatureReportLength": 0,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb3/3-4/3-4.3/3-4.3.1/3-4.3.1:1.1/0003:28DE:2300.000F/hidraw/hidraw14",
      "Manufacturer": "Valve",
      "ProductName": "Index HMD",
      "SerialNumber": "LHR-6E50B063",
      "FriendlyName": "Index HMD",
      "VendorID": 10462,
      "ProductID": 8960,
      "InputReportLength": 64,
      "OutputReportLength": 0,
      "FeatureReportLength": 0,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb3/3-3/3-3.4/3-3.4:1.1/0003:24F0:0140.000A/hidraw/hidraw9",
      "Manufacturer": "Metadot - Das Keyboard",
      "ProductName": "Das Keyboard",
      "SerialNumber": "",
      "FriendlyName": "Das Keyboard",
      "VendorID": 9456,
      "ProductID": 320,
      "InputReportLength": -1,
      "OutputReportLength": -1,
      "FeatureReportLength": -1,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb3/3-3/3-3.1/3-3.1:1.0/0003:046D:C08F.0007/hidraw/hidraw6",
      "Manufacturer": "Logitech",
      "ProductName": "G403 HERO Gaming Mouse",
      "SerialNumber": "087D39783434",
      "FriendlyName": "G403 HERO Gaming Mouse",
      "VendorID": 1133,
      "ProductID": 49295,
      "InputReportLength": -1,
      "OutputReportLength": -1,
      "FeatureReportLength": -1,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb3/3-4/3-4.3/3-4.3.1/3-4.3.1:1.2/0003:28DE:2300.0010/hidraw/hidraw15",
      "Manufacturer": "Valve",
      "ProductName": "Index HMD",
      "SerialNumber": "LHR-6E50B063",
      "FriendlyName": "Index HMD",
      "VendorID": 10462,
      "ProductID": 8960,
      "InputReportLength": 65,
      "OutputReportLength": 65,
      "FeatureReportLength": 65,
      "CanOpen": true
    },
    {
      "DevicePath": "/sys/devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb3/3-4/3-4.3/3-4.3.1/3-4.3.1:1.0/0003:28DE:2300.000E/hidraw/hidraw13",
      "Manufacturer": "Valve",
      "ProductName": "Index HMD",
      "SerialNumber": "LHR-6E50B063",
      "FriendlyName": "Index HMD",
      "VendorID": 10462,
      "ProductID": 8960,
      "InputReportLength": 52,
      "OutputReportLength": 64,
      "FeatureReportLength": 65,
      "CanOpen" [...]

2022-03-20 23:20 UTC, WebFreak001 commented
also tried this change out in a project called `osu` (Open Source Rhythm Game) where OpenTabletDriver is used as a dependency, there with the tablet being connected a warning/notification is shown with "Detect: More than 1 matching device has been found" which seems to come from OTD.

2022-03-20 23:34 UTC, InfinityGhost commented
> there with the tablet being connected a warning/notification is shown with "Detect: More than 1 matching device has been found" which seems to come from OTD

This warning happens because the detection in the configuration isn't precise enough, so it just grabs the first one in the list which can vary from system to system. As long as this warning is thrown, we won't accept the configuration.

2022-03-20 23:35 UTC, jamesbt365 commented
thats the problem here, specifically select one of the interfaces, 8 on the input 0 on the output

2022-03-20 23:36 UTC, WebFreak001 commented
there are 2 devices with 8 on input and 0 on output though, not sure if it's possible to differentiate here.

2022-03-20 23:37 UTC, jamesbt365 commented
Both can be opened, should be fine. Give it a test.

2022-03-20 23:38 UTC, WebFreak001 commented
with both I still had the random issues with it sometimes working and sometimes not, with the one with 8 InputReportLength and 6 FeatureReportLength I couldn't get the tablet to work at all so far, so that's probably one to avoid.

2022-03-20 23:41 UTC, WebFreak001 commented
the two 0 output length devices only differ in DevicePath:

```
/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4.1/1-4.1:1.0/0003:256C:006E.0032/hidraw/hidraw10
/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4.1/1-4.1:1.2/0003:256C:006E.0034/hidraw/hidraw19
```

not sure if those changing values after 0003:256C:006E (32 and 34) are system dependent or if I can somehow match on those though.

2022-04-05 20:08 UTC, X9VoiD commented
Remaining issue is an OTD limitation, will merge as is.

2022-04-05 20:08 UTC, merged