Restrict file extension
OpenTabletDriver/OpenTabletDriver pull request #2150
Opened 2022-04-01 14:56 UTC by satodayo

It is my first contribution.
Please let me know if this PR is not good.
Thank you.

2022-04-01 14:57 UTC, satodayo commented
for #2146

2022-04-01 15:01 UTC, jamesbt365 commented
If a file extension that isn't provided nothing saves, however .txt and .json do save as intended. Tested on linux.

2022-04-01 15:12 UTC, satodayo commented
Thank you for feedback.
I misunderstand, I will fix it.

2022-04-01 15:35 UTC, satodayo commented
Resolve #2146

2022-04-01 16:37 UTC, vedattt commented
Regular expressions are way way overkill for the task here. Since file extensions, if they exist, are always at the end of `fileDialog.FileName`, opt for a simpler algorithm using [`String.EndsWidth`](https://docs.microsoft.com/en-us/dotnet/api/system.string.endswith?view=net-6.0). See [here](https://github.com/OpenTabletDriver/OpenTabletDriver/pull/1798/files) for a similar PR from earlier.

Also, if Discord is able to display JSON files as well as TXT files, I'd say forget about checking against `.txt` altogether since the diagnostics being exported are in fact JSON, for the time being.

2022-04-01 16:46 UTC, vedattt commented
Apparently Discord plays well, but GitHub issues don't let you upload JSONs. In that case, I think we should enforce `.json` by default, but also allow saving as either `.log` or `.txt`, both of which work fine with Discord and GitHub.

2022-04-01 18:14 UTC, gonX commented
> Regular expressions are way way overkill for the task here. Since file extensions, if they exist, are always at the end of fileDialog.FileName, opt for a simpler algorithm using [String.EndsWidth](https://docs.microsoft.com/en-us/dotnet/api/system.string.endswith?view=net-6.0). See [here](https://github.com/OpenTabletDriver/OpenTabletDriver/pull/1798/files) for a similar PR from earlier.

I agree with this. For readability this could even be done with Linq:
```cs
String fileName = "blabla.txt";
String[] options = { ".json", ".txt", ".log" };
bool result = options.Any(fileName.EndsWith);
```

2022-04-01 18:15 UTC, gonX requested changes
Change from Regex to [String.EndsWith](https://docs.microsoft.com/en-us/dotnet/api/system.string.endswith?view=net-6.0)

2022-04-01 22:43 UTC, satodayo commented
@vedattt @gonX 
Thank you for your feedback!
I guess regex is overkill as well.

Please let me check a little.
If file extension is not any, I guess I can't detect with only string.EndsWitdh.
So I guess I need to handle that filename case.
If then, should I add ".json" for filename?  or save as it is ? or unsave?

2022-04-01 22:47 UTC, satodayo commented on OpenTabletDriver.UX/MainForm.cs
> +                        var file = new FileInfo(filename);
Currently
```suggestion
                        String fileName = fileDialog.FileName;
                        String[] options = { ".json", ".txt", ".log" };
                        if (!options.Any(fileName.EndsWith))
                            return;

                        var file = new FileInfo(fileName);
```

2022-04-01 22:52 UTC, vedattt commented
If the given filename ends with json/log/txt, it is saved as it is. In any other case, the file is saved as `filename + ".json"`.

So you could just grab gonX's example using `Any(endsWith)` to test whether you save it is as is, or save it with `.json` appended. That should cover all cases.

You could probably reduce the code down to a single line or two as well, going this way.

2022-04-01 23:04 UTC, satodayo commented
That make sense.
I was thinking too compricated, thank you.
I will fix it, please give me some time...

2022-04-02 14:05 UTC, satodayo commented
Because I pushed a lot of unnecessary commit, I will re-contribute with new branch.
I am sorry for my many mistake.

2022-04-02 14:06 UTC, jamesbt365 commented
you don't have to do that, just squash commits.

2022-04-02 15:14 UTC, satodayo commented
@jamesbt365 
Thank you so much.
I didn't know anything..., I squashed commits.
I am sorry for the trouble.

2022-04-02 15:17 UTC, jamesbt365 commented
no worries, will test and review in a bit

2022-04-02 15:26 UTC, jamesbt365 approved these changes

2022-04-02 15:26 UTC, jamesbt365 commented
Works correctly.

2022-04-02 18:47 UTC, vedattt requested changes
Super minor thing left

2022-04-02 18:47 UTC, vedattt commented on OpenTabletDriver.UX/MainForm.cs
> +                        String[] options = { ".json", ".txt", ".log" };
```suggestion
                        string[] options = { ".json", ".txt", ".log" };
```
Sorry, our example snippet made this "mistake" as well, but C# code style tends to prefer using the alias `string` over the class `String`. They both compile down to the same thing, so it's just cosmetic consistency. You can fix this and squash it once again. Looks good to merge otherwise.

2022-04-02 18:54 UTC, vedattt commented on OpenTabletDriver.UX/MainForm.cs
> +                        String[] options = { ".json", ".txt", ".log" };
P.S., you could go a step further by making it a `const` variable at the top of the method.

2022-04-02 21:24 UTC, satodayo commented on OpenTabletDriver.UX/MainForm.cs
> +                        String[] options = { ".json", ".txt", ".log" };
@vedattt 
Thank you for review.
I fixed it.

2022-04-02 21:28 UTC, gonX approved these changes

2022-04-06 16:30 UTC, jamesbt365 approved these changes

2022-04-13 16:04 UTC, InfinityGhost approved these changes

2022-04-13 16:04 UTC, merged