Add serial/legacy tablet backend
OpenTabletDriver/OpenTabletDriver pull request #2215
Opened 2022-04-25 01:19 UTC by adryzz

- [x] Add device streams and endpoints
- [ ] Figure out configs
- [ ] Figure out UI
- [ ] Figure out the extra bugs with this
- [ ] Figure out auto-detection of tablet
- [ ] Figure out report parser
- [ ] Useless extra dopamine releasing checkbox

2022-05-10 19:00 UTC, Sublimelime requested changes

2022-05-10 19:00 UTC, Sublimelime commented on OpenTabletDriver/Devices/SerialBackend/SerialInterface.cs
> +        public int FeatureReportLength => 0; // requires parsing report descriptor to determine feature report length
Convert to xmldoc instead of inline comment

2022-05-10 19:02 UTC, adryzz commented on OpenTabletDriver.UX/Windows/Tablet/LegacyTabletConnectionWindow.cs
> +                Spacing = 5,
they are exactly like this in other classes
for example this
https://github.com/OpenTabletDriver/OpenTabletDriver/blob/4f06b708ccc7109e39bd029fcb47f0df3efe992a/OpenTabletDriver.UX/Windows/DeviceStringReader.cs#L65

2022-05-10 19:11 UTC, InfinityGhost commented
Marking as draft as this is still incomplete

2022-05-10 19:12 UTC, InfinityGhost commented on OpenTabletDriver.UX/Windows/Tablet/LegacyTabletConnectionWindow.cs
> +                Spacing = 5,
It's fine to leave this non-constant.

2022-05-10 19:13 UTC, InfinityGhost requested changes

2022-05-10 19:13 UTC, InfinityGhost commented on OpenTabletDriver/Devices/SerialBackend/SerialDeviceHub.cs
> +        public SerialDevoceHub()
Typo in constructor
```suggestion
        public SerialDeviceHub()
```

2022-10-04 19:39 UTC, adryzz commented
rebased everything, now it's time to fix all the issues and it should work... took 5 hours to rebase...

2022-10-04 19:42 UTC, closed without merging