Add Veikk A30 V2
OpenTabletDriver/OpenTabletDriver pull request #2216
Opened 2022-04-25 15:34 UTC by SnowLire

Still waiting on the guy who asked for support to come back and test it, although I suspect it's the same as the Veikk S640 V2 and only needed a parser change.

Conversation: https://discord.com/channels/615607687467761684/615611007951306863/965638577394425926

2022-05-03 19:43 UTC, InfinityGhost commented
Untested configurations will not be merged. Marking as draft until this is verified.

2022-05-19 19:56 UTC, jamesbt365 commented
Any reason this isn't in the same Configuration as the A30? There's no conflict between them.

2022-05-20 08:47 UTC, X9VoiD requested changes

2022-05-20 08:47 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/VEIKK/A30 V2.json
> +    }
Move inside `VEIKK A30` configuration as this has similar specifications to that.

2022-05-22 12:51 UTC, SnowLire commented on OpenTabletDriver.Configurations/Configurations/VEIKK/A30 V2.json
> +    }
Did it this way to stay consistent with the Veikk S640 and S640 V2 being 2 different configs despite having only the `InputReportLength` changed.

2022-05-22 13:07 UTC, Kuuuube commented on OpenTabletDriver.Configurations/Configurations/VEIKK/A30 V2.json
> +    }
The Veikk A30 V2 and Veikk A30 are both product names and how the tablets are referred to by Veikk. They should not be combined.

2022-05-22 13:07 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/VEIKK/A30 V2.json
> +    }
https://discord.com/channels/615607687467761684/628651971267788800/977920269509357641

2022-05-22 13:12 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/VEIKK/A30 V2.json
> +    }
Aight, will mark as resolved.

2022-05-22 13:14 UTC, X9VoiD approved these changes

2022-05-22 13:15 UTC, X9VoiD approved these changes

2022-05-22 13:15 UTC, jamesbt365 approved these changes

2022-05-22 13:15 UTC, jamesbt365 approved these changes

2022-05-22 13:16 UTC, jamesbt365 approved these changes

2022-05-24 15:07 UTC, jamesbt365 requested changes

2022-05-24 15:08 UTC, jamesbt365 commented
Verification: https://discord.com/channels/615607687467761684/615611007951306863/978675579551363123

2022-05-24 15:27 UTC, jamesbt365 commented
hold off, some aux fuckery

2022-05-26 11:05 UTC, SnowLire commented on TABLETS.md
> +| Veikk A30 V2                  |     Untested      |
Resolved

2022-05-26 11:35 UTC, jamesbt365 approved these changes

2022-05-27 22:33 UTC, merged