Add support for DTK-1300 aka Cintiq 13HD
OpenTabletDriver/OpenTabletDriver pull request #2241
Opened 2022-05-10 20:13 UTC by OniCado

Digitizer works fine with IntuosV1ReportParser, only missing functionality is the 9th button (which is also non functional on Intuos4/5 tablets)

2022-05-10 20:14 UTC, jamesbt365 approved these changes

2022-05-27 22:39 UTC, X9VoiD requested changes

2022-05-27 22:39 UTC, X9VoiD commented on TABLETS.md
> +| Wacom DTK-1300                |  Missing Features | Wheel center button is not yet supported.
```suggestion
| Wacom DTK-1300                |  Missing Features | Wheel is not yet supported.
```

2022-05-27 22:39 UTC, jamesbt365 commented
This tablet has no wheel, it has buttons shaped like a wheel.

2022-05-27 22:49 UTC, merged