Add eraser support for intuos1
OpenTabletDriver/OpenTabletDriver pull request #2260
Opened 2022-05-22 02:20 UTC by Kuuuube

2022-05-22 06:20 UTC, AbstractQbit requested changes

2022-05-22 06:20 UTC, AbstractQbit commented on OpenTabletDriver.Configurations/Parsers/Wacom/Intuos1/Intuos1ReportParser.cs
> +        public static byte ToolStore;
Using statics in report parsers can potentially mess with multi tablet support, see #1665. Just make it a regular member and pass it to report constructor instead

2022-05-22 13:22 UTC, jamesbt365 approved these changes

2022-06-12 04:06 UTC, gonX commented
What happens to the V1 parser from here?

2022-11-07 22:30 UTC, X9VoiD requested changes
Is there no more users of IntuosV1? Should delete it if there's none since Intuos1 is directly compatible with V1 (i hate the parser name scheme we have if there even is one lol).

2022-11-07 22:30 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Parsers/Wacom/Intuos1/Intuos1ToolReport.cs
> +    public struct Intuos1ToolReport : IToolReport, IEraserReport, IProximityReport
Consider removing `IEraserReport` here and `Eraser` so eraser event and position is parsed at the same time frame? This doesn't really matter much so feel free to ignore.

2022-11-07 22:43 UTC, gonX commented on OpenTabletDriver.Configurations/Parsers/Wacom/Intuos1/Intuos1ToolReport.cs
> +    public struct Intuos1ToolReport : IToolReport, IEraserReport, IProximityReport
It's probably a good idea to address this, as `IToolReport`s are not yet implemented and could potentially end up being reported differently from `IEraserReport`s (as `IEraserReport`s are usually a part of a position report, not a tool report).

Should that not be the case then the change will do nothing on that front, but still implies intent better than what the PR proposes.

2022-11-07 23:50 UTC, Kuuuube commented on OpenTabletDriver.Configurations/Parsers/Wacom/Intuos1/Intuos1ToolReport.cs
> +    public struct Intuos1ToolReport : IToolReport, IEraserReport, IProximityReport
It is not possible to parse eraser and position at the same time. They are never sent together.

The tablet sends one report containing the tool data only when the tool changes or goes from out of range to in range. The tool data contained in the tool report is valid for all reports after the tool report, until another tool report is received.

It may seem worth actually using `ToolType.Eraser` or `ToolType.Pen` for this but I don't want to do that since this should be arbitrarily expandable and allow checking for more than eraser or pen tip. Though not supported in OTD yet, this tablet also supports mice and some other pens which may need special handling. The tool reports for those are reported over the same byte.

2022-11-07 23:54 UTC, Kuuuube commented
> Is there no more users of IntuosV1? Should delete it if there's none since Intuos1 is directly compatible with V1 (i hate the parser name scheme we have if there even is one lol).

No there are still many tablets that use it. Some Wacom tablets should be split off similar to this PR but even then there's some other tablets that use it.

2022-12-26 20:57 UTC, X9VoiD commented
Superseded by #2260

2022-12-26 20:57 UTC, closed without merging