Add another identifier to Huion HXXXP
OpenTabletDriver/OpenTabletDriver pull request #2264
Opened 2022-05-24 15:58 UTC by jamesbt365

H1060P: https://discord.com/channels/615607687467761684/615611007951306863/978687494814056489
H640P: #2265

2022-05-26 15:22 UTC, jamesbt365 commented
Whats the bet that the h430p needs another one as well? :tf:

2022-05-27 22:57 UTC, X9VoiD requested changes

2022-05-27 22:57 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/Huion/H640P.json
> +      "ProductID": 100,
Are you sure about `100`? Not `110`?

2022-05-27 23:01 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/Huion/H640P.json
> +      "ProductID": 100,
Yes, check #2265 for the H640P. Should of made that clear in my message (sorry). Some huions now use 100 as the pid for no reason though

2022-05-27 23:03 UTC, merged