Add variant of UGTABLET M708
OpenTabletDriver/OpenTabletDriver pull request #2268
Opened 2022-05-26 20:56 UTC by jamesbt365

Verification: https://discord.com/channels/615607687467761684/979472667260354571/979484050681131069

This tablet did alot of jank so look here and here maybe?
 https://discord.com/channels/615607687467761684/979472667260354571/979477598000255017
https://discord.com/channels/615607687467761684/979472667260354571/979479952137289748

2022-05-27 22:54 UTC, X9VoiD requested changes

2022-05-27 22:54 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/UGTABLET/M708 V2.json
> +      ]
Are you sure that it requires three inits of two different kinds?

2022-05-27 22:55 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/UGTABLET/M708 V2.json
> +      ]
Never actually tried removing them to find out, will try and get back in touch with the person that has this tablet.

2022-07-17 14:04 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/UGTABLET/M708 V2.json
> +      ]
They do not. https://discord.com/channels/615607687467761684/615611007951306863/998228153531109448

2022-07-17 19:21 UTC, merged