Add arm64 building on github actions
OpenTabletDriver/OpenTabletDriver pull request #2270
Opened 2022-05-26 23:18 UTC by jamesbt365

Adds arm64 builds to github actions.

TODO:

- [ ] Figure out if these builds actually work (knowing me they don't)
- [ ] Add for releases as well as just actions

Packaging repo also needs doing :P

2022-05-26 23:21 UTC, InfinityGhost requested changes
Since we're targeting multiple platforms now, we should include the architectures in the workflow names as well, so update the old ones to include the architectures.

2022-05-26 23:21 UTC, InfinityGhost commented on .github/workflows/dotnet.yml
> +      - name: Windows arm Publish
```suggestion
      - name: Windows ARM64 Publish
```

2022-05-26 23:33 UTC, jamesbt365 commented
> Since we're targeting multiple platforms now, we should include the architectures in the workflow names as well, so update the old ones to include the architectures.

Should the path it builds to also be changed to x86_64 from x64 if we are going this route?

2022-07-02 22:14 UTC, jamesbt365 commented
Eto likely needs to be bumped for native arm builds to work on macos. #2336

2022-09-05 19:18 UTC, jamesbt365 commented
Probably best to rip out macos arm for now because it requires something we cannot supply rn and has to be built and signed on macos

2023-08-27 17:41 UTC, jamesbt365 commented
Lots has changed since this pull request was opened. Not sure if we really "need" x86 builds anymore due to dotnet 7 phasing out Windows 7 and 8 support. Handling arm MacOS builds requires signing on MacOS for it to work so in reality it seems only really arm windows (which hardly anybody uses) and arm linux exist to implement if we are still interested in doing something like that.

2023-08-27 17:41 UTC, closed without merging