Add native notifactions when the fallback timer is used on Windows.
OpenTabletDriver/OpenTabletDriver pull request #2272
Opened 2022-05-28 13:40 UTC by jamesbt365

Is this how you do it :voidvoid:

2022-05-28 18:22 UTC, jamesbt365 commented
![image](https://user-images.githubusercontent.com/22662856/170838206-4da2141a-1568-4bfe-9473-55bf6c8f1301.png)

2022-05-28 18:48 UTC, vedattt commented
> won't go through if the user has notifications from otd off

Does the notification get logged to at least the OTD console in this case?
So long as there is *some* indicator out there, I think that's enough. User is responsible beyond that point if they've disabled OTD notifications.

2022-05-28 18:49 UTC, jamesbt365 commented
Its still logged, just the notification won't appear.

2022-11-21 21:17 UTC, jamesbt365 commented
Rebased. No clue if it still works but i'm gonna assume it does because why wouldn't it.

2022-11-22 13:15 UTC, InfinityGhost requested changes

2022-11-22 13:15 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Interop/Timer/WindowsTimer.cs
> +                        Log.WriteNotify("Timer", "Unsupported interval detected, will use fallback timer. Expect high CPU usage", LogLevel.Warning);
What interval? This should be a bit more specific for the user to know what to change.

2022-12-25 23:02 UTC, jamesbt365 commented on OpenTabletDriver.Desktop/Interop/Timer/WindowsTimer.cs
> +                        Log.WriteNotify("Timer", "Unsupported interval detected, will use fallback timer. Expect high CPU usage", LogLevel.Warning);
Fixed.

2022-12-25 23:05 UTC, merged