Switch to GitHub issue forms
OpenTabletDriver/OpenTabletDriver pull request #2279
Opened 2022-06-01 11:05 UTC by vedattt

## Changes

- Convert all existing Markdown issue templates to GitHub issue forms
- Add diagnostics export field to bug reports and remove redundant fields

All diagnostics exports across the forms are currently set to be required.
We could relax that requirement if needed?

## Issues

- Closes #2277

2022-06-01 11:50 UTC, X9VoiD requested changes

2022-06-01 11:50 UTC, X9VoiD commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +          required: true
Probably change to `Acknowledgements` and do these required questions instead:
- I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another.
- I have written a short but informative title.
- I have checked [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and my issue is not covered in there or did not fix my issue.

Description should probably be like: `Read this carefully, we will close and ignore your issue if you skimmed through this.`

Do the same for all other templates. So yeah, convert feature request too into this then you may omit the third acknowledgement.

2022-06-01 11:50 UTC, X9VoiD commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      required: true
Probably do the standard `Reproduction steps`, `Expected behaviour`, `Actual behaviour` instead of just one singular "Description" field.

```suggestion
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue. Pictures, videos, or gifs that showcase the issue are welcome.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you should expect to happen.
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Explain what actually happens.
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true
```

2022-06-01 11:50 UTC, X9VoiD commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: Export diagnostics and attach or paste below. In the GUI, click Help -> Export Diagnostics.
```suggestion
      description: Export diagnostics by doing OTD -> Help -> Export Diagnostics then attach the file here (as `.txt` if Github doesn't allow you to upload it) or paste contents below.
```

2022-06-02 20:10 UTC, vedattt reviewed
Need to fix:

- Text areas with property `render` set cannot have files attached
- Link to "installation instructions"

2022-06-07 20:14 UTC, InfinityGhost requested changes
lg2m for the most part

2022-06-07 20:14 UTC, InfinityGhost commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://discord.gg/9bcMaPkVAR
Ideally would point to https://opentabletdriver.net/Discord so that it always uses our primary link, even though this just redirects to that.
```suggestion
    url: https://opentabletdriver.net/Discord
```

2022-06-08 01:50 UTC, InfinityGhost commented on .github/ISSUE_TEMPLATE/support_request.yml
> +        (Notice the triple backticks)
Should match the bug report diagnostic yml here

2022-06-08 02:04 UTC, InfinityGhost approved these changes

2022-06-08 02:08 UTC, merged