Fixed german translation of README.md
OpenTabletDriver/OpenTabletDriver pull request #2295
Opened 2022-06-05 22:21 UTC by Julian-Sz

Fixed many typos etc

2022-06-05 22:35 UTC, X9VoiD requested changes

2022-06-05 22:35 UTC, X9VoiD commented on docs/README_DE.md
> +OpenTabletDriver ist ein plattformübergreifender Open Source Benutzermodustreiber für Grafiktabletts. Das Ziel von OpenTabletDriver ist es, so Cross-Plattform wie möglich zu sein, mit der höchsten Ko
```suggestion
OpenTabletDriver ist ein plattformübergreifender Open Source Benutzermodustreiber für Grafiktabletts. Das Ziel von OpenTabletDriver ist es, so Cross-Platform wie möglich zu sein, mit der höchsten Kompatibilität und mit einer einfach zu konfigurierenden grafischen Benutzeroberfläche.
```

2022-06-05 22:37 UTC, X9VoiD approved these changes

2022-06-06 06:20 UTC, C0D3-M4513R commented
I'd either remove or finish the last sentence. Not a blocker in my eyes though.
This pr greatly improves readability (something that was severely lacking in #1777 ).

2022-06-06 06:21 UTC, C0D3-M4513R approved these changes

2022-06-06 06:27 UTC, C0D3-M4513R commented
wWe should add localization and documentation tags

2022-06-20 19:37 UTC, InfinityGhost commented
Is this good to go?

2022-06-20 19:59 UTC, Julian-Sz commented
Yes, ready to merge

2022-12-25 23:08 UTC, jamesbt365 commented
somebody merge this lmao

2022-12-25 23:09 UTC, merged