Label on pull request creation
OpenTabletDriver/OpenTabletDriver pull request #2335
Opened 2022-07-01 15:31 UTC by jamesbt365

2022-07-01 16:21 UTC, vedattt requested changes

2022-07-01 16:21 UTC, vedattt commented on .github/ISSUE_TEMPLATE/tablet_configuration.yml
> +labels: ["configuration", "need-triage"]
```suggestion
labels: ["configuration", "needs-triage"]
```

2022-07-01 16:21 UTC, vedattt commented on .github/ISSUE_TEMPLATE/support_request.yml
> +labels: ["support request", "need-triage"]
```suggestion
labels: ["support request", "needs-triage"]
```

2022-07-01 21:10 UTC, vedattt commented
The only reason we've found that justifies having a `needs-triage` label over filtering by unlabeled issues is that our issue forms already auto label upon opening. In other words, there are almost* no issues that are ever completely unlabeled, hence the need for a way to distinguish.

*: Blank issues aren't labeled at all, but they're on the rare side being mostly used for non-user-facing meta topics.

2022-07-01 21:12 UTC, jamesbt365 commented
All issues and pull requests opened will have the needs-triage label so that somebody can label them correctly so things are easier to sort though later

2022-07-01 21:26 UTC, vedattt requested changes

2022-07-01 21:26 UTC, vedattt commented on .github/labeler.yml
> +  - '*'
```suggestion
needs-triage:
  - '.*'
```
`*` is not valid regex, as it attempts to quantify a token that doesn't exist. If issue-labeler somehow interprets '*' as a glob pattern then perhaps it's still functional and this could be ignored.

Otherwise, to match everything we should use either `.*` or an empty regex. Both seem to result in a match for any string in JS, which I believe is the flavor of regex that applies to GitHub Actions.

2022-07-01 21:30 UTC, jamesbt365 commented on .github/labeler.yml
> +  - '*'
oops

2022-08-22 23:46 UTC, InfinityGhost approved these changes

2022-08-22 23:46 UTC, merged