Add more user guidance to build.sh and generate-rules.sh
OpenTabletDriver/OpenTabletDriver pull request #2403
Opened 2022-08-26 18:29 UTC by Sublimelime

Small PR that adds some more guidance to people using build.sh and generate-rules.sh to build and run OTD from source. Notably,

- Build.sh now checks for udev rules in the typical `/etc/udev/rules.d/` directory, and if not found, warns the user that they need to also run generate-rules.sh.
- Generate-rules.sh now explains what to do with the generated rules file.
- (added this in as a bonus) build.sh now spams less text while building, via providing the --verbosity=quiet tag. `dotnet publish` will still output errors (if any) just fine, but it won't spam individual files being built. 

The only thing unaddressed is running the binaries themselves, but I don't think that this is necessary - the script explains where the binaries are created by build.sh, and they're named obviously. You run `OpenTabletDriver.Daemon` for the daemon, etc. 

If the user wants automated running of OTD (and isn't planning on installing a package to have the service), they should set that up via their DE's startup system, potentially creating .desktop files pointing at the created binaries. Alternatively we could provide some pre-made .desktop files for the user to edit and move where they're supposed to go for their DE.

If they want to start OTD for dev work, a simple `./bin/OpenTabletDriver.Daemon` from the root folder works. No need for a dedicated run script.

2022-08-26 18:32 UTC, jamesbt365 commented on build.sh
> +if [ ! -f /etc/udev/rules.d/99-opentabletdriver.rules ]; then
Check /usr/lib/udev/rules.d as well as this is also a place the rules could be.

2022-08-26 19:32 UTC, X9VoiD requested changes
Do the same verbosity change on build.ps1 for consistency.

2022-08-26 20:39 UTC, gonX requested changes

2022-08-26 20:39 UTC, gonX commented on build.sh
> +if [ ! -f /etc/udev/rules.d/99-opentabletdriver.rules ] && [ ! -f /usr/lib/udev/rules.d/99-opentabletdriver.rules ]; then
I don't like this check, we should check if `/dev/uinput` can be opened, or a similar reliable check. Also check if we're being run as root, probably.
If you really wanna check for files I suggest also looking in `/usr/share/udev/` and checking for `*-opentabletdriver.rules` instead

2022-08-26 21:04 UTC, Sublimelime commented on build.sh
> +if [ ! -f /etc/udev/rules.d/99-opentabletdriver.rules ] && [ ! -f /usr/lib/udev/rules.d/99-opentabletdriver.rules ]; then
>I don't like this check, we should check if /dev/uinput can be opened, or a similar reliable check. 

Doesn't this have to be done by the driver not by the build script? If I understand correctly...

>Also check if we're being run as root, probably.

We have no reason to be run as root, nor do anything with root. This is just a compilation script, and this PR is just to add info and guidance not functionality.

>If you really wanna check for files I suggest also looking in /usr/share/udev/ and checking for *-opentabletdriver.rules instead

I can add that directory too, but checking for * like that isn't necessary - we have it hardcoded to make 99-opentabletdriver.rules.

2022-08-27 03:23 UTC, gonX commented on build.sh
> +if [ ! -f /etc/udev/rules.d/99-opentabletdriver.rules ] && [ ! -f /usr/lib/udev/rules.d/99-opentabletdriver.rules ]; then
I've seen `90-opentabletdriver.rules` before. It's not necessary to assume that much about the users environment, maybe use `??-opentabletdriver.rules`? This should match anything that we'd be interested in - I don't think numbers higher than 99 are supported in this regard (since 100 would sort before 11).

> We have no reason to be run as root, nor do anything with root. This is just a compilation script, and this PR is just to add info and guidance not functionality.

This was mostly in relation if you wanted to go through with the `/dev/uinput` check. The check is pointless if its run as root, but @X9VoiD brought up a good point [on Discord](https://discord.com/channels/615607687467761684/628651971267788800/1012841999763767407) in regards to that we should also really be checking if tablet endpoints are accessible, but IMO at that point the complexity is probably too much.

So leaving it with a file check is fine.

2022-08-27 03:24 UTC, gonX approved these changes

2022-08-27 17:19 UTC, X9VoiD approved these changes

2022-09-08 02:08 UTC, InfinityGhost approved these changes

2022-09-08 02:09 UTC, merged