Update configs
OpenTabletDriver/OpenTabletDriver pull request #2419
Opened 2022-09-03 19:53 UTC by X9VoiD

And also lint the config files using `jq`.

2022-09-03 23:44 UTC, gonX approved these changes
We should probably add `jq` as a linting step - making an issue

2022-09-03 23:53 UTC, Sublimelime approved these changes
LGTM Except for some minor grammar things in Tablets.md.

2022-09-03 23:53 UTC, Sublimelime commented on TABLETS.md
> +| Gaomon S830                   |     Supported     | User may need to re-plug their tablet multiple time for it to be detected
```suggestion
| Gaomon S830                   |     Supported     | User may need to re-plug their tablet multiple times for it to be detected
```

2022-09-03 23:53 UTC, Sublimelime commented on TABLETS.md
> +| Genius i608x                  |     Supported     | Windows: Require Zadig's WinUSB
Interface? Also Require -> Requires

2022-09-03 23:53 UTC, Sublimelime commented on TABLETS.md
> +| KENTING K5540                 |     Supported     | Windows: Requires Zadig's WinUSB
Interface?

2022-09-03 23:53 UTC, Sublimelime commented on TABLETS.md
> +| Veikk A30 V2                  |  Missing Features | Touchpad is not yet supported.
```suggestion
| VEIKK A30 V2                  |  Missing Features | Touchpad is not yet supported.
```

2022-09-03 23:55 UTC, jamesbt365 commented on TABLETS.md
> +| KENTING K5540                 |     Supported     | Windows: Requires Zadig's WinUSB
Its a singular interface device.

2022-09-03 23:56 UTC, jamesbt365 commented on TABLETS.md
> +| Genius i608x                  |     Supported     | Windows: Require Zadig's WinUSB
Singular interface devices

2022-09-03 23:57 UTC, jamesbt365 commented on TABLETS.md
> +| Veikk A30 V2                  |  Missing Features | Touchpad is not yet supported.
Blame snowlire

2022-09-04 15:56 UTC, InfinityGhost requested changes
~~Multiple configurations have final newlines and extra whitespace.~~ Forgot to pull lmao

2022-09-04 15:56 UTC, InfinityGhost commented on TABLETS.md
> +| Genius i608x                  |     Supported     | Windows: Require Zadig's WinUSB
```suggestion
| Genius i405x                  |     Supported     | Windows: Requires Zadig's WinUSB
| Genius i608x                  |     Supported     | Windows: Requires Zadig's WinUSB
```

2022-09-05 02:58 UTC, InfinityGhost approved these changes

2022-09-05 02:58 UTC, merged