Add support for XP-PEN Artist Pro 16TP
OpenTabletDriver/OpenTabletDriver pull request #2430
Opened 2022-09-22 17:50 UTC by jamesbt365

Verification: https://discord.com/channels/615607687467761684/645408221322018837/1022501703259537499

2022-09-24 14:07 UTC, InfinityGhost requested changes

2022-09-24 14:07 UTC, InfinityGhost commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist Pro 16TP.json
> +          ],
Fix formatting

2022-11-04 17:29 UTC, merged

2022-12-19 00:35 UTC, MathisP75 commented
Is this supposed to be working now? It won't detect my 16 TP

2022-12-19 01:18 UTC, jamesbt365 commented
>Is this supposed to be working now? It won't detect my 16 TP.

as in the latest version? No as its not in the latest version yet.

>Edit: It seems like it the commit has been reverted or something? Was it problematic?

No it wasn't. I'm assuming you are looking at master. This commit is currently only in `configs`.