EvdevVirtualTablet: Code cleanup
OpenTabletDriver/OpenTabletDriver pull request #2507
Opened 2022-11-19 17:00 UTC by gonX

Less lines = more good

The array ordering has been carefully chosen to make sure that events are reset in the following order: tools -> touch -> buttons

This supersedes ce6b876d13142d82af8ad1981499f4fe256a8efe from #1984

(please test, the changes were simply rebased to the current codebase)

2022-11-19 17:55 UTC, X9VoiD requested changes

2022-11-19 17:55 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/EvdevVirtualTablet.cs
> +        private readonly EventCode[] eventCodes =
```suggestion
        private static readonly EventCode[] eventCodes =
```

2022-11-21 21:40 UTC, X9VoiD approved these changes

2022-11-22 16:00 UTC, InfinityGhost approved these changes

2022-11-22 16:00 UTC, merged