Add support for Wacom Bamboo Pad USB CTH-301 tablets
OpenTabletDriver/OpenTabletDriver pull request #2545
Opened 2022-12-19 23:20 UTC by aomsin2526

This thing is different from any other wacom tablets, so new parser is needed. Pen, eraser, pen and aux button works. No touch support yet.

2022-12-19 23:21 UTC, jamesbt365 commented
closes #2312

2022-12-19 23:25 UTC, 32-bit-link commented
Thank you aom sin for this magnificent pull request 🙏

2022-12-20 09:18 UTC, X9VoiD requested changes

2022-12-20 09:18 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Parsers/Wacom/BambooPad/BambooPadAuxReport.cs
> +                report[23] == 2
This prevents it from sending both buttons as active. Is it not possible for the hardware to send both?

```suggestion
                report[23].IsBitSet(0),
                report[23].IsBitSet(1)
```

2022-12-20 11:32 UTC, aomsin2526 commented on OpenTabletDriver.Configurations/Parsers/Wacom/BambooPad/BambooPadAuxReport.cs
> +                report[23] == 2
As far as i tested, This value is only returns 1 or 2, It is not possible to click both buttons as same time even on official drivers. It is also prioritize right button.

2022-12-20 11:47 UTC, aomsin2526 commented on OpenTabletDriver.Configurations/Parsers/Wacom/BambooPad/BambooPadAuxReport.cs
> +                report[23] == 2
After another test i found problem related to long press, maybe i will try improve it later.

2022-12-20 18:15 UTC, X9VoiD approved these changes

2022-12-20 18:15 UTC, merged