Potential tilt support for Veikk tablets.
OpenTabletDriver/OpenTabletDriver pull request #2632
Opened 2023-02-05 01:28 UTC by brkeejp

Tested on Veikk vk640 graphic tablet.

2023-02-05 04:24 UTC, X9VoiD requested changes
Keep this report parser unchanged and then do this on another parser. I suggest `VeikkTiltReportParser`. Tablets that rely on `Veikk(V2)ReportParser` but reports less than 13 bytes would have thrown `ArgumentOutOfRangeException`.

2023-02-05 21:06 UTC, brkeejp commented
Like you mentioned I created new parser, changed vk640's config file to use new parser for it.

2023-02-05 21:45 UTC, X9VoiD requested changes

2023-02-05 21:45 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Parsers/Veikk/VeikkTiltedTabletReport.cs
> +                Y = unchecked((sbyte)report[12])
I don't think unchecked is needed here as this is a same-length cast.
```suggestion
                X = (sbyte)report[11],
                Y = (sbyte)report[12]

```

2023-02-05 21:45 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Parsers/Veikk/VeikkTiltedReportParser.cs
> +            return new DeviceReport(report);
No need to comment them like this, it adds no value to the code as it already reads the same as the comment.

Also no need to manually throw an argument out of range exception as well.

2023-02-05 21:45 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Parsers/Veikk/VeikkTiltedReportParser.cs
> +    public class VeikkTiltedReportParser : IReportParser<IDeviceReport>
Change class name to `VeikkTiltReportParser` to match current convention.

2023-02-05 22:15 UTC, brkeejp commented on OpenTabletDriver.Configurations/Parsers/Veikk/VeikkTiltedTabletReport.cs
> +                Y = unchecked((sbyte)report[12])
well actually it's effects how it's works. if i remove unchecked it will throw error.
`Constant value '128' cannot be converted to a 'sbyte' (use 'unchecked' syntax to override)`

otherwise i need to use formula but I'm not math guy so if I can achieve result simpler way I do.
because of that only part i can't touch.

2023-02-05 22:16 UTC, brkeejp commented on OpenTabletDriver.Configurations/Parsers/Veikk/VeikkTiltedReportParser.cs
> +            return new DeviceReport(report);
I can remove all those comments

2023-02-06 15:14 UTC, X9VoiD approved these changes

2023-08-13 14:54 UTC, merged