Add packaging scripts
OpenTabletDriver/OpenTabletDriver pull request #2787
Opened 2023-06-11 21:55 UTC by X9VoiD

Supersedes [OpenTabletDriver.Packaging](https://github.com/OpenTabletDriver/OpenTabletDriver.Packaging).

## Tested Platforms

- [x] Windows
- [ ] Debian-based
- [ ] RPM-based
- [ ] MacOS

## Changes (compared to OTD.Packaging)

### General

- Simplified packaging to improve maintainability and readability.

### Linux

- Packages now use `/usr/lib/opentabletdriver` to stash the real binaries instead of `/usr/share/OpenTabletDriver`. This is to comply better to FHS (`/usr/share` can *only* contain arch-independent files).
- Binary tarball is now better structured for easier system administration/automation to those that uses it.
- Changed systemd user service to start explicitly after `graphical.target`. It won't solve the issues we have with boot-up but it's better than an ambiguous `default.target` (which could be `multi-user.target`)
- Improved the kernel module blacklist to apply during boot and runtime (previously it only blocks module loading during boot).

2023-06-12 17:50 UTC, gonX requested changes
overall nice work

2023-06-12 17:50 UTC, gonX commented on eng/linux/Debian/package.sh
> + ${OTD_NAME} has the highest number of supported tablets with great
Can these sentences be put into a config file that other packaging scripts can source from as well? seems useful to have centralized

2023-06-12 17:50 UTC, gonX commented on build.sh
can get rid of this file if you like, just coordinate with packagers first

2023-06-12 17:50 UTC, gonX commented on eng/linux/Generic/usr/lib/modprobe.d/99-opentabletdriver.conf
> +install hid_uclogic /usr/bin/true
```suggestion
blacklist wacom
blacklist hid_uclogic
```

Otherwise users would need to uninstall OpenTabletDriver entirely to be able to load the vendor drivers, which may not be desirable for some setups.

2023-06-12 17:50 UTC, gonX commented on eng/linux/Generic/usr/lib/systemd/user/opentabletdriver.service
> +WantedBy=default.target
This won't work because we can't ensure that environment variables are ready yet. I suggest the following instead:

```suggestion
[Unit]
Description=OpenTabletDriver Daemon
PartOf=graphical-session.target

[Service]
ExecStart=otd-daemon
Restart=always
RestartSec=3

[Install]
WantedBy=graphical-session.target
```

See "_2) Set up a dependency chain so that your DE starts a systemd target (advanced)_" in https://github.com/OpenTabletDriver/OpenTabletDriver.Web/issues/43#issue-1105884672 for more details.

The alternative for starting should be starting it on DE start, ie. literally `otd-daemon` in the DE/WM's autostart.

2023-06-12 17:50 UTC, gonX commented on generate-rules.sh
> +set -eu
I would prefer just using `set -u` if anything. `set -e` breaks some expected behaviors (like some uses of `&&` and `||` in if's) - better to just affix commands with ` || exit $?`

I suggest reading the `-e` section in `man 1 bash`

(I might have missed this for other BASH scripts but consider this review as for all of them)

2023-06-12 18:34 UTC, X9VoiD commented on eng/linux/Debian/package.sh
> + ${OTD_NAME} has the highest number of supported tablets with great
Would moving it to `lib.sh` suffice? Will remove the extra whitespaces as well.

2023-06-12 18:36 UTC, X9VoiD commented on build.sh
Won't remove. It still has its use. (provides sane defaults for quickly doing a build and testing things out)

2023-06-12 18:36 UTC, gonX commented on eng/linux/Debian/package.sh
> + ${OTD_NAME} has the highest number of supported tablets with great
yes definitely

2023-06-12 18:37 UTC, X9VoiD commented on eng/linux/Generic/usr/lib/modprobe.d/99-opentabletdriver.conf
> +install hid_uclogic /usr/bin/true
The goal is to make OpenTabletDriver not undesirable, so I think keeping those modules unloadable is fine.

2023-06-12 18:43 UTC, gonX commented on eng/linux/Generic/usr/lib/modprobe.d/99-opentabletdriver.conf
> +install hid_uclogic /usr/bin/true
After further research, `modprobe -i` can circumvent `install`s - so leaving this in as-is is fine.

2023-06-12 20:16 UTC, X9VoiD commented on eng/linux/Debian/package.sh
> + ${OTD_NAME} has the highest number of supported tablets with great
Done

2023-06-14 01:55 UTC, hwsmm commented on eng/linux/lib.sh
> +Version=${OTD_VERSION}
This entry is not for the software version, but for desktop entry spec version

2023-06-14 09:19 UTC, X9VoiD commented on eng/linux/lib.sh
> +Version=${OTD_VERSION}
Fixed, should be 1.5 i think?

2023-06-18 15:23 UTC, merged