TRANSLATED README TO NL ALSO FIXED BADGES OR SOMETHING
OpenTabletDriver/OpenTabletDriver pull request #2904
Opened 2023-08-26 19:28 UTC by Ruben172

2023-08-26 19:32 UTC, Kuuuube requested changes

2023-08-26 19:32 UTC, Kuuuube commented on docs/README_CN.md
> +[![Actions Status](https://github.com/OpenTabletDriver/OpenTabletDriver/workflows/.NET%20CI/badge.svg)](https://github.com/OpenTabletDriver/OpenTabletDriver/actions) [![CodeFactor](https://www.codefa
Change back the alt text on the download counter. It isn't translated on most of them but it is here so it should be kept.

2023-08-26 19:39 UTC, Ruben172 commented on docs/README_CN.md
> +[![Actions Status](https://github.com/OpenTabletDriver/OpenTabletDriver/workflows/.NET%20CI/badge.svg)](https://github.com/OpenTabletDriver/OpenTabletDriver/actions) [![CodeFactor](https://www.codefa
thank you kuuube love you <3

2023-08-26 19:45 UTC, Kuuuube requested changes

2023-08-26 19:45 UTC, Kuuuube commented on docs/README_NL.md
> +[English](../README.md) | [한국어](docs/README_KO.md) | [Español](docs/README_ES.md) | [Русский](docs/README_RU.md) | [简体中文](docs/README_CN.md) | [Français](docs/README_FR.md) | [Deutsch](docs/README_DE
```suggestion
[English](../README.md) | [한국어](README_KO.md) | [Español](README_ES.md) | [Русский](README_RU.md) | [简体中文](README_CN.md) | [Français](README_FR.md) | [Deutsch](README_DE.md) | [Português-BR](README_PTBR.md) | Nederlands
```
Your links are broken.

2023-09-20 21:15 UTC, jamesbt365 commented
good job Ruben amazing commit

2023-09-20 21:16 UTC, Ruben172 commented
> good job Ruben amazing commit

:3

2024-03-10 19:46 UTC, jamesbt365 requested changes

2024-03-10 19:46 UTC, jamesbt365 commented on docs/README_NL.md
> +Voor problemen en PRs met betrekking tot de verpakking van OpenTabletDriver, bekijk alstublieft [hier](https://github.com/OpenTabletDriver/OpenTabletDriver.Packaging) de repository.
Packaging is now done within this repository.
```suggestion

```

2024-03-10 19:46 UTC, jamesbt365 commented on docs/README_NL.md
> +Voor problemen en PRs met betrekking tot de webpagina van OpenTabletDriver, bekijk alstublieft [hier](https://github.com/OpenTabletDriver/OpenTabletDriver.Web) de repository.
We have now moved our website to GitHub pages, the current referenced repository is archived and is no longer worked on.
```suggestion
Voor problemen en PRs met betrekking tot de webpagina van OpenTabletDriver, bekijk alstublieft [hier](https://github.com/OpenTabletDriver/opentabletdriver.github.io) de repository.
```

2024-03-17 19:44 UTC, jamesbt365 approved these changes
thank

2024-03-17 20:07 UTC, jamesbt365 reviewed
Actually I hate to be that guy but the README surrounding building the driver has changed drastically since this was worked on. Could you take a look?

2024-03-17 20:42 UTC, Ruben172 commented
> Actually I hate to be that guy but the README surrounding building the driver has changed drastically since this was worked on. Could you take a look?

fixed in [9119671](https://github.com/OpenTabletDriver/OpenTabletDriver/pull/2904/commits/9119671f3b9d71d14d062f27d459c51a1a542949)

2024-03-17 20:42 UTC, jamesbt365 commented on docs/README_NL.md
> +- .NET 6 SDK (kan [hier](https://dotnet.microsoft.com/download/dotnet/6.0) verkregen worden - U heeft de SDK voor uw platform nodig, Linux gebruikers kunnen het via hun package manager installeren wa
This should be dotnet 7 sdk, we changed that too.

2024-03-17 20:43 UTC, Ruben172 commented on docs/README_NL.md
> +- .NET 6 SDK (kan [hier](https://dotnet.microsoft.com/download/dotnet/6.0) verkregen worden - U heeft de SDK voor uw platform nodig, Linux gebruikers kunnen het via hun package manager installeren wa
reviewer is fixing that yeah o7

2024-03-17 21:04 UTC, Ruben172 commented on docs/README_NL.md
> +- .NET 6 SDK (kan [hier](https://dotnet.microsoft.com/download/dotnet/6.0) verkregen worden - U heeft de SDK voor uw platform nodig, Linux gebruikers kunnen het via hun package manager installeren wa
fixed in [5de2056](https://github.com/OpenTabletDriver/OpenTabletDriver/pull/2904/commits/5de20565585b2ae1cfc67e39787f23cb6e6a938e)

2024-03-17 21:05 UTC, Earthgames commented
I also check Rubens shit, and it look ok

2024-05-10 14:31 UTC, merged