Add support for Huion H951P
OpenTabletDriver/OpenTabletDriver pull request #2927
Opened 2023-09-13 02:46 UTC by FrBst

Verified the configuration on my own tablet.
The digitizer height is as measured on my device, it's a bit more than in official specs

2023-11-23 11:31 UTC, gonX requested changes

2023-11-23 11:31 UTC, gonX commented on OpenTabletDriver.Configurations/Configurations/Huion/H951P.json
> +      "Height": 141.0,
Based off the MaxX and MaxY values, these settings are likely more correct (matching 200 LPMM exactly):
```suggestion
      "Width": 220.985,
      "Height": 137.995,
```

2023-11-23 11:31 UTC, gonX commented on OpenTabletDriver.Configurations/Configurations/Huion/H951P.json
> +      "ReportParser": "OpenTabletDriver.Configurations.Parsers.UCLogic.UCLogicTiltReportParser",
Given the missing features reported in TABLETS.md, it is likely that another parser is more accurate. Please test the following change:
```suggestion
      "ReportParser": "OpenTabletDriver.Configurations.Parsers.UCLogic.UCLogicV2ReportParser",
```

Of course, TABLETS.md needs to be updated accordingly.

2023-11-29 08:03 UTC, FrBst commented
@gonX
I can't check any changes right now (I have some problem with Windows, OTD doesn't get any input, trying to solve).

Regarding width and height - the new values should be fine, they align with the specs on Huion website.
Regarding the parser - I will try it out when I can get everything to work again, but it might not be soon.

For the time being, can we merge it as is and then make the changes in subsequent updates?

2023-11-30 12:53 UTC, FrBst commented on OpenTabletDriver.Configurations/Configurations/Huion/H951P.json
> +      "MaxY": 27599.0
Tried this part again and got some nice numbers, 200 LPMM resolution checks out too. Guess this must be the right config:
```suggestion
      "Width": 221.0,
      "Height": 138.0,
      "MaxX": 44200.0,
      "MaxY": 27600.0
```

2023-11-30 12:56 UTC, FrBst commented on OpenTabletDriver.Configurations/Configurations/Huion/H951P.json
> +      "Height": 141.0,
MaxX and MaxY are slightly off, I added the right values as another suggestion

2023-11-30 12:56 UTC, gonX commented on OpenTabletDriver.Configurations/Configurations/Huion/H951P.json
> +      "MaxY": 27599.0
Thanks for providing these numbers. Does the parser change I suggested work for you?

2023-12-02 03:20 UTC, FrBst commented on OpenTabletDriver.Configurations/Configurations/Huion/H951P.json
> +      "MaxY": 27599.0
> Does the parser change I suggested work for you?

Left a comment on your suggestion

2023-12-02 10:44 UTC, gonX commented
Please push the `MaxX` and `MaxY` changes to this branch.

This PR would also need to move to a completely new parser that does not exhibit the aux issues.

2023-12-02 15:01 UTC, FrBst commented
> Please push the `MaxX` and `MaxY` changes to this branch.
> 
> This PR would also need to move to a completely new parser that does not exhibit the aux issues.

Added a new commit. Did I understand it correctly? Wheel still not working, but I created a parser so there are no weird issues with aux buttons

2023-12-02 19:33 UTC, gonX commented
Amazing! You can resolve the remaining conversations

2023-12-02 19:54 UTC, X9VoiD commented
Don't mind the CI failure here. We're doing stuff on our end to fix bugs on the CI workflow.

2023-12-03 01:08 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Parsers/Huion/InspiroyReportParser.cs
> +                0xe3 => new UCLogicAuxReport(data),
This PR is based on an old commit of `master` that didn't have the configuration linters yet, so what I did is I created a new branch from this, rebased it to latest `master`, then ran `dotnet test --filter FullyQualifiedName~ConfigurationTest`

2023-12-06 03:15 UTC, FrBst commented on OpenTabletDriver.Configurations/Parsers/Huion/InspiroyReportParser.cs
> +                _ => new TiltTabletReport(data)
> Determine what kind of reports actually contain `TiltTabletReport`, there should also be a report that indicates out of range, then discard everything else that cannot be parsed. Don't use TiltTabletReport itself as a catch-all.

Fixed in https://github.com/OpenTabletDriver/OpenTabletDriver/pull/2927/commits/8fdbbdd9730746b3e51ae63585d68abb2b36ccbb. Also updated TABLETS.md in https://github.com/OpenTabletDriver/OpenTabletDriver/pull/2927/commits/7840569ec60d56f6710e5b7c234df31d786ed2f9

2023-12-24 08:54 UTC, X9VoiD approved these changes
LGTM, just some minor changes that I can apply myself before merge.

2024-05-14 16:48 UTC, InfinityGhost approved these changes

2024-05-14 16:53 UTC, jamesbt365 approved these changes

2024-05-29 15:24 UTC, merged