Parse /etc/os-release in diagnostics
OpenTabletDriver/OpenTabletDriver pull request #2944
Opened 2023-09-30 18:17 UTC by gonX

Closes #2744 
Supersedes #2819 

Pre-PR diagnostics on Linux:
```json
  "OperatingSystem": {
    "Platform": "Unix",
    "ServicePack": "",
    "Version": "6.5.5.273",
    "VersionString": "Unix 6.5.5.273"
  }
```

Post-PR diagnostics on Linux:
```json
  "OperatingSystem": {
    "NAME": "Arch Linux",
    "PRETTY_NAME": "Arch Linux",
    "ID": "arch",
    "BUILD_ID": "rolling"
  }
```

Code or naming is probably messy, reviews are very welcome in those areas.

2023-10-01 19:10 UTC, vedxyz requested changes
I've intended to make a PR for the parent issue several times but still haven't gotten around to it. I would've liked to say I can help with the stuff I've left reviews for here, but not trusting myself on that currently.

2023-10-01 19:10 UTC, vedxyz commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +        public IDictionary<string,string> Raw;
```suggestion
        public IDictionary<string, string> Raw;
```

Been a while since I touched C#, but I think this is the correct style?

2023-10-01 19:10 UTC, vedxyz commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +        }
This is really bit of a nit, but I'm not a fan of IO operations in the constructor. I personally would've kept this class instantiable independent of IO, and move the construction with IO to a static method (`FromFile()`? or `FromOsReleaseFile()`?). Might even make the method have a nullable return type instead of throwing an exception.

2023-10-01 19:10 UTC, vedxyz commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +        static IDictionary<string,string> parse()
Should be pascal case and private?

2023-10-01 19:10 UTC, vedxyz commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +        static IDictionary<string,string> parse()
On another note, I think the manpage and Python implementations can be consulted for a more robust parser. Although I'm unsure how much of a risk the current implementation poses, if any.

- See example 5 in https://www.freedesktop.org/software/systemd/man/os-release.html
- https://github.com/python/cpython/blob/679af65ca3798dc36dedabfdc66303b4cee49373/Lib/platform.py#L1233-L1287
  - Can be tested too, just saying https://github.com/python/cpython/blob/adf0f15a06c6e8ddd1a6d59b28efcbb26289f080/Lib/test/test_platform.py#L511-L539

2023-10-01 19:14 UTC, vedxyz commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +    public class LinuxEtcOSRelease
```suggestion
    public class LinuxOSRelease
```

`Etc` irrelevant IMO.

2023-10-01 19:59 UTC, gonX commented on OpenTabletDriver.Desktop/Diagnostics/IDiagnosticInfo.cs
> +        IDictionary<string, string> OperatingSystem { get; }
`OperatingSystem` isn't universally useful for us - for the most part we just need the `VersionString`. I re-implemented the rest of the fields in case dotnet decides to expand its functionality on non-Windows systems.

I wish there was a cleaner way to integrate `OperatingSystem` as a Dictionary without the roundabout way of setting the fields individually done currently in the PR.

2023-10-01 20:00 UTC, gonX commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +        };
Could also just stick with just `ID`, extrapolating the other information should be simple.

2023-10-01 20:02 UTC, gonX commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +        static IDictionary<string,string> parse()
Implicitly private and private methods should be camelCase afaik. If there is precedence for explicit usage of `private` I have missed that. Will check up on this.

2023-10-01 20:03 UTC, gonX commented on OpenTabletDriver.Desktop/Diagnostics/DiagnosticInfo.cs
> +            rv.Add("VersionString", Environment.OSVersion.VersionString);
Agree with this, add a suggestion if you want the commit credit

2023-10-01 20:06 UTC, gonX commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +        }
Can just move it into a static function altogether. I mostly wanted it to be an instantiated (and singleton) class so that there'd be less overhead on multiple runs. But with the way things are implemented now it just makes the code harder to read, so I do plan to rework this.

2023-10-01 20:07 UTC, gonX commented on OpenTabletDriver.Desktop/Diagnostics/IDiagnosticInfo.cs
> +        IDictionary<string, string> OperatingSystem { get; }
I re-read your comment and I did initially go for a class that implemented those fields, but it would require the class to also be serializable. I ran into some roadblocks in regards to that, hence the current solution.

2023-10-01 20:11 UTC, gonX commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +        static IDictionary<string,string> parse()
I have not seen those examples but it doesn't look too different from what it's doing now - only immediate difference I'm seeing is they're parsing with a regex, whereas currently the proposed code checks for presence of `=` before parsing the line, which is effectively has the same end result.

A test would be cool but I am not well-versed in C# testing infra. Leaving convo open for last for input on that.

2023-10-01 20:14 UTC, gonX commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +        static IDictionary<string,string> parse()
(actually the code currently doesn't trim the value which we might want to do)

2023-10-01 20:15 UTC, vedxyz commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +        }
Yeah good point, this class could have a nullable, static, cached property `Instance` or something instead of a public constructor or static method.

2023-10-01 20:22 UTC, vedxyz commented on OpenTabletDriver.Desktop/Diagnostics/IDiagnosticInfo.cs
> +        IDictionary<string, string> OperatingSystem { get; }
Hmm, the main thing I'm not a fan of is that the contents of `OperatingSystem` (the property) are fluid and inconsistent across OSes as a dictionary. On Linux it's a dump of `os-release` keys, but on non-Linux it's actually structured but with totally different keys.

Setting the fields individually should also not be needed for a new class that can capture relevant OS info (for our purposes) for any OS. It'll just get serialized to JSON directly, might need a couple annotations though.

2023-10-01 20:25 UTC, vedxyz commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +    public class LinuxEtcOSRelease
Should've added more context. I say irrelevant because `etc/` is not the only place `os-release` can exist, per the manpage. (This is also something that might be good to consider for the parser logic, though IDK how many distros require handling this edge case)

2023-10-01 20:28 UTC, vedxyz commented on OpenTabletDriver.Desktop/Diagnostics/IDiagnosticInfo.cs
> +        IDictionary<string, string> OperatingSystem { get; }
Oh, I posted before refreshing the page so I missed your later comments.

2023-10-02 11:42 UTC, gonX commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +        static IDictionary<string,string> parse()
Resolved next push

2023-10-02 12:19 UTC, gonX commented on OpenTabletDriver.Desktop/Diagnostics/LinuxEtcOSRelease.cs
> +        static IDictionary<string,string> parse()
I did a pass over the code, most notably it was missing handling of comments, which will be added in an upcoming push.

2023-10-02 12:48 UTC, gonX commented
I sadly had to butcher the history (a lot of overlapping changes), but thanks for the review @vedxyz

2023-10-02 14:12 UTC, vedxyz approved these changes
LGTM. Just two small style suggestions.

---

I'm still of the same opinion as my [earlier comment](https://github.com/OpenTabletDriver/OpenTabletDriver/pull/2944/files#r1342183464) regarding dictionary vs class, but no biggie. @X9VoiD said he might have another look anyway so he might go for it if he sees fit.

2023-10-02 14:12 UTC, vedxyz commented on OpenTabletDriver.Desktop/Diagnostics/DiagnosticInfo.cs
> +        }
```suggestion
        public IDictionary<string, string> OperatingSystem => SystemInterop.CurrentPlatform switch
        {
            SystemPlatform.Linux => LinuxOSRelease.Raw,
            _ => OSVersionToDict(),
        };
```

@X9VoiD reminded me that this exists. Didn't test but should compile/work?

2023-10-02 14:12 UTC, vedxyz commented on OpenTabletDriver.Desktop/Diagnostics/LinuxOSRelease.cs
> +                    if (Array.IndexOf(ACCEPTED_KEYS, parsed.Key) == -1)
Could have used LINQ's `Contains` here, but no big deal.

2023-10-02 14:49 UTC, gonX commented on OpenTabletDriver.Desktop/Diagnostics/DiagnosticInfo.cs
> +        }
Will fixup if it doesnt work, looks familiar to me

2023-10-02 14:51 UTC, gonX commented on OpenTabletDriver.Desktop/Diagnostics/LinuxOSRelease.cs
> +                    if (Array.IndexOf(ACCEPTED_KEYS, parsed.Key) == -1)
Makes sense, that's more clear

2023-10-02 14:54 UTC, gonX commented
> I'm still of the same opinion as my [earlier comment](https://github.com/OpenTabletDriver/OpenTabletDriver/pull/2944/files#r1342183464) regarding dictionary vs class, but no biggie. @X9VoiD said he might have another look anyway so he might go for it if he sees fit.

There is nothing particularly interesting in the OperatingSystem struct at the moment, so I see no need to complicate the class with a serialization function.

2023-10-17 18:40 UTC, X9VoiD commented
Pushed commits to this PR. It looks like this now on Linux:

```json
  "OperatingSystem": {
    "Name": "Fedora Linux",
    "Version": "38 (Workstation Edition)",
    "Attributes": {
      "ID": "fedora",
      "VERSION_ID": "38",
      "VERSION_CODENAME": "",
      "PRETTY_NAME": "Fedora Linux 38 (Workstation Edition)",
      "SUPPORT_END": "2024-05-14",
      "VARIANT": "Workstation Edition",
      "VARIANT_ID": "workstation",
      "KERNEL_VERSION": "6.4.12-200.fc38.x86_64"
    }
  },
```

and this on Windows:

```json
  "OperatingSystem": {
    "Name": "Win32NT",
    "Version": "10.0.22621.0",
    "Attributes": {
      "ServicePack": ""
    }
  },
```

2023-10-17 18:45 UTC, merged