Add hungarian README
OpenTabletDriver/OpenTabletDriver pull request #2962
Opened 2023-10-15 16:06 UTC by PearooXD

I am a native Hungarian speaker, and I checked through the words with a spellchecker to make sure there are no typos or anything like that. :)

2023-10-15 16:07 UTC, jamesbt365 commented on docs/README_HU.md
> +[English](../README.md) | [한국어](docs/README_KO.md) | [Español](docs/README_ES.md) | [Русский](docs/README_RU.md) | [简体中文](docs/README_CN.md) | [Français](docs/README_FR.md) | [Deutsch](docs/README_DE
```suggestion
[English](../README.md) | [한국어](README_KO.md) | [Español](README_ES.md) | [Русский](README_RU.md) | [简体中文](README_CN.md) | [Français](README_FR.md) | [Deutsch](README_DE.md) | [Português-BR](README_PTBR.md) | Magyar
```
Your links are broken.

2023-10-15 16:09 UTC, jamesbt365 commented
Also please include yours on the main README.md file.

2023-10-15 16:14 UTC, PearooXD commented
All done

2023-10-15 16:17 UTC, jamesbt365 commented
Please remove the changes from #2961. If your pull request gets reviewed first yours therefore cannot be merged until the other is too.

The one that is merged after will deal with the conflicts as and when.

2023-10-15 16:45 UTC, PearooXD commented
Removed the file but I didn't remove the redirect from the other readme's, since they're mostly the same - or at least I hope that's the case, if not, I can remove them too

2023-10-15 16:46 UTC, jamesbt365 commented
No, please entirely remove any changes related to #2961, including history, if your pull requests gets merged first (which entirely depends on somebody else who knows the language reviewing it) we will have dead links.

Remove the git history and any other change you have made to match that pull request please.

2023-10-15 16:59 UTC, PearooXD commented
Done

2023-10-15 16:59 UTC, jamesbt365 commented
Please remove the history (commits).

2023-10-15 17:02 UTC, PearooXD commented
How do I do that?

2023-10-15 17:10 UTC, gonX commented
You'll need to squash all the commits into 1 so that the history makes sense. Right now, you are adding the Greek README and then removing it again which will make it look like you contributed to the Greek README at some point.

You can see the history for this pull request here: https://github.com/OpenTabletDriver/OpenTabletDriver/pull/2962/commits

For CLI git, see this guide: https://gist.github.com/lpranam/4ae996b0a4bc37448dc80356efbca7fa
For Github Desktop, see here: https://docs.github.com/en/desktop/managing-commits/squashing-commits-in-github-desktop

After squashing, you'll need to "Force Push" your changes so that this pull request is forcefully updated with the new history. I would advise backing up your changes on another branch (or with the good old copy paste) in case you mess something up.

2023-10-15 17:15 UTC, PearooXD commented
*Should be* okay now

2023-10-15 17:16 UTC, gonX commented
Thanks, that looks good now. Now it just needs to undergo normal review.

2023-10-15 17:16 UTC, jamesbt365 commented
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/22662856/e420b2b5-f21f-42e1-92a6-d5b8be898334)
one last thing reword this and remove the other lines.

2023-10-15 17:29 UTC, PearooXD commented
I messed it up but it doesn't matter (I think)

2023-10-15 17:33 UTC, jamesbt365 requested changes

2023-10-15 17:33 UTC, jamesbt365 commented on README.md
> +English | [한국어](docs/README_KO.md) | [Español](docs/README_ES.md) | [Русский](docs/README_RU.md) | [简体中文](docs/README_CN.md) | [Français](docs/README_FR.md) | [Deutsch](docs/README_DE.md) | [Portuguê
```suggestion
English | [한국어](docs/README_KO.md) | [Español](docs/README_ES.md) | [Русский](docs/README_RU.md) | [简体中文](docs/README_CN.md) | [Français](docs/README_FR.md) | [Deutsch](docs/README_DE.md) | [Português-BR](docs/README_PTBR.md) | [Magyar](docs/README_HU.md)
```

The main README.md is not inside the docs folder so you must include the path to specify the correct directory.

Just merge this change within GitHub and this can go on to normal review unless I have missed anything else.

2023-12-23 02:05 UTC, gepbird requested changes
Thanks for your translations, overall they were pretty good!
I'm a native Hungarian speaker as well, and have found several improvements:
- fix typos and delete a leftover English paragraph
- find better translations depending on the context (so neglect word-by-word translation)
- don't translate some tech expressions (eg. github issue,s as the interface is English for everyone AFAIK)
- translate techy expressions (this may not always be better, since these sometimes sound odd in Hungarian and English equivalents could be preferred)

I've left many nits, but I hope you can focus on the important changes

2024-03-17 19:50 UTC, jamesbt365 requested changes

2024-03-17 19:50 UTC, jamesbt365 commented on docs/README_HU.md
> +A hibajegyeket és az OpenTabletDriver [weboldalához](https://opentabletdriver.net) kapcsolódó PR-eket [ebben](https://github.com/OpenTabletDriver/OpenTabletDriver.Web) a repository-ban találhatod meg
Point this at opentabletdriver.github.io instead of OpenTabletDriver.Web, this repo is archived and no longer worked on since the move to github pages.

2024-03-17 19:50 UTC, jamesbt365 commented on docs/README_HU.md
> +A hibajegyeket és az OpenTabletDriver csomagolásához kapcsolódó PR-eket [itt találod](https://github.com/OpenTabletDriver/OpenTabletDriver.Packaging).
Remove this line, packaging is done in this repo now since #2787.

2024-03-17 20:09 UTC, jamesbt365 commented
I forgot to mention that the building OpenTabletDriver part has changed drastiscally since this was written, please take a look at that.

2024-03-17 20:44 UTC, jamesbt365 commented on docs/README_HU.md
> +- .NET 6 SDK (töltsd le [innen](https://dotnet.microsoft.com/download/dotnet/6.0) - A te platformodra készült SDK-t töltsd le, Linux felhasználók a package managerrel töltsék le)
```suggestion
- .NET 7 SDK (töltsd le [innen](https://dotnet.microsoft.com/download/dotnet/7.0) - A te platformodra készült SDK-t töltsd le, Linux felhasználók a package managerrel töltsék le)
```

2024-05-10 14:31 UTC, merged