Packaging/generate udev rules
OpenTabletDriver/OpenTabletDriver pull request #2971
Opened 2023-10-20 20:37 UTC by InfinityGhost

Rewrote generate-rules.sh to use `jq` `gawk` and `tr`

2023-10-20 20:56 UTC, X9VoiD reviewed
Some distro packages and/or packaging scripts might need to be updated to reflect new build time requirements. Not necessarily needed to be addressed in this PR, just taking a note of it.

2023-10-20 20:56 UTC, X9VoiD commented on OpenTabletDriver.Tools.udev/Program.cs
> -            );
This part is missing in the bash port?

2023-10-20 21:12 UTC, gonX commented
diff from 43c350e
```diff
--- /tmp/tmp.1frkEfhP8b/usr/lib/udev/rules.d/70-opentabletdriver.rules	2023-10-20 22:59:17.000000000 +0200
+++ 70-opentabletdriver.rules	2023-10-20 23:00:56.000000000 +0200
@@ -1,6 +1,4 @@
-/home/gonx/prog/pkgbuild/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.Desktop/Interop/Input/MacOSVirtualMouse.cs(71,66): warning CS8629: Nullable value type may be null. [/home/gonx/prog/pkgbuild/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.Desktop/OpenTabletDriver.Desktop.csproj]
-# Dynamically generated with the OpenTabletDriver.udev tool. https://github.com/OpenTabletDriver/OpenTabletDriver
-KERNEL=="js[0-9]*", SUBSYSTEM=="input", ATTRS{name}=="OpenTabletDriver Virtual Tablet", RUN+="/usr/bin/env rm %E{DEVNAME}"
+# OpenTabletDriver udev rules generated by eng/linux/generate-rules.sh
 KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess", TAG+="udev-acl"
 # Genius G-Pen 560
 KERNEL=="hidraw*", ATTRS{idVendor}=="0458", ATTRS{idProduct}=="5003", TAG+="uaccess", TAG+="udev-acl"
@@ -269,7 +267,6 @@
 # Wacom CTL-4100WL
 KERNEL=="hidraw*", ATTRS{idVendor}=="056a", ATTRS{idProduct}=="0376", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="056a", ATTRS{idProduct}=="0376", TAG+="uaccess", TAG+="udev-acl"
-# Wacom CTL-4100WL
 KERNEL=="hidraw*", ATTRS{idVendor}=="056a", ATTRS{idProduct}=="0377", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="056a", ATTRS{idProduct}=="0377", TAG+="uaccess", TAG+="udev-acl"
 # Wacom CTL-6100WL
@@ -315,7 +312,7 @@
 KERNEL=="hidraw*", ATTRS{idVendor}=="0b57", ATTRS{idProduct}=="9091", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="0b57", ATTRS{idProduct}=="9091", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="input", ATTRS{idVendor}=="0b57", ATTRS{idProduct}=="9091", ENV{LIBINPUT_IGNORE_DEVICE}="1"
-# Waltop Slim Tablet 5.8"
+# Waltop Slim Tablet 5.8
 KERNEL=="hidraw*", ATTRS{idVendor}=="172f", ATTRS{idProduct}=="0032", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="172f", ATTRS{idProduct}=="0032", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="input", ATTRS{idVendor}=="172f", ATTRS{idProduct}=="0032", ENV{LIBINPUT_IGNORE_DEVICE}="1"
@@ -323,6 +320,9 @@
 KERNEL=="hidraw*", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="0061", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="0061", TAG+="uaccess", TAG+="udev-acl"
 # Gaomon 1060 Pro
+KERNEL=="hidraw*", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="0064", TAG+="uaccess", TAG+="udev-acl"
+SUBSYSTEM=="usb", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="0064", TAG+="uaccess", TAG+="udev-acl"
+SUBSYSTEM=="input", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="0064", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 # Gaomon M6
 # Huion H1060P
 # Huion H1161
@@ -336,14 +336,14 @@
 # Huion HS610
 # Huion RTE-100
 # Huion RTM-500
-KERNEL=="hidraw*", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="0064", TAG+="uaccess", TAG+="udev-acl"
-SUBSYSTEM=="usb", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="0064", TAG+="uaccess", TAG+="udev-acl"
-SUBSYSTEM=="input", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="0064", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 # Huion H641P
 KERNEL=="hidraw*", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="0066", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="0066", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="input", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="0066", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 # Artisul A1201
+KERNEL=="hidraw*", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006d", TAG+="uaccess", TAG+="udev-acl"
+SUBSYSTEM=="usb", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006d", TAG+="uaccess", TAG+="udev-acl"
+SUBSYSTEM=="input", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006d", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 # Gaomon 1060 Pro
 # Gaomon GM156HD
 # Gaomon M106K Pro
@@ -391,10 +391,10 @@
 # Huion Q620M
 # Huion RDS-160
 # Huion RTM-500
-KERNEL=="hidraw*", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006d", TAG+="uaccess", TAG+="udev-acl"
-SUBSYSTEM=="usb", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006d", TAG+="uaccess", TAG+="udev-acl"
-SUBSYSTEM=="input", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006d", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 # Gaomon 1060 Pro
+KERNEL=="hidraw*", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006e", TAG+="uaccess", TAG+="udev-acl"
+SUBSYSTEM=="usb", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006e", TAG+="uaccess", TAG+="udev-acl"
+SUBSYSTEM=="input", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006e", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 # Gaomon M106K
 # Gaomon M10K
 # Gaomon PD1560
@@ -427,18 +427,15 @@
 # Huion WH1409
 # Huion WH1409 V2
 # Monoprice 10594
-KERNEL=="hidraw*", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006e", TAG+="uaccess", TAG+="udev-acl"
-SUBSYSTEM=="usb", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006e", TAG+="uaccess", TAG+="udev-acl"
-SUBSYSTEM=="input", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006e", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 # Gaomon M106K Pro
+KERNEL=="hidraw*", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006f", TAG+="uaccess", TAG+="udev-acl"
+SUBSYSTEM=="usb", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006f", TAG+="uaccess", TAG+="udev-acl"
+SUBSYSTEM=="input", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006f", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 # Gaomon M1230
 # Gaomon S620
 # Huion H320M
 # Huion H430P
 # Huion HS611
-KERNEL=="hidraw*", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006f", TAG+="uaccess", TAG+="udev-acl"
-SUBSYSTEM=="usb", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006f", TAG+="uaccess", TAG+="udev-acl"
-SUBSYSTEM=="input", ATTRS{idVendor}=="256c", ATTRS{idProduct}=="006f", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 # XP-Pen Artist 13.3
 KERNEL=="hidraw*", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="000b", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="000b", TAG+="uaccess", TAG+="udev-acl"
@@ -464,11 +461,11 @@
 SUBSYSTEM=="usb", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0071", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="input", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0071", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 # XP-Pen Star G430
-# XP-Pen Star G430S
-# XP-Pen Star G540
 KERNEL=="hidraw*", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0075", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0075", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="input", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0075", ENV{LIBINPUT_IGNORE_DEVICE}="1"
+# XP-Pen Star G430S
+# XP-Pen Star G540
 # XP-Pen Star 06
 KERNEL=="hidraw*", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0078", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0078", TAG+="uaccess", TAG+="udev-acl"
@@ -498,10 +495,10 @@
 SUBSYSTEM=="usb", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0904", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="input", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0904", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 # XP-Pen Deco 01 V2
-# XP-Pen Deco 01 V2 (variant 2)
 KERNEL=="hidraw*", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0905", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0905", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="input", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0905", ENV{LIBINPUT_IGNORE_DEVICE}="1"
+# XP-Pen Deco 01 V2 (variant 2)
 # XP-Pen Star G640S
 KERNEL=="hidraw*", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0906", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="0906", TAG+="uaccess", TAG+="udev-acl"
@@ -646,25 +643,25 @@
 SUBSYSTEM=="usb", ATTRS{idVendor}=="2d80", ATTRS{idProduct}=="6001", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="input", ATTRS{idVendor}=="2d80", ATTRS{idProduct}=="6001", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 # VEIKK S640
-# VEIKK S640 V2
 KERNEL=="hidraw*", A [...]

2023-10-20 22:01 UTC, gonX requested changes
You're missing `KERNEL=="js[0-9]*", SUBSYSTEM=="input", ATTRS{name}=="OpenTabletDriver Virtual Tablet", RUN+="/usr/bin/env rm %E{DEVNAME}"` in rules.

Also note that comment ordering seems different - please double check that they're commented to the appropriate convention, e.g.:

```
# Tablet One
# Tablet Two
<rule for Tablet One and Two>
```
and not
```
# Tablet One
<rule for Tablet One and Two>
# Tablet Two
```

2023-10-20 22:07 UTC, gonX commented on generate-rules.sh
> +configs_arr=$(jq -s "$script" $OTD_CONFIGURATIONS/**/**.json | tr -d '"')
I think this last trim is causing this diff, it's not critical though.
```diff
@@ -315,7 +312,7 @@
 KERNEL=="hidraw*", ATTRS{idVendor}=="0b57", ATTRS{idProduct}=="9091", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="0b57", ATTRS{idProduct}=="9091", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="input", ATTRS{idVendor}=="0b57", ATTRS{idProduct}=="9091", ENV{LIBINPUT_IGNORE_DEVICE}="1"
-# Waltop Slim Tablet 5.8"
+# Waltop Slim Tablet 5.8
 KERNEL=="hidraw*", ATTRS{idVendor}=="172f", ATTRS{idProduct}=="0032", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="172f", ATTRS{idProduct}=="0032", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="input", ATTRS{idVendor}=="172f", ATTRS{idProduct}=="0032", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 ```

2023-10-21 16:10 UTC, gonX commented on generate-rules.sh
> +IFS=':'
what happens if tablet name contains `:`?

2023-10-21 16:18 UTC, gonX commented on generate-rules.sh
> +] | unique | sort_by(.VendorID,.ProductID) | .[] | "\(.Name):\(.VendorID):\(.ProductID):\(.libinput)"'
```suggestion
script='[
  .[] | { Name:.Name, libinput:(.Attributes.libinputoverride // "0") } + (.DigitizerIdentifiers[] | { VendorID:.VendorID, ProductID:.ProductID })
] | unique | sort_by(.VendorID,.ProductID) | group_by(.VendorID, .ProductID) |
map({ Name: (map(.Name) | join(", ")), libinput: .[0].libinput, VendorID: .[0].VendorID, ProductID: .[0].ProductID})
| .[] | "\(.Name):\(.VendorID):\(.ProductID):\(.libinput)"'
```

this groups names in comments properly

2023-10-21 17:13 UTC, gonX commented on generate-rules.sh
> +] | unique | sort_by(.VendorID,.ProductID) | .[] | "\(.Name):\(.VendorID):\(.ProductID):\(.libinput)"'
```suggestion
script='[
  .[] | { Name:.Name, libinput:(.Attributes.libinputoverride // "0") } + (.DigitizerIdentifiers[] | { VendorID:.VendorID, ProductID:.ProductID })
] | unique | sort_by(.VendorID,.ProductID) | group_by(.VendorID, .ProductID) |
  map({ Name: (map(.Name) | join(", ")), libinput: (map(.libinput) | max), VendorID: .[0].VendorID, ProductID: .[0].ProductID})
| .[] | "\(.Name):\(.VendorID):\(.ProductID):\(.libinput)"'
```
this also ensures that libinput is 1 if its set in any of the declarations

2023-10-23 02:52 UTC, InfinityGhost commented on generate-rules.sh
> +IFS=':'
With a little bit of testing it would be an illegal character as it would try to use the suffix as the vendor ID. We can change the IFS to something else to work around this if needed.

2023-10-23 03:19 UTC, InfinityGhost commented on generate-rules.sh
> +configs_arr=$(jq -s "$script" $OTD_CONFIGURATIONS/**/**.json | tr -d '"')
This appears to be fixed now with the name grouping.

2023-10-24 15:51 UTC, gonX commented on generate-rules.sh
> +IFS=':'
I think we can take that chance for now, #2975 (when merged) will check for invalid udev rules in case we end up generating something incorrect.

2023-10-24 15:54 UTC, gonX commented on generate-rules.sh
> +for c in git jq tr awk; do
```suggestion
for c in git jq tr awk sed; do
```
since `sed` is now used

2023-10-24 16:02 UTC, gonX commented
updated diff after 55dd310
```diff
--- usr/lib/udev/rules.d/70-opentabletdriver.rules	2023-10-24 17:58:32.000000000 +0200
+++ ../tmp.IsuIGbBz1s/usr/lib/udev/rules.d/70-opentabletdriver.rules	2023-10-24 17:55:05.000000000 +0200
@@ -1,7 +1,6 @@
-/home/gonx/prog/pkgbuild/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.Desktop/Interop/Input/MacOSVirtualMouse.cs(71,66): warning CS8629: Nullable value type may be null. [/home/gonx/prog/pkgbuild/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.Desktop/OpenTabletDriver.Desktop.csproj]
-# Dynamically generated with the OpenTabletDriver.udev tool. https://github.com/OpenTabletDriver/OpenTabletDriver
-KERNEL=="js[0-9]*", SUBSYSTEM=="input", ATTRS{name}=="OpenTabletDriver Virtual Tablet", RUN+="/usr/bin/env rm %E{DEVNAME}"
+# OpenTabletDriver udev rules (https://github.com/OpenTabletDriver/OpenTabletDriver)
 KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess", TAG+="udev-acl"
+KERNEL=="js[0-9]*", SUBSYSTEM=="input", ATTRS{name}=="OpenTabletDriver Virtual Tablet", RUN+="/usr/bin/env rm %E{DEVNAME}"
 # Genius G-Pen 560
 KERNEL=="hidraw*", ATTRS{idVendor}=="0458", ATTRS{idProduct}=="5003", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="0458", ATTRS{idProduct}=="5003", TAG+="uaccess", TAG+="udev-acl"
@@ -315,7 +314,7 @@
 KERNEL=="hidraw*", ATTRS{idVendor}=="0b57", ATTRS{idProduct}=="9091", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="0b57", ATTRS{idProduct}=="9091", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="input", ATTRS{idVendor}=="0b57", ATTRS{idProduct}=="9091", ENV{LIBINPUT_IGNORE_DEVICE}="1"
-# Waltop Slim Tablet 5.8"
+# Waltop Slim Tablet 5.8
 KERNEL=="hidraw*", ATTRS{idVendor}=="172f", ATTRS{idProduct}=="0032", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="usb", ATTRS{idVendor}=="172f", ATTRS{idProduct}=="0032", TAG+="uaccess", TAG+="udev-acl"
 SUBSYSTEM=="input", ATTRS{idVendor}=="172f", ATTRS{idProduct}=="0032", ENV{LIBINPUT_IGNORE_DEVICE}="1"
 ```

Approving aside from the 1 change I've suggested a few minutes ago. I don't really care about the Waltop name being mangled.

2023-10-24 17:05 UTC, merged