Add support for Parblo Ninos N7B
OpenTabletDriver/OpenTabletDriver pull request #3006
Opened 2023-11-15 18:19 UTC by nefir2

2023-11-15 18:31 UTC, gonX requested changes

2023-11-15 18:31 UTC, gonX commented on OpenTabletDriver.Configurations/OpenTabletDriver.Configurations.csproj
> +
This change is unnecessary
```suggestion
```
The file should already be getting picked up by the itemgroup a few lines above

2023-11-15 18:31 UTC, gonX commented on OpenTabletDriver.Configurations/Configurations/Parblo/Ninos N7B.json
> +  "Name": "Parblo Ninos N7",
Tablet name should match the file name.
```suggestion
  "Name": "Parblo Ninos N7B",
```

2023-11-15 18:31 UTC, gonX commented on OpenTabletDriver.Configurations/Configurations/Parblo/Ninos N7B.json
> +      "MaxY": 16199.0
Are you sure this is correct? This is usually calculated based off LPI (usually 100 or 200) with `MaxX`/`MaxY` as reference point. You can get `MaxX` and `MaxY` with the help of the Tablet Debugger in OpenTabletDriver.

If these MaxX and MaxY values are correct, perhaps `Width` is `143.995` and `Height` is `80.995`?

2023-11-15 18:31 UTC, gonX commented on OpenTabletDriver.Configurations/Configurations/Parblo/Ninos N7B.json
> +    }
You should be able to skip one of these identifiers, likely the latter one if I had to guess

2023-11-15 18:31 UTC, jamesbt365 requested changes
Please amend these changes and follow our [CONTRIBUTING.md](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/CONTRIBUTING.md) thanks.

2023-11-15 18:31 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/OpenTabletDriver.Configurations.csproj
> +    <None Remove="Configurations\Parblo\Ninos N7B.json" />
Why are you touching this?

2023-11-15 18:31 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/Parblo/Ninos N7B.json
> +  "Name": "Parblo Ninos N7",
Correct this.

2023-11-15 18:44 UTC, nefir2 commented on OpenTabletDriver.Configurations/OpenTabletDriver.Configurations.csproj
> +    <None Remove="Configurations\Parblo\Ninos N7B.json" />
Visual Studio did this automatically

2023-11-15 22:43 UTC, gonX commented
Don't forget to add an entry to [TABLETS.md](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/TABLETS.md). You can see how to properly do that in [CONTIBUTING.md](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/CONTRIBUTING.md#adding-a-configuration)

Please confirm the following with the Tablet Debugger:
- [ ] Pressure reaches the full range
- [ ] Max values reached in matches MaxX/MaxY
- [ ] Both tilt axises are working
- [ ] All buttons work, on both tablet and pen

2023-11-15 23:00 UTC, jamesbt365 commented
Once done it would be nice if you were to squash commits ^^

2023-11-18 12:38 UTC, nefir2 commented
> Don't forget to add an entry to [TABLETS.md](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/TABLETS.md). You can see how to properly do that in [CONTIBUTING.md](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/CONTRIBUTING.md#adding-a-configuration)
> 
> Please confirm the following with the Tablet Debugger:
> 
>     * [ ]  Pressure reaches the full range
> 
>     * [ ]  Max values reached in matches MaxX/MaxY
> 
>     * [ ]  Both tilt axises are working
> 
>     * [ ]  All buttons work, on both tablet and pen

 * [x]  Pressure reaches the full range

 * [x]  Max values reached in matches MaxX/MaxY

 * [ ]  Both tilt axises are working

 * [x]  All buttons work, on both tablet and pen

I don't know how to check the third point because I don't know how it works. I can see "Tilt" in "Properties" section in the Debugger, but it changes values randomly when I use the stylus.

2023-11-18 12:50 UTC, jamesbt365 commented
Tilt corresponds to which direction the pen is tilted.

2023-11-19 05:18 UTC, gonX commented
If you hold your pen from the very end of it and let it dangle naturally by gravity (like a pendulum), the tilt reading should be close to `[0, 0]`. Make sure the pen is reasonably close to the tablet as some tablets do not report tilt unless it is fairly close to the surface.

One number should be corresponding to the horizontal axis while the other number should correspond to the vertical axis.

2023-11-27 13:01 UTC, gonX commented
Hello, please let us know how you're progressing with this. We're very interested in adding support for this tablet.

2023-12-10 01:15 UTC, X9VoiD commented on OpenTabletDriver.Configurations/Configurations/Parblo/Ninos N7B.json
> +      "MaxY": 16199.0
This doesn't look right. If current values are true then the sensors aren't a square.

2024-03-11 14:17 UTC, jamesbt365 commented
Fixes #3187.

2024-04-20 22:43 UTC, jamesbt365 approved these changes
Unless i'm missing anything, which I might be as it has been a while since I've looked into this tablet and the N7, I'm assuming the sizing is a little different between these 2 models as your config differs from the other.

Shouldn't be anything else stopping a merge of this one?

2024-05-29 15:24 UTC, merged