Adding README_TW
OpenTabletDriver/OpenTabletDriver pull request #3152
Opened 2023-12-27 20:37 UTC by stonkol

1. Adding the Traditional Chinese version of README.

2. Removing one empty line from README_DE.

3. Improving the lines in the last section of README_PTBR.

2023-12-27 21:03 UTC, gonX approved these changes
Aside from the actual translation (which I can't comment on), the other changes look good to me

2023-12-28 10:16 UTC, stonkol commented
> Aside from the actual translation (which I can't comment on), the other changes look good to me

Ok, cool, did I need to do anything for now?

2024-03-17 19:48 UTC, jamesbt365 requested changes

2024-03-17 19:48 UTC, jamesbt365 commented on docs/README_TW.md
> +有關OpenTabletDriver的packaging的問題與PR，請參閱[此處](https://github.com/OpenTabletDriver/OpenTabletDriver.Packaging)的儲存庫。
Remove this line, packaging is done in this repo now.

2024-03-17 19:48 UTC, jamesbt365 commented on docs/README_TW.md
> +有關OpenTabletDriver[網頁](https://opentabletdriver.net)相關的問題與PR，請參閱[此處](https://github.com/OpenTabletDriver/OpenTabletDriver.Web)的儲存庫。
Point this at opentabletdriver.github.io instead of OpenTabletDriver.Web, this repo is archived and no longer worked on since the move to github pages.

2024-03-17 20:08 UTC, jamesbt365 commented
I forgot to mention that the building OpenTabletDriver part has changed drastically since this was written, please take a look at that.

2024-05-10 14:31 UTC, merged