Add support for XP-Pen Artist 16
OpenTabletDriver/OpenTabletDriver pull request #3276
Opened 2024-04-10 20:45 UTC by Mat931

2024-04-10 20:58 UTC, jamesbt365 requested changes
We also strongly prefer a diagnostic be provided as per our [CONTRIBUTING.md](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/CONTRIBUTING.md) when adding support for tablets. Please provide the file generated from `help > export diagnostics`

2024-04-10 20:58 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist 16.json
> +      "InitializationStrings": [
Are you sure you need *every* string here for full functionality?

Judging from other tablets only 100 should be required, 123 may be required for aux functionality, could you provide a string dump from the inbuilt device string reader?

2024-04-10 20:58 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist 16.json
> +      "MaxX": 34416,
Are you sure these are right? If these are the highest values you can get you should adjust the width and weight to reflect these properly.

max value/lpmm = physical size

the lpmm for this tablet is 100 and the max value is what you can measure in the `tablet > tablet debugger` when moving your pen as far as you can get it to read.

2024-04-10 20:58 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist 16.json
> +      "MaxPressure": 2047,
XP-Pen likes to hide old tablets specification pages so I can't compare this alongside a spec sheet at this time, is this the value you got when you measured it in `tablet > tablet debugger`?

2024-04-10 20:58 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist 16.json
> +      "ReportParser": "OpenTabletDriver.Configurations.Parsers.XP_Pen.XP_PenOffsetAuxReportParser",
Are you sure this is the right parser? Its currently only used on the UGEE M708 (UGEE and XP-Pen are close companies so its fine if this is the right parser)

The only difference is where it reads auxiliary data from, so if it reads fine this is the right parser.

2024-04-10 21:01 UTC, Mat931 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist 16.json
> +      "InitializationStrings": [
Yes. I tried removing every single one of them. 123 is to switch to the correct aux button format but that also seems to mess up the dpi. It sometimes works if the 100 is removed but not reliably. These were captured using usbmon from the Windows driver running inside a virtual machine.

2024-04-10 21:02 UTC, Mat931 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist 16.json
> +      "InitializationStrings": [
How do I use the string reader?

2024-04-10 21:03 UTC, Mat931 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist 16.json
> +      "MaxX": 34416,
The MaxX and MaxY are from the tablet debugger. The width and height are copied from a different 16" tablet.

2024-04-10 21:03 UTC, Mat931 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist 16.json
> +      "MaxPressure": 2047,
MaxPressure is also the highest value seen in the tablet debugger

2024-04-10 21:03 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist 16.json
> +      "InitializationStrings": [
The OEM driver will throw strings that the tablet does not need and are simply denied by the tablet.

put `21827`, `77` in the middle and ignore the bottom box, dump all.

2024-04-10 21:03 UTC, Mat931 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist 16.json
> +      "ReportParser": "OpenTabletDriver.Configurations.Parsers.XP_Pen.XP_PenOffsetAuxReportParser",
Yes. With other parsers the aux buttons don't work

2024-04-10 21:23 UTC, Mat931 commented
[string reader.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/14937913/string.reader.txt)
[Artist 16 Diagnostics.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/14937914/Artist.16.Diagnostics.json)

2024-04-10 21:34 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist 16.json
> +      "InitializationStrings": [
Try only 100 and 123, replug your tablet to reset the initialization process.

2024-04-10 21:35 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/Artist 16.json
> +      "MaxX": 34416,
You should calculate the values using the formula provided and use those instead.

2024-04-10 21:36 UTC, jamesbt365 commented
Functionality of this tablet will be spotty until #3245 is merged.

2024-04-10 22:59 UTC, Mat931 commented
[Artist 16 Diagnostics Win.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/14938647/Artist.16.Diagnostics.Win.json)

2024-04-10 23:06 UTC, jamesbt365 approved these changes

2024-07-30 20:48 UTC, InfinityGhost commented
Blocking this PR until it has a backport

2024-09-17 22:06 UTC, jamesbt365 approved these changes

2024-09-17 22:18 UTC, merged