Fix aux button support on Veikk A15 tablets
OpenTabletDriver/OpenTabletDriver pull request #3284
Opened 2024-04-16 17:44 UTC by adhdandy

Proof [tablet-data.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/15000732/tablet-data.txt)

2024-04-16 18:02 UTC, jamesbt365 commented
Tablet data as proof doesn't verify much as it doesn't necessarily prove what the tablet is doing, could you do separate data recordings for the different functions of the tablet?

2024-04-17 18:34 UTC, jamesbt365 commented
Yes.

2024-04-17 18:50 UTC, adhdandy commented
[aux_buttons.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/15015732/aux_buttons.txt)
[movement.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/15015733/movement.txt)
[pen_buttons.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/15015734/pen_buttons.txt)
[pen_pressure.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/15015736/pen_pressure.txt)

2024-07-30 21:05 UTC, jamesbt365 requested changes
I'd still prefer a different naming scheme to avoid the breaking change if any other tablets use this parser in the future.

It likely accomodates all Veikk tablets that currently use the `SkipByteTabletReportParser`.

Parser looks fine.

2024-08-02 10:12 UTC, jamesbt365 commented
`VeikkV1ReportParser` should be fine for now. We'll be improving the naming scheme of our parsers at some point.

2024-08-02 10:18 UTC, jamesbt365 commented
Is tilt out of scope?

2024-08-02 14:27 UTC, adhdandy commented
> Is tilt out of scope?

I only have the old A15 without tilt, so I don't know how that works.

2024-08-03 03:34 UTC, InfinityGhost commented on OpenTabletDriver.Configurations/Configurations/VEIKK/A15.json
> +      "ReportParser": "OpenTabletDriver.Configurations.Parsers.Veikk.VeikkA15ReportParser",
We can change it later if it happens to fit more tablets.

2024-08-03 13:20 UTC, gonX approved these changes
LGTM, any parser duplication issues can be solved later (given that its already fairly messy)

2024-08-03 13:24 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/VEIKK/A15.json
> +      "ReportParser": "OpenTabletDriver.Configurations.Parsers.Veikk.VeikkA15ReportParser",
Will merge as is and somebody can rename it when they add tilt or other tablets to the parser.

2024-08-03 13:24 UTC, jamesbt365 approved these changes

2024-08-03 13:24 UTC, merged