Add support for variant of Huion H610X
OpenTabletDriver/OpenTabletDriver pull request #3301
Opened 2024-04-27 16:58 UTC by entith

My new Huion H610X had a different device string than the pattern specified in the config file: `HUION_T229_220720`

Attached is a diagnostics file with the tablet detected and working.

[diagnostic-h610x.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/15139030/diagnostic-h610x.json)

2024-04-27 17:00 UTC, jamesbt365 approved these changes
Assuming everything works this is fine, could you export and upload strings here anyway incase something comes up in the future and we have to hunt variants?

2024-04-27 17:27 UTC, entith commented
[strings-h610x.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/15139123/strings-h610x.txt)

2024-05-03 22:29 UTC, jamesbt365 approved these changes

2024-05-17 02:56 UTC, InfinityGhost requested changes

2024-05-17 02:56 UTC, InfinityGhost commented on OpenTabletDriver.Configurations/Configurations/Huion/H610X.json
> +        "201": "HUION_(T212|T229)_\\d{6}$"
```suggestion
        "201": "HUION_T(212|229)_\\d{6}$"
```

2024-05-17 08:24 UTC, jamesbt365 approved these changes

2024-05-29 15:24 UTC, merged