Bulk merge backport
OpenTabletDriver/OpenTabletDriver pull request #3372
Opened 2024-07-11 01:05 UTC by jamesbt365

Backports #3314 

Welcome to hell!

Because of the fuckup in #3291 that was noticed after the original bulk PR merge this is technically ahead of master for configurations because the follow up fix in #3335 was backported into #3292. This will be resolved if #3335 is fixed.

Draft as incomplete.

2024-07-11 01:42 UTC, jamesbt365 commented
Skimmed over the diff and it seems to include everything.

2024-07-20 22:01 UTC, InfinityGhost requested changes

2024-07-20 22:01 UTC, InfinityGhost commented on OpenTabletDriver.Configurations/Parsers/Veikk/VeikkAuxV1Report.cs
> +                }
Formatting

2024-07-20 22:10 UTC, InfinityGhost approved these changes

2024-07-20 22:12 UTC, merged