Fix Detection Issue for Huion Kamvas Pro 12 Tablet
OpenTabletDriver/OpenTabletDriver pull request #3432
Opened 2024-08-21 12:12 UTC by lucek8123

Hi,

I own a Kamvas Pro 12, and I found out that my tablet is undetected. When I was debugging, I found that my device with ProductID=109 has a DeviceString "HUION_M171_\d{6}$" instead of "HUION_M20j_\d{6}$" as in the configuration. This pull request will fix this bug by adding an additional configuration for this tablet.

PS: It's my first pull request, and my English is not my first language, so please forgive me if I do any mistakes :)

2024-08-21 12:16 UTC, jamesbt365 commented
Modify the regex of the **current** identifier instead of adding a new identifier, theres no need to bloat our configs in cases like these.

Additionally, please provide a diagnostic with the tablet plugged in and detected, it is a requirement as per our [CONTRIBUTING.md](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/CONTRIBUTING.md).

2024-08-21 13:02 UTC, jamesbt365 commented
I'm not asking you to remove the identifier, I'm asking you to merge the regex string.

2024-08-21 13:17 UTC, lucek8123 commented
Yeah i misunderstood... Sorry... I merged these two identifiers with regex now.

2024-08-22 01:18 UTC, jamesbt365 requested changes
This and then a squash of the commits with a better commit name would be ideal.

2024-08-22 01:18 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/Huion/Kamvas Pro 12.json
> +        "201": "HUION_(M20j|M171)_\\d{6}$"
```suggestion
        "201": "HUION_M(20j|171)_\\d{6}$"
```

2024-08-22 10:45 UTC, lucek8123 commented
Hi. I squashed commits and changed commit message as you said. I also included your change in this commit.

2024-08-22 19:55 UTC, jamesbt365 approved these changes

2024-08-23 03:40 UTC, InfinityGhost approved these changes

2024-08-23 03:41 UTC, merged