docs: Simplify README_PTBR.md
OpenTabletDriver/OpenTabletDriver pull request #3433
Opened 2024-08-21 22:52 UTC by meirochun

Reduced verbosity in the README_PTBR.md by condensing the text and removing redundant information. The updated documentation is now more concise and easier to follow.

In few parts was changed the whole word "OpenTabletDriver" to the short way "OTD". Because in Brazil now is more often people saying the abbreviated version.

2024-08-21 22:53 UTC, meirochun commented
I will find someone to review the text.

2024-08-21 22:59 UTC, jamesbt365 commented
> In few parts was changed the whole word "OpenTabletDriver" to the short way "OTD".

We try and avoid this in our official documentation, at least in practice and I personally would rather keep things in line with the rest of our docs. It doesn't really make that much sense to refer to it by an acronym in one localisation, its just generally unnatural.

n nearly every language, it is common for individuals to use abbreviations or acronyms. However, in more formal documentation, this practice is less frequent. I would prefer to maintain consistency here and keep it in line with the rest of the documentation.

2024-08-21 23:03 UTC, meirochun commented
That makes sense, I'll change it.

2024-09-05 23:27 UTC, MrFelopes requested changes
At "OpenTabletDriver é um programa código aberto", there should be a "de" between "programa" and "código". It should be: "OpenTabletDriver é um programa de código aberto...".

2024-09-05 23:32 UTC, MrFelopes approved these changes
Now, it's good to go!

2024-09-06 19:45 UTC, meirochun commented
@jamesbt365 review done.

2024-09-06 20:15 UTC, jamesbt365 approved these changes

2024-09-06 20:15 UTC, merged