Turcom TS-6580 compatibility config.
OpenTabletDriver/OpenTabletDriver pull request #3440
Opened 2024-08-25 21:09 UTC by VoidJuiceConcentrate

Adding config file for Turcom TS-6580. Full functionality tested in Windows 11 on OTD 0.7.x. 
Confirmed data via Huion driver USB packet capture. (USB addr in pcap is 3.10)
[ts-6580-diag.txt](https://github.com/user-attachments/files/16741961/ts-6580-diag.txt)
[ts-6580_huion-driver-cap.pcap.tar.gz](https://github.com/user-attachments/files/16741967/ts-6580_huion-driver-cap.pcap.tar.gz)

2024-08-25 21:44 UTC, jamesbt365 requested changes
Lint configuration to pass tests.

2024-08-25 23:03 UTC, VoidJuiceConcentrate commented
I also have a 0.6.x config available for this.

2024-08-26 00:00 UTC, jamesbt365 commented on TABLETS.md
> +| Turcom TS-6580                |     Supported     |
Please note the WinUSB requirement on windows.

2024-08-26 16:46 UTC, jamesbt365 commented on TABLETS.md
> +| Turcom TS-6580                |    Has Quirks     | Windows: Requires Zadig's WinUSB to be installed on interface 0.
The list should be alphabetically sorted.

2024-08-26 16:49 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/Turcom/TS-6580.json
> +        "121" : "M508"
The configuration still isn't linted, you see how other configurations, like this one, have the json properly "inline", this will not pass tests right now.

https://github.com/OpenTabletDriver/OpenTabletDriver/blob/49b7d80b41e6502ad31a149c74b8566c1b2217af/OpenTabletDriver.Configurations/Configurations/Huion/H610X.json#L29-L31

2024-08-26 17:03 UTC, VoidJuiceConcentrate commented on TABLETS.md
> +| Turcom TS-6580                |    Has Quirks     | Windows: Requires Zadig's WinUSB to be installed on interface 0.
Done.

2024-08-26 17:06 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/Turcom/TS-6580.json
> +        "121" : "M508"
Close, but it shouldn't be `"121" : "m508"`, it should be `"121": "m508"`.

2024-08-26 17:09 UTC, VoidJuiceConcentrate commented on OpenTabletDriver.Configurations/Configurations/Turcom/TS-6580.json
> +        "121" : "M508"
Corrected.

2024-08-26 17:11 UTC, jamesbt365 commented
Could you squash the commits down into 1 or 2 commits now? Its a 56 line diff adding 1 file, so there doesn't really need to be that many commits, it will make backporting the configuration while keeping proper attribution easier too.

2024-08-26 18:54 UTC, jamesbt365 commented
Should be good, will push an attribute to this config when #3245 is merged to help prevent flaky behaviour on Linux.

2024-09-17 23:47 UTC, jamesbt365 approved these changes

2024-09-17 23:47 UTC, merged