Prevent multiple exception dialogs from opening at once (spamming) (0.6.x)
OpenTabletDriver/OpenTabletDriver pull request #3490
Opened 2024-10-06 09:34 UTC by BunnyTub

Uses the **MessageBoxActive** bool to determine if there is an exception dialog already open.

This is to prevent cases where for example, a plugin throws an unhandled exception, or something goes horribly wrong in OpenTabletDriver, and exception windows are constantly shown. Things such as that can cause the system to slow down, and is definitely a problem, since not all windows can be closed quickly, or sometimes, even at all.

Although more than one exception won't be shown, they are logged.

2024-10-12 07:19 UTC, BunnyTub commented
![image](https://github.com/user-attachments/assets/187caca6-0c6d-4f0f-bc17-18517c03594e)

2024-10-13 18:54 UTC, gonX requested changes
Looks alright other than that one thing.

2024-10-13 18:54 UTC, gonX commented on OpenTabletDriver.UX/Extensions.cs
> +                return;
Unless I'm missing something, shouldn't this be moved below the `Log.Write` statement below?

2024-10-13 21:43 UTC, BunnyTub commented on OpenTabletDriver.UX/Extensions.cs
> +                return;
Yes, you're right, fixed the oversight.

2024-11-08 17:59 UTC, gonX approved these changes

2024-11-08 22:59 UTC, X9VoiD approved these changes

2024-11-08 23:00 UTC, merged