Fix AppInfo desync in UX
OpenTabletDriver/OpenTabletDriver pull request #3615
Opened 2024-12-18 01:38 UTC by Mrcubix

Attempt at fixing the Plugin Manager & Preset Manager being instantiated with the wrong AppInfo.

Closes #3575

2024-12-18 01:40 UTC, Mrcubix commented
![image](https://github.com/user-attachments/assets/0897196b-b161-4724-bd0c-98377d145ec7)

Well that's an odd way for unit tests to fail

2024-12-18 01:48 UTC, Mrcubix commented
Might need to unload all plugins before re-instantiating the new manager

2024-12-22 13:15 UTC, gonX requested changes
satisfy warnings (remove `mainPanel` definition in MainForm)

2025-01-22 15:22 UTC, gonX commented on OpenTabletDriver.UX/MainForm.cs
> +            AppInfo.PresetManager = new PresetManager();
I don't know enough about this part of the code - shouldn't this be grabbing the manager from the daemon rather than making a new one instead?

2025-01-22 16:53 UTC, Mrcubix commented on OpenTabletDriver.UX/MainForm.cs
> +            AppInfo.PresetManager = new PresetManager();
The UX instantiate its own Preset & plugin manager (in static properties).
The constructors of these objects use a path, that is only synchronized once the UX connects to the daemon.
This result in the Plugin Manager & Preset Manager, pulling data from the wrong path.

2025-01-22 16:54 UTC, Mrcubix commented on OpenTabletDriver.UX/MainForm.cs
> +            AppInfo.PresetManager = new PresetManager();
By re-instantiating the object, you force them to use the new path provided by the daemon.

2025-01-22 21:49 UTC, gonX commented on OpenTabletDriver.UX/MainForm.cs
> +            AppInfo.PresetManager = new PresetManager();
Ok, makes sense.

2025-01-22 21:50 UTC, gonX approved these changes

2025-01-22 21:50 UTC, merged