Add XP-Pen Deco 01 V3 configuration
OpenTabletDriver/OpenTabletDriver pull request #3644
Opened 2024-12-27 19:01 UTC by madnessman666

Tablet: XP-Pen Deco 01 V3
Status: Untested.
Notes: I tested it by myself and it's works. 

Works:

1. Pen

2. Binding

2024-12-27 19:32 UTC, jamesbt365 requested changes
> Tablet: XP-Pen Deco 01 V3 Status: Untested. Notes: I tested it by myself and it's works.


So what is it? is it tested? untested?

Your configuration doesn't follow half of our linting rules, look at existing configurations and remove all null and empty configurations fields.

Where is the diagnostic? All configurations submitted must be accompanied with a diagnostic (help > export diagnostics) 

You haven't included an entry in the TABLETS.md?

please read our CONTRIBUTING.md for anything else you missed.

2024-12-27 19:32 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/XP-Pen Deco 01 V3.json
> +    "Digitizer": {
There should be no trailing zeros.

2024-12-27 19:32 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/XP-Pen Deco 01 V3.json
> +      "MaxPressure": 16384,
Are you sure this isn't supposed to be 16383? Check in the tablets > tablet debugger

2024-12-27 19:32 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/XP-Pen Deco 01 V3.json
> +      "Buttons": {
This is the wrong format for the master branch. Look at existing configurations

2024-12-27 19:32 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/XP-Pen Deco 01 V3.json
> +        "2": "Deco 01 V3"
You don't need to match for this string.

2024-12-27 19:32 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/XP-Pen Deco 01 V3.json
> +  "AuxilaryDeviceIdentifiers": [
Are you sure you need any auxiliary devices?

2024-12-28 00:11 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/XP-Pen Deco 01 V3.json
> +  "Name": "Deco 01 V3",
```suggestion
  "Name": "XP-Pen Deco 01 V3",
```

2024-12-28 14:26 UTC, madnessman666 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/XP-Pen Deco 01 V3.json
> +    "Digitizer": {
See last commit for changes

2024-12-28 14:38 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/XP-Pen Deco 01 V3.json
> +      "MaxY": 31739
Are you sure this is exactly as high as you can get? If you can get higher change this number and calculate the height (maxy/200, because this tablet has 200lpmm), otherwise recalculate the height with the above formula anyway because its currently inaccurate to the tablet.

Try and get as *high* as you can, beacuse the higher you can get the more accurate you can make this.

2024-12-28 14:38 UTC, jamesbt365 commented
You still haven't attached a diagnostic to this post, as said before this is a requirement for all configuration posts.

2024-12-28 14:40 UTC, madnessman666 commented
Sorry. Forgot. 
[diag.json](https://github.com/user-attachments/files/18266487/diag.json)

2024-12-28 15:05 UTC, jamesbt365 commented on OpenTabletDriver.Configurations/Configurations/XP-Pen/XP-Pen Deco 01 V3.json
> +  }
There is no need to use this attribute when there is no ambiguity in the interface lengths, arbitrarily adding these may prevent new variants of this tablet from being supported out of the box.


```suggestion
  ]
```

2025-01-29 20:10 UTC, jamesbt365 approved these changes

2025-01-30 00:26 UTC, jamesbt365 commented
Thanks for your contribution!

2025-01-30 00:27 UTC, merged