Add PTH-460 configuration
OpenTabletDriver/OpenTabletDriver pull request #588
Opened 2020-12-26 13:20 UTC by X9VoiD

## Verification

[Discord](https://discord.com/channels/615607687467761684/615607687467761690/792379318428499969)

2020-12-30 08:43 UTC, AbstractQbit commented
Wacom driver doesn't let you do SetFeature (at least that's the case with pth860), so the second identifier will probably fail if used.

2020-12-30 14:15 UTC, X9VoiD commented
#599 will help with that. Can't remove it since this scenario may happen.

- Wacom driver, and OTD installed
- User disabled wacom service or killed process (At this point, tablet is already initialized by wacom driver)
- User, at some point, replugged the tablet (Replugging uninitializes the tablet)

If OTD don't have the SetFeature for the second identifier then the tablet won't be initialized.

2020-12-30 16:09 UTC, AbstractQbit commented
It won't be initialized either way because wacom driver doesn't let set feature through 🤷

2021-02-27 21:36 UTC, InfinityGhost commented
I never checked if this was ready, is it ready for merge?

2021-02-28 05:59 UTC, X9VoiD commented
Yes, ready for merge

2021-03-01 19:08 UTC, InfinityGhost requested changes

2021-03-01 19:08 UTC, InfinityGhost commented on OpenTabletDriver/Configurations/Wacom/PTH-460.json
> +      "ReportParser": null,
Explicitly define the report parser.

2021-03-02 11:54 UTC, X9VoiD commented on OpenTabletDriver/Configurations/Wacom/PTH-460.json
> +      "ReportParser": null,
Fixed

2021-03-12 05:26 UTC, NBruderman commented
Any news about this one? I think it's ready

2021-03-13 02:23 UTC, InfinityGhost commented
> Any news about this one? I think it's ready

Yeah I forgot to re-review. Will give it a once over.

2021-03-13 02:26 UTC, InfinityGhost commented on OpenTabletDriver/Configurations/Wacom/PTH-460.json
> +  ],
Kind of odd to see that this only uses the Wacom driver report parser. Does this still work correctly when caught up to v0.5.2.2?

2021-03-13 04:28 UTC, X9VoiD commented on OpenTabletDriver/Configurations/Wacom/PTH-460.json
> +  ],
I'm not entirely sure with this either. This auxiliary endpoint is not the one reporting tablet buttons so we don't know what this endpoint is for. Can change to non-wacom driver if that's more preferable.

2021-03-13 05:29 UTC, AbstractQbit commented on OpenTabletDriver/Configurations/Wacom/PTH-460.json
> +  ],
44 byte endpoint on intuosv3 carries touch data.

2021-03-13 07:19 UTC, X9VoiD commented on OpenTabletDriver/Configurations/Wacom/PTH-460.json
> +  ],
Is it confirmed that we need to skip a byte for the 44 byte endpoint?

2021-03-22 01:08 UTC, InfinityGhost approved these changes
lg2m

2021-03-22 01:09 UTC, merged