Allow only one instance of UX
OpenTabletDriver/OpenTabletDriver pull request #634
Opened 2021-01-08 10:39 UTC by X9VoiD

2021-01-08 18:29 UTC, InfinityGhost requested changes

2021-01-08 18:29 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/IUXDriver.cs
> +    public interface IUXDriver
`IUserInterface` makes more sense here.

2021-01-08 18:29 UTC, InfinityGhost commented on OpenTabletDriver.UX/RPC/UXDriver.cs
> +    public class UXDriver : IUXDriver
`UserInterfaceProxy`

2021-01-08 18:29 UTC, InfinityGhost commented on OpenTabletDriver.UX/UXInstance.cs
> +    public class UXInstance : IDisposable
`UserInterfaceInstance`

2021-01-08 18:29 UTC, InfinityGhost commented on OpenTabletDriver.UX/RPC/UXDriver.cs
> +                    form.WindowStyle = WindowStyle.Default;
This shouldn't be necessary, and actually has the potential to cause issues on non MainForm windows.

2021-01-08 18:29 UTC, InfinityGhost commented on OpenTabletDriver.UX/UXInstance.cs
> +            }
Why don't we just null check to see if it is a client or host?

2021-01-08 18:29 UTC, InfinityGhost commented on OpenTabletDriver.UX/UXInstance.cs
> +        readonly bool IsClient;
Add `private` to all fields, use `camelCase` for naming.

2021-01-08 18:47 UTC, X9VoiD commented on OpenTabletDriver.UX/RPC/UXDriver.cs
> +                    form.WindowStyle = WindowStyle.Default;
So just keep this?
```cs
                    form.Show();
                    form.BringToFront();
```
I'm assuming we won't need WindowState too to respect user-set window state (fullscreen vs windowed)

2021-01-08 18:49 UTC, InfinityGhost commented on OpenTabletDriver.UX/RPC/UXDriver.cs
> +                    form.WindowStyle = WindowStyle.Default;
Yes

2021-01-08 18:53 UTC, X9VoiD commented
Requested changes pushed

2021-01-08 19:06 UTC, InfinityGhost requested changes

2021-01-08 19:06 UTC, InfinityGhost commented on OpenTabletDriver.UX/RPC/UserInterfaceProxy.cs
> +    public class UserInterfaceProxy : IUserInterface
Actually, we should make the MainForm implement this interface and pass that through RPC

2021-01-08 19:06 UTC, InfinityGhost commented on OpenTabletDriver.UX/UserInterfaceInstance.cs
> +            GC.SuppressFinalize(this);
All references should be nulled before suppressing finalize (host and client)

2021-01-08 19:06 UTC, InfinityGhost commented on OpenTabletDriver.UX/UserInterfaceInstance.cs
> +    public class UserInterfaceInstance : IDisposable
This should be `UserInterfaceProxy` instead if we do the MainForm implementation

2021-01-08 19:37 UTC, X9VoiD commented
Pushed, made some changes to `RpcHost` to allow passing an object the rpc will attach to.

2021-01-08 19:53 UTC, InfinityGhost commented on OpenTabletDriver.UX/App.cs
> +            _ = UserInterfaceProxy.Invoke(async ux =>
Any reason to not just make this method `async void`?

2021-01-08 19:55 UTC, X9VoiD commented on OpenTabletDriver.UX/App.cs
> +            _ = UserInterfaceProxy.Invoke(async ux =>
No real reason other than the internet saying `async void` might be bad

2021-01-08 20:06 UTC, X9VoiD commented on OpenTabletDriver.UX/App.cs
> +            _ = UserInterfaceProxy.Invoke(async ux =>
Changed to `async void`

2022-05-02 16:02 UTC, EXtremeExploit commented
no merge?
⠀⣞⢽⢪⢣⢣⢣⢫⡺⡵⣝⡮⣗⢷⢽⢽⢽⣮⡷⡽⣜⣜⢮⢺⣜⢷⢽⢝⡽⣝
⠸⡸⠜⠕⠕⠁⢁⢇⢏⢽⢺⣪⡳⡝⣎⣏⢯⢞⡿⣟⣷⣳⢯⡷⣽⢽⢯⣳⣫⠇
⠀⠀⢀⢀⢄⢬⢪⡪⡎⣆⡈⠚⠜⠕⠇⠗⠝⢕⢯⢫⣞⣯⣿⣻⡽⣏⢗⣗⠏⠀
⠀⠪⡪⡪⣪⢪⢺⢸⢢⢓⢆⢤⢀⠀⠀⠀⠀⠈⢊⢞⡾⣿⡯⣏⢮⠷⠁⠀⠀
⠀⠀⠀⠈⠊⠆⡃⠕⢕⢇⢇⢇⢇⢇⢏⢎⢎⢆⢄⠀⢑⣽⣿⢝⠲⠉⠀⠀⠀⠀
⠀⠀⠀⠀⠀⡿⠂⠠⠀⡇⢇⠕⢈⣀⠀⠁⠡⠣⡣⡫⣂⣿⠯⢪⠰⠂⠀⠀⠀⠀
⠀⠀⠀⠀⡦⡙⡂⢀⢤⢣⠣⡈⣾⡃⠠⠄⠀⡄⢱⣌⣶⢏⢊⠂⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢝⡲⣜⡮⡏⢎⢌⢂⠙⠢⠐⢀⢘⢵⣽⣿⡿⠁⠁⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠨⣺⡺⡕⡕⡱⡑⡆⡕⡅⡕⡜⡼⢽⡻⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣼⣳⣫⣾⣵⣗⡵⡱⡡⢣⢑⢕⢜⢕⡝⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⣴⣿⣾⣿⣿⣿⡿⡽⡑⢌⠪⡢⡣⣣⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⡟⡾⣿⢿⢿⢵⣽⣾⣼⣘⢸⢸⣞⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠁⠇⠡⠩⡫⢿⣝⡻⡮⣒⢽⠋⠀⠀⠀⠀⠀⠀

2022-05-07 12:07 UTC, doubledge-spec commented
Merge?

2022-05-29 03:18 UTC, X9VoiD commented
Updated the thing

2022-07-22 11:35 UTC, doubledge-spec commented
update? what are the plans for this after DI rewrite is complete?

2022-09-03 12:12 UTC, closed without merging

2023-07-03 15:13 UTC, X9VoiD commented
Superseded by #2828