Center relative to parent control and fix location jitter
OpenTabletDriver/OpenTabletDriver pull request #689
Opened 2021-01-20 18:19 UTC by X9VoiD

## Changes

- Center all child form or dialog relative to parent window (mostly `MainForm`)
- Attach all child form or dialog to parent window (fixes problems like losing a form/dialog behind the `MainForm` or the form/dialog not restored in conjuction with `MainForm.Show()` after getting minimized)
- Fixed `MainForm` being larger than 1366x768 or smaller screens. (Previous logic checked if ClientSize is larger than Screen before applying but ClientSize does not account for window decoration, so the window's total size is still larger than the screen)
- Apply `MainForm`'s sizing and centering logic before it launches by retrieving the screen through the cursor

2021-01-20 20:08 UTC, InfinityGhost requested changes

2021-01-20 20:08 UTC, InfinityGhost commented on OpenTabletDriver.UX/MainForm.cs
> +            InitializePlatform();
At least copy what was in the original `DesktopForm` class if you're going to outright remove it. This is called at `OnLoadComplete()` with the single run variable. Preferably, I'd like to keep the `DesktopForm` class so this is easier to maintain.

2021-01-22 22:44 UTC, InfinityGhost approved these changes

2021-01-22 22:48 UTC, InfinityGhost requested changes
On GTK, dialogs are not even relatively close to being centered.
![image](https://user-images.githubusercontent.com/39218853/105557334-f8659e80-5cd9-11eb-9747-066d4ff49748.png)

2021-01-22 22:50 UTC, InfinityGhost requested changes

2021-01-22 22:50 UTC, InfinityGhost commented on OpenTabletDriver.UX/DesktopForm.cs
>          }
Fix this to check if the platform is GTK, window positioning is handled automatically on that platform.
```cs
        protected virtual void InitializeForm()
        {
            if (!Platform.IsGtk)
            {
                var x = Owner.Location.X + (Owner.ClientSize.Width / 2);
                var y = Owner.Location.Y + (Owner.ClientSize.Height / 2);
                var center = new PointF(x, y);

                Location = new Point((int)(center.X - (ClientSize.Width / 2)), (int)(center.Y - (ClientSize.Height / 2)));
            }
        }
 ```

2021-11-06 02:52 UTC, X9VoiD commented
Fixed, and rebased to https://github.com/OpenTabletDriver/OpenTabletDriver/commit/2ddf0a75b455996ac3eba163a280c83c11b7ba4a.

![image](https://user-images.githubusercontent.com/10338031/140595472-50137a8d-906f-45f4-8e6e-edefb0cdbf0f.png)

It was a bug in Eto where `ClientSize` will always be zero until form is shown, all calls to `ClientSize._set` are ignored in Gtk as long as `Form.Show()` is not called yet

2021-12-01 01:58 UTC, gonX commented
CodeFactor is crying - also, rebase and/or close? No idea if this PR is still interesting

2021-12-21 16:37 UTC, InfinityGhost commented
Resolve conflicts and I'll test then merge.

2021-12-24 16:39 UTC, InfinityGhost commented
Tablet debugger size appears entirely wrong on GTK, horizontal scrollbar visible.

2021-12-25 10:05 UTC, gonX requested changes
Just 1 change to fix the issue reported by Ghost, otherwise LGTM

2021-12-25 10:05 UTC, gonX commented on OpenTabletDriver.UX/Windows/Tablet/TabletDebugger.cs
> +            this.ClientSize = new Size(640, 640);
Removing this line makes Tablet debugger size properly by default
```suggestion
```

2021-12-25 11:54 UTC, X9VoiD commented on OpenTabletDriver.UX/Windows/Tablet/TabletDebugger.cs
> +            this.ClientSize = new Size(640, 640);
Removing this may also cause issues with platforms that rely on pre-determined size for jitter-less window creation (Windows, MacOS), but will add that change for now for the sake of moving things forward.

2021-12-25 11:57 UTC, gonX commented on OpenTabletDriver.UX/Windows/Tablet/TabletDebugger.cs
> +            this.ClientSize = new Size(640, 640);
The tablet debugger already has a default width height and height specified if I'm not mistaken: https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/OpenTabletDriver.UX/Windows/Tablet/TabletDebugger.cs#L122-L123:
```cs
            #code snipped for brevity
            var splitter = new Splitter
            {
                Width = 660,
                Height = 800
            };
            this.Content = new Scrollable
            {
                Content = splitter
            };
```

2021-12-26 17:54 UTC, InfinityGhost requested changes
Form windows are not centered when they are created on GTK, they're slightly offset lower than they should be. ideally, they should be handled by the window manager and should not be positioned by us on Linux altogether.

2021-12-26 21:18 UTC, InfinityGhost approved these changes

2021-12-26 21:19 UTC, merged