Harden against any possible settings loading error
OpenTabletDriver/OpenTabletDriver pull request #699
Opened 2021-01-21 19:58 UTC by X9VoiD

As discussed from the Discord, all discussed errors from loading a settings is fixed in this PR:

- Delete settings that are inaccessible by `PluginManager` (Keep structure if `AuxButtons` or `PenButtons`)
- Migrate settings after loading plugins to avoid null reference after uninstalling an active plugin through UX Plugin Manager
- Never let `Settings` become null after Daemon's initialization (UX side settings loading not needed anymore)

2021-01-22 03:30 UTC, InfinityGhost requested changes
Haven't tested this yet, but its a move in the right direction.

2021-01-22 03:30 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Settings.cs
> +        };
What's the sense in re-adding this? We removed this in the past for a reason.

2021-01-22 03:30 UTC, InfinityGhost commented on OpenTabletDriver.UX/MainForm.cs
> +            await Application.Instance.InvokeAsync(async () => Settings = await Driver.Instance.GetSettings());
Some interactivity would be nice here. What about in the case something went wrong? We lose all of that with this simplification.

2021-01-22 03:54 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Settings.cs
> +        };
Yeah it's not needed nice catch, it was supposed to be used as a default store but SafeMigrateCollection already handles it

2021-01-22 03:56 UTC, X9VoiD commented on OpenTabletDriver.UX/MainForm.cs
> +            await Application.Instance.InvokeAsync(async () => Settings = await Driver.Instance.GetSettings());
UX only ever starts loading settings when it connects to a Daemon, so since Daemon ensures that there is always a Settings available, most of the checking UX side is not needed anymore.

2021-01-22 03:57 UTC, InfinityGhost commented on OpenTabletDriver.UX/MainForm.cs
> +            await Application.Instance.InvokeAsync(async () => Settings = await Driver.Instance.GetSettings());
That's actually a better way of handling it in that case

2021-01-22 03:58 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Settings.cs
> +        };
Will remove Settings.Default

2021-01-22 09:43 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Settings.cs
> +        };
Resolved

2021-02-24 20:47 UTC, InfinityGhost approved these changes
All looks good, but haven't tested.

2021-02-25 08:47 UTC, X9VoiD commented
## Test 1 (Broken Format)

Change tablet area to something like 80mm width aspect ratio locked or anything memorable. Then do

```patch
-  "EnableClipping": false,
+  "EnableClipping": false,,
```

### Pre-PR

- Daemon crash

### Post-PR

- Daemon survives, and attempts to retrieve recoverable settings, in this case, OTD was able to recover up until `EnableClipping`

![image](https://user-images.githubusercontent.com/10338031/109127090-f84d3880-7788-11eb-9de3-f90df38fd3c3.png)

## Test 2 (Inexistent Output Mode)

Modify `settings.json` with

```patch
-    "Path": "OpenTabletDriver.Desktop.Output.AbsoluteMode",
+    "Path": "OpenTabletDriver.Desktop.Output.AbsoluteMod",
```

### Pre-PR

- Daemon crashes

### Post-PR

- Daemon survives and resets the component into its defaults

![image](https://user-images.githubusercontent.com/10338031/109113575-6e48a400-7777-11eb-877e-5fb6f3250426.png)

- This also fixes invalid paths for all other plugin paths that rely on PluginSettings

## Test 3 (Version Migration)

Save a settings file using OTD 0.4.2 or use this [settings.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/6041051/settings.zip)

### Pre-PR

- TipButton fails to migrate and is left `null`

![image](https://user-images.githubusercontent.com/10338031/109115227-b799f300-7779-11eb-8092-cec006014922.png)

### Post-PR

- TipButton is migrated to its default successfully

![image](https://user-images.githubusercontent.com/10338031/109115415-00ea4280-777a-11eb-8c06-ab8e969d52bf.png)

2021-02-27 21:34 UTC, InfinityGhost requested changes

2021-02-27 21:34 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Settings.cs
> +            using var jr = new JsonTextReader(sr);
I don't like this format, this should instead be in a block format. Don't directly apply this suggestion, doesn't update lower text.
```suggestion
            using (var stream = file.OpenRead())
            using (var sr = new StreamReader(stream))
            using (var jr = new JsonTextReader(sr))
            {
```

2021-02-27 21:34 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Settings.cs
> +                Log.Write("Settings", $"    Recovered '{p.PropertyName}'", LogLevel.Debug);
```suggestion
                Log.Write("Settings", $"Recovered '{p.PropertyName}'", LogLevel.Debug);
```

2021-02-27 21:34 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Settings.cs
> +                Log.Write("Settings", $"    Recovery ended. Reason: {e.Message}", LogLevel.Debug);
```suggestion
                Log.Write("Settings", $"Recovery ended. Reason: {e.Message}", LogLevel.Debug);
```

2021-02-27 21:34 UTC, InfinityGhost commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +        }
Should just move this into `Settings` directly as a static property.

2021-02-27 21:34 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Migration/SettingsMigrator.cs
> +            ));
If the `DriverDaemon.DefaultSettings` gets moved, this should be done instead.
```suggestion
            // Bindings
            settings.TipButton = SafeMigrateNamespace(settings.TipButton, Settings.Default.TipButton);
```

2021-02-28 05:57 UTC, X9VoiD commented
Fixed

2021-03-01 19:03 UTC, InfinityGhost approved these changes

2021-03-01 19:05 UTC, merged