Fix area resize and add toggle
OpenTabletDriver/OpenTabletDriver pull request #779
Opened 2021-02-17 07:58 UTC by X9VoiD

## Changes

- Add "Update proportionally to display area change" on tablet area editor context menu.
- Fix "Tablet area resize is performed in reverse when changing display area size".

## Test

1. Enable Lock Aspect Ratio
2. Change display area to quarter area (manual editing or changing mapped monitor of different resolution also triggers the bug)

### Pre-PR

The tablet area becomes bigger instead of smaller to maintain the *feel* or physical distance travelled to reach the same point on screen.

### Post-PR

Tablet area will only update after toggling "Update proportionally to display area change" and the resize is fixed.

2021-02-24 20:39 UTC, InfinityGhost commented
Not sure if I'm a big fan of the additional option, its not very clear why you would have both lock aspect ratio and this. Maybe the default behavior should be this instead.

2021-02-25 04:43 UTC, X9VoiD commented
Toggle removed

2021-02-26 00:36 UTC, InfinityGhost requested changes

2021-02-26 00:36 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Settings.cs
> +                TabletWidth *= DisplayWidth / prevValue;
Doesn't this make the aspect ratio *always* locked?

2021-02-26 00:36 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Settings.cs
> +                TabletHeight *= DisplayHeight / prevValue;
Same here

2021-02-26 00:36 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/OutputModeEditor.cs
> +                }
What changed here to trigger this?

2021-02-26 05:23 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Settings.cs
> +                TabletWidth *= DisplayWidth / prevValue;
I can probably change the math a little bit so it won't resize the area and just change the ratios, because if I add it back to `LockAspectRatio` if block then it's not really lock aspect ratio, but proportional resize. That's why there was a new toggle prior to the review.

2021-03-23 04:39 UTC, InfinityGhost commented
Don't like the direction of this PR, it's not a good solution to what we're trying to solve.

2021-03-23 04:39 UTC, closed without merging