Hide number if text is bigger than area rectangle
OpenTabletDriver/OpenTabletDriver pull request #805
Opened 2021-02-26 17:51 UTC by X9VoiD

![image](https://user-images.githubusercontent.com/10338031/109336388-443dd180-789e-11eb-8c1c-1d12af9fca34.png)

2021-02-26 17:58 UTC, AbstractQbit commented
Maybe it would be better to just push the text a bit away from the rectangle, rather than hide it completely?

2021-02-27 21:51 UTC, InfinityGhost commented
Resolve merge conflicts

2021-02-28 06:03 UTC, X9VoiD commented
Merge conflicts resolved

2021-03-01 18:55 UTC, InfinityGhost requested changes
One formatting issue but the rest looks good.

2021-03-01 18:55 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/Area/AreaDisplay.cs
> +
Remove this line

2021-03-02 11:50 UTC, X9VoiD commented on OpenTabletDriver.UX/Controls/Area/AreaDisplay.cs
> +
Fixed

2021-03-03 19:40 UTC, InfinityGhost approved these changes

2021-03-03 19:40 UTC, merged