Trigger boundary check on manual input
OpenTabletDriver/OpenTabletDriver pull request #880
Opened 2021-03-18 17:52 UTC by X9VoiD

Fixes #879 

- [x] Trigger boundary check during manual input
- [ ] Update input box content (X and Y) about the new changes

2021-03-22 01:14 UTC, InfinityGhost requested changes

2021-03-22 01:14 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/Area/AreaDisplay.cs
> +                this.ViewModel.PropertyChanged += (viewModelBase, args) =>
This is compounding, for any situation we set the ViewModel we'll be hooking this event yet again. Not sure this is the best way to trigger it.

2021-03-23 07:08 UTC, X9VoiD commented on OpenTabletDriver.UX/Controls/Area/AreaDisplay.cs
> +                this.ViewModel.PropertyChanged += (viewModelBase, args) =>
Can merge #801 to hook during ctor instead. That way we're sure it happens only once.

2021-03-23 07:12 UTC, X9VoiD commented on OpenTabletDriver.UX/Controls/Area/AreaDisplay.cs
> +                            PointF.Rotate(rect.BottomLeft, viewModel.Rotation)
Tabbing is gud again lol

2021-07-18 02:34 UTC, InfinityGhost commented
This needs to be rebased to latest master in order to be merged.

2021-07-27 03:21 UTC, X9VoiD commented
Will supersede this PR with something based on #1287

2021-07-27 03:21 UTC, closed without merging