Improve logged DeviceIOException message
OpenTabletDriver/OpenTabletDriver pull request #893
Opened 2021-03-20 13:35 UTC by X9VoiD

Intercept DeviceIOException and change it to something more descriptive. Include link to instructions as well.

Helps with #892

2021-03-20 23:11 UTC, InfinityGhost requested changes

2021-03-20 23:11 UTC, InfinityGhost commented on OpenTabletDriver/Driver.cs
> +            catch (IOException iex) when (iex.Message.Contains("Unable to open HID class device"))
This doesn't take into consideration what platform this is running on.

2021-03-21 12:26 UTC, X9VoiD commented on OpenTabletDriver/Driver.cs
> +            catch (IOException iex) when (iex.Message.Contains("Unable to open HID class device"))
Fixed. But the problem with our approach is that these logs are spammed. Tried moving it to DriverDaemon to implement breaks but that means you'll have to implement the same try catch on lazer side.

2021-03-22 01:12 UTC, InfinityGhost approved these changes
lg2m

2021-03-22 01:12 UTC, merged