Implement tablet driver detection
OpenTabletDriver/OpenTabletDriver pull request #905
Opened 2021-03-23 19:22 UTC by X9VoiD

## Changes

- Add `DriverInfo`
- Make OTD daemon aware of other tablet drivers (self-detection on another PR for osu! lazer and OTD)

Supports detection for the following drivers:

- Wacom
- Huion
- XP-Pen
- Gaomon
- VEIKK
- TabletDriver (Hawku/InfinityGhost/Devocub)

> Note: MacOS is not supported yet.

2021-03-24 10:04 UTC, X9VoiD commented
Ready for merge.

2021-03-24 18:28 UTC, InfinityGhost requested changes

2021-03-24 18:28 UTC, InfinityGhost commented on OpenTabletDriver/Instance.cs
> +            }
This is not a good way to implement this.

2021-03-24 18:28 UTC, InfinityGhost commented on OpenTabletDriver/Environ/DriverInfo.cs
> +namespace OpenTabletDriver.Environ
Just make the full namespace name
```suggestion
namespace OpenTabletDriver.Environment
```

2021-03-24 18:28 UTC, InfinityGhost commented on OpenTabletDriver/Environ/DriverInfo.cs
> +    public record DriverInfo
Just use a class, we don't use `record` anywhere else within the project and I don't have any intention to.

2021-03-24 18:28 UTC, InfinityGhost commented on OpenTabletDriver/Environ/Drivers/ProcessModuleQueryableDriver.cs
> +    internal abstract class ProcessModuleQueryableDriver : IDriverInfoProvider
```suggestion
    internal abstract class ProcessModuleQueryableDriverInfoProvider : IDriverInfoProvider
```

2021-03-24 18:28 UTC, InfinityGhost commented on OpenTabletDriver/Environ/Drivers/TabletDriver.cs
> +    internal class TabletDriver : IDriverInfoProvider
```suggestion
    internal class TabletDriverInfoProvider : IDriverInfoProvider
```

2021-03-24 18:28 UTC, InfinityGhost commented on OpenTabletDriver/Environ/Drivers/VeikkDriver.cs
> +    internal class VeikkDriver : ProcessModuleQueryableDriver
```suggestion
    internal class VeikkDriverInfoProvider : ProcessModuleQueryableDriverInfoProvider
```

2021-03-24 18:28 UTC, InfinityGhost commented on OpenTabletDriver/Environ/Drivers/WacomDriver.cs
> +    internal class WacomDriver : ProcessModuleQueryableDriver
```suggestion
    internal class WacomDriverInfoProvider : ProcessModuleQueryableDriverInfoProvider
```

2021-03-24 18:28 UTC, InfinityGhost commented on OpenTabletDriver/Environ/Drivers/XPPenDriver.cs
> +    internal class XPPenDriver : ProcessModuleQueryableDriver
```suggestion
    internal class XPPenDriverInfoProvider : ProcessModuleQueryableDriverInfoProvider
```

2021-03-24 18:28 UTC, InfinityGhost commented on OpenTabletDriver/Environ/IDriverInfoProvider.cs
> +    internal interface IDriverInfoProvider
We really need a better name for this interface. I don't like the `DriverInfo` name for the class as it is, we have too many "Info" classes which I'll be addressing in future pull requests.

2021-03-24 18:28 UTC, InfinityGhost commented on OpenTabletDriver/Environ/Drivers/GaomonDriver.cs
> +    internal class GaomonDriver : ProcessModuleQueryableDriver
```suggestion
    internal class GaomonDriverInfoProvider : ProcessModuleQueryableDriverInfoProvider
```

2021-03-24 18:28 UTC, InfinityGhost commented on OpenTabletDriver/Environ/Drivers/HuionDriver.cs
> +    internal class HuionDriver : ProcessModuleQueryableDriver
```suggestion
    internal class HuionDriverInfoProvider : ProcessModuleQueryableDriverInfoProvider
```

2021-03-24 18:28 UTC, InfinityGhost commented on OpenTabletDriver/Environ/Drivers/OpenTabletDriver.cs
> +    public class OpenTabletDriver : IDriverInfoProvider
```suggestion
    public class OpenTabletDriverInfoProvider : IDriverInfoProviderInfoProvider
```

2021-03-24 18:30 UTC, X9VoiD commented on OpenTabletDriver/Environ/DriverInfo.cs
> +namespace OpenTabletDriver.Environ
This makes it conflict with System.Environment on a lot of places.

2021-03-24 18:36 UTC, X9VoiD commented on OpenTabletDriver/Instance.cs
> +            }
```cs
if (createdNew)
{
    IsOwner = true;
}
```
Something simpler like this then? I implemented it with static bool because we can't use AlreadyExisting. (will trigger self-detection for OpenTabletDriver.Daemon)

2021-03-24 18:40 UTC, InfinityGhost commented on OpenTabletDriver/Instance.cs
> +            }
We shouldn't use a static property at all, this Instance class can be used outside of OpenTabletDriver as well.

An alternative solution would be to make a `private static readonly IList<Instance>` collection to store which instances the current application owns instead, and then using a public method to check for those instances.

2021-03-24 19:05 UTC, X9VoiD commented on OpenTabletDriver/Instance.cs
> +            }
Fixed.

2021-03-24 19:12 UTC, X9VoiD commented on OpenTabletDriver/Environ/DriverInfo.cs
> +    public record DriverInfo
Fixed.

2021-03-25 07:10 UTC, X9VoiD commented on OpenTabletDriver/Environ/IDriverInfoProvider.cs
> +    internal interface IDriverInfoProvider
Will address in a future PR

2021-03-25 07:11 UTC, X9VoiD commented
Requested changes all done

2021-07-02 00:00 UTC, gonX commented
Needs rebasing with master

2021-07-06 20:22 UTC, X9VoiD commented
Merge conflicts fixed.

2021-07-18 01:27 UTC, InfinityGhost requested changes

2021-07-18 01:27 UTC, InfinityGhost commented on OpenTabletDriver/Environment/DriverInfo.cs
> +namespace OpenTabletDriver.Environment
Change this namespace name, the conflict with `System.Environment` is annoying especially since this could be renamed.

2021-07-27 01:53 UTC, X9VoiD commented on OpenTabletDriver/Environment/DriverInfo.cs
> +namespace OpenTabletDriver.Environment
Resolved.
`OpenTabletDriver.Environment -> OpenTabletDriver.SystemDrivers`
`OpenTabletDriver.Environment.Drivers -> OpenTabletDriver.SystemDrivers.InfoProviders`

2021-07-28 01:32 UTC, InfinityGhost requested changes
Looks good to me, just minor changes.

2021-07-28 01:32 UTC, InfinityGhost commented on OpenTabletDriver/Instance.cs
> +                ownedInstances.Add(this);
We don't at any point remove an owned instance, maybe this should be implemented in the disposal?

2021-07-28 01:32 UTC, InfinityGhost commented on OpenTabletDriver/SystemDrivers/Providers/ProcessModuleQueryableDriverInfoProvider.cs
> +        private static string LinuxModules;
Casing should be camelCased since these are private fields.

2021-07-28 01:45 UTC, InfinityGhost approved these changes

2021-07-28 01:45 UTC, InfinityGhost commented on OpenTabletDriver/Instance.cs
> +                ownedInstances.Add(this);
Scratch that, this is only within a single application now that I think about it

2021-07-28 01:52 UTC, merged