Fix issues on pipeline rework
OpenTabletDriver/OpenTabletDriver pull request #927
Opened 2021-03-26 22:07 UTC by X9VoiD

## Issues fixed

- [x] OutputMode was not connected by default, so the benchmark fails
- [x] Null reference exception when AuxReader is null (for devices that don't have a separate aux interface)
- [ ] Millimeter and PreTranspose is not actually in milimeter coordinates (it was in raw device coordinates)
- [ ] RelativeOutputMode is broken (cursor on bottom right)
  - [x] Transform absolute report to delta report
  - [ ] Fix ResetTime (remove jumps)

Initial benchmarks for reworked pipeline:

| Method |     Mean |   Error |  StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |---------:|--------:|--------:|------:|------:|------:|----------:|
| Output | 102.2 ns | 1.96 ns | 1.64 ns |     - |     - |     - |         - |

2021-03-27 02:51 UTC, InfinityGhost requested changes

2021-03-27 02:51 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Output/LinuxArtistMode.cs
> +        public override IAbsolutePointer Pointer { set; get; } = new EvdevVirtualTablet();
Revert this commit, this is entirely on purpose. We store the pointer statically so when modifying settings or switching output modes, the virtual tablet doesn't get reconstructed. Applications such as GIMP require restart to make use of the new virtual tablet.

2021-03-27 03:10 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Output/OutputMode.cs
> +                    this.Emit -= this.OnFinalReport;
Not sure if this is the best way to handle this potential bug, elements can still be cleared.

A private function to control this bypass technique would be a much safer and maintainable alternative with a field that stores the bypass state.

2021-03-27 07:01 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Output/LinuxArtistMode.cs
> +        public override IAbsolutePointer Pointer { set; get; } = new EvdevVirtualTablet();
Resolved. The null check is removed by statically setting the private pointer.

2021-03-27 07:08 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Output/OutputMode.cs
> +                    this.Emit -= this.OnFinalReport;
Made a private function that sets and unsets the passthrough.

2021-03-27 11:03 UTC, X9VoiD commented
Ready for merge.

For a test element, build [this branch](https://github.com/X9VoiD/OpenTabletDriver/tree/output-pipeline-test-element) (devocub filter ported as a pipeline element)

2021-04-01 01:46 UTC, InfinityGhost commented
>     *  Every access to IVirtualDisplay causes ctor

This isn't necessarily an issue really, since its intended to be stored in the state in which it is assigned.

However, it could be resolved in the same way we store the `IVirtualKeyboard` and the `IRelativePointer`/`IAbsolutePointer` on Linux where recreating the pointers creates desktop environment issues. Doing it this way will construct it on the first request to the `IVirtualScreen` but will always return that instance from that point forward until application exit.

https://github.com/OpenTabletDriver/OpenTabletDriver/blob/7953a99582ec9882fa7ea7e2bb9fdc682f74e7d0/OpenTabletDriver.Desktop/Interop/DesktopInterop.cs#L88

2021-04-01 05:41 UTC, X9VoiD commented
Yeah, my bad, forgot to update the check boxes. I used almost the same method. But since we'll always need the virtual display I used a switch statement on it and just returned it from the getter.

The IVirtualDisplay re-ctor was a problem due to Windows timer that we have to detect resolution change (somehow we already have it even tho the change only propagates to the pointer). Without the fix, there are two instances of the timer running, and spamming "DPI Awareness enabled" twice every second.

2021-04-06 02:29 UTC, InfinityGhost requested changes

2021-04-06 02:29 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Platform/Pointer/IMouseButtonHandler.cs
> +    public interface IMouseButtonHandler
Revert this name change, it is out of scope for this PR.

2021-04-06 02:29 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Platform/Pointer/IPressureHandler.cs
> +    public interface IPressureHandler
Revert this name change as well, out of scope for this PR.

2021-04-06 02:29 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Output/OutputMode.cs
> +        }
Make this a property, sort of like so. Probably more needed to be changed here however.
```cs
        private bool passthrough;
        protected bool Passthrough
        {
            private set
            {
                if (value && !passthrough)
                {
                    this.entryElement = this;
                    this.Emit += this.OnOutput;
                    this.passthrough = true;
                }
                else if (!value && passthrough)
                {
                    this.entryElement = null;
                    this.Emit -= this.OnOutput;
                    this.passthrough = false;
                }
            }
            get => this.passthrough;
        }
```

2021-04-06 02:29 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Interop/DesktopInterop.cs
> +        };
Implement this the same way we do for the other interfaces within this class for cleanliness (such as the pointers and `IVirtualKeyboard`) and so that the behavior is the same throughout. This will initialize at the same time as the static constructor, whereas the others will be initialized when requested.

2021-04-06 02:29 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Output/LinuxArtistMode.cs
> +        public override IAbsolutePointer Pointer { set; get; } = pointer;
This will initialize the pointer even when not ever used since the static constructor will be invoked initializing this field, resulting in wasted memory. This also will be constructed on non-linux platforms because of this.

2021-04-06 02:29 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Output/AsyncPositionedPipelineElement.cs
> +        protected abstract void ConsumeState();
Whats the purpose in this function? The documentation needs to be improved here.

2021-04-06 02:29 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Output/AsyncPositionedPipelineElement.cs
> +        protected bool PenIsInRange()
Could benefit from adding a remark explaining how this is determined.

2021-04-06 09:45 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Output/AsyncPositionedPipelineElement.cs
> +        protected abstract void ConsumeState();
Notifies the asynchronous element when a state is consumed,
> Lets the element to update its internal state, not to be confused with `State`)

And does so within a lock to avoid race conditions against `UpdateState`. Overriding `Consume` is not viable as that means the override will happen outside of the lock.

2021-04-06 10:01 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Output/AsyncPositionedPipelineElement.cs
> +        protected bool PenIsInRange()
We determine that a pen is out of range when `PenIsInRange` is called within `UpdateState` after a time equivalent to a report and a half has already passed.

If however, the report interval is faster than 3ms, we instead check if 3ms has already passed before declaring that the pen is out of range.

2021-04-06 16:41 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Output/LinuxArtistMode.cs
> +        public override IAbsolutePointer Pointer { set; get; } = new EvdevVirtualTablet();
We still need to store the virtual tablet statically, otherwise it will re-initialize the pointer on every settings change. Many applications require restart when the virtual tablet is re-initialized so this becomes an unnecessary inconvenience.

2021-04-06 16:43 UTC, InfinityGhost reviewed
Almost ready, just need the linux artist mode fixed.

2021-04-06 17:00 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Output/LinuxArtistMode.cs
> +        public override IAbsolutePointer Pointer { set; get; } = new EvdevVirtualTablet();
Fixed

2021-04-06 17:15 UTC, InfinityGhost approved these changes

2021-04-06 22:11 UTC, merged