Add Wacom touch support
OpenTabletDriver/OpenTabletDriver pull request #962
Opened 2021-04-06 10:44 UTC by AbstractQbit

I have only tested this with cth-470, pth-850 and pth-860; 
8th and 9th gen consumer tablets need testing before merging this.

Also fixes #935.

2021-04-06 15:05 UTC, X9VoiD requested changes

2021-04-06 15:05 UTC, X9VoiD commented on OpenTabletDriver/Vendors/Wacom/WacomTouchReport.cs
> +                var touchID = Raw[2 + offset];
Should probably clean up to
```suggestion
            for (var i = 0; i < Raw[1]; i++)
            {
                var offset = (i * 8) + 2;
                var touchID = Raw[offset];
```
So it'll be easier to see that the chunks start on third byte, and has a length of 8 bytes.

2021-04-06 15:05 UTC, X9VoiD commented on OpenTabletDriver/Vendors/Wacom/WacomTouchReport.cs
> +                        (report[3 + offset] & (1 << 3)) != 0
If the suggestions above are applied, this should also change to:
```suggestion
                        (report[1 + offset] & (1 << 0)) != 0,
                        (report[1 + offset] & (1 << 1)) != 0,
                        (report[1 + offset] & (1 << 2)) != 0,
                        (report[1 + offset] & (1 << 3)) != 0
```

2021-04-06 15:05 UTC, X9VoiD commented on OpenTabletDriver/Vendors/Wacom/WacomTouchReport.cs
> +                var touchState = Raw[3 + offset];
```suggestion
                var touchState = Raw[1 + offset];
```

2021-04-06 15:05 UTC, X9VoiD commented on OpenTabletDriver/Vendors/Wacom/WacomTouchReport.cs
> +                            Y = (Raw[5 + offset] << 4) | (Raw[6 + offset] & 0xF)
```suggestion
                            X = (Raw[2 + offset] << 4) | (Raw[4 + offset] >> 4),
                            Y = (Raw[3 + offset] << 4) | (Raw[4 + offset] & 0xF)
```

2021-04-06 15:16 UTC, InfinityGhost requested changes

2021-04-06 15:16 UTC, InfinityGhost commented on OpenTabletDriver/Vendors/Wacom/IntuosV3TouchReport.cs
> +        public bool ShouldSerializeTouches() => true;
What is this function for?

2021-04-06 15:16 UTC, InfinityGhost commented on OpenTabletDriver/Vendors/Wacom/IntuosV3TouchReport.cs
> +        private static TouchPoint[] PrevTouches;
Use camelCase for fields.

2021-04-06 15:16 UTC, InfinityGhost commented on OpenTabletDriver/Vendors/Wacom/IntuosV3TouchReport.cs
> +        public const int maxPoints = 16;
Use UPPER_CASE_SNAKE_CASE for constants. This may also be able to be moved up into the interface, since all implementations of it appear to have the same value.

2021-04-06 15:19 UTC, AbstractQbit commented on OpenTabletDriver/Vendors/Wacom/IntuosV3TouchReport.cs
> +        public bool ShouldSerializeTouches() => true;
Newtonsoft refused to serialize that property without this

2021-04-06 15:21 UTC, InfinityGhost commented on OpenTabletDriver/Vendors/Wacom/IntuosV3TouchReport.cs
> +        public bool ShouldSerializeTouches() => true;
Wouldn't `JsonPropertyAttribute` suffice for this? I've never seen this needed before.

2021-04-06 16:20 UTC, X9VoiD commented
WacomTouchReport and IntuosV3Report is [wacom_bpt3_touch()](https://github.com/linuxwacom/input-wacom/blob/master/4.5/wacom_wac.c#L2952)

This parser is used for devices of these type
| Intuos 5 Lineup | Intuos P Lineup | Intuos HT Lineup | Bamboo Lineup |
| :---: | :---: | :---: | :---: |
| Intuos5 | IntuosPS | IntuosHT | Bamboo Pen |
| Intuos5S | IntuosPM | IntuosHT2 | Bamboo Touch |
| Intuos5L | IntuosPL | | BambooPT |

So with that said, we can determine that these devices that the PR modified are to be verified working:

| BambooPT | IntuosHT | IntuosHT2 | Intuos5 | Intuos5L | IntuosPS | IntuosPM |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| CTH-470 | CTH-480 | CTH-490 | PTH-650 | PTH-850 | PTH-451 | PTH-651 |
| CTH-670 | CTH-680 | CTH-690 |
| | CTL-480 | CTL-490 |
| | CTL-680 | CTL-690 |

PTH-660 however is a device that cannot be verified, there are references to it in input-wacom, but no full configuration for it. (doesn't specify parser, size, max touch points, etc, as if it's unsupported)

2021-04-06 16:32 UTC, InfinityGhost commented on OpenTabletDriver/Vendors/Wacom/IntuosV3TouchReport.cs
> +        public bool ShouldSerializeTouches() => true;
After discussion, we should at least add xmldocs explaining what this is used for.

2021-04-06 16:33 UTC, AbstractQbit commented
Here are the touch dimensions for PTH-460/660/860: 
https://github.com/linuxwacom/input-wacom/blob/74f6fd70f2584f0548303583ef8713e53d3314a5/4.5/wacom_wac.c#L3793-L3816

2021-04-06 16:41 UTC, X9VoiD commented
The thing is that the kernel module did not declare PTH-660 (PID: 855 or 0x357) as a supported device so I can't verify that one.

2021-04-08 03:46 UTC, InfinityGhost commented
Man I sure do love CI

2021-04-08 03:47 UTC, InfinityGhost commented
Is this ready for merge?

2021-04-08 06:14 UTC, merged

2023-09-25 17:11 UTC, ocumo commented
Sorry for posting in this old thread, but something is not clear, and before I create or pollute other threads, just a question:
Does this includes Wacom PTH-851?
With PTH-851, touch is detected in the tablet debugger, but not by any other program or desktop.
Should I make a separate request to add touch support for PTH-851?
Thanks!
(Linux, Xubuntu 22.04 LTS)

2023-09-25 17:19 UTC, jamesbt365 commented
This pull request parses touch. OTD does not support any touch output at this time.

2023-09-27 15:57 UTC, ocumo commented
Thanks.
So, that means, that for now OTD reads the input --correctly, as far as I can see-- but it won't output it to any program, right?
Is touch output a thing that might ever be supported in the future, even for a limited number of tablets, or is it completely out of the scope of the project?  I can only guess than getting to parse the touch is a good clue that touch is planned or at least desired.
Thanks again

2023-09-27 15:59 UTC, jamesbt365 commented
See #1664.

2023-09-27 16:39 UTC, jamesbt365 commented
#1664 is the issue tracking touch support. Touch is parsed on most tablets that support, meaning that OTD understands what touch is, but currently has no support for actually outputting this to the display. The issue that I linked is the issue tracking this.

We are a small team, we are not paid to develop this project and therefore we do not have all the time in the world to work on specific features so unless anybody steps up outside of our team to supply any touch support before we do this is not in scope for 0.7 or potentially even 0.7.1 depending on what time we have available, hence why it is in the backlog milestone. For an overview on all the milestones see [this](https://github.com/OpenTabletDriver/OpenTabletDriver/milestones).

We have no plans on implementing this *right now* as we have more important things to do like getting a stable codebase for 0.7 to release on. There is lots to do in that milestone so do you not expect this any time soon, we have limited resources here.

2023-09-27 17:00 UTC, ocumo commented
Ok, thank you so very much!

I totally understand. I am by no means criticizing lack of support of any feature.  Quite the contrary: I am glad that there is this project.  The reason for my curiosity (not a request) is that I have only recently discovered OTD and dumped Wacom drivers to give it a chance, since there is no good GUI solution for tablets in Linux.  I just need to understand the limitations to adapt and try to live with it.   Touch would be nice, but I am with you, it's not top priority.

I will keep using OTD, and I have already have my quote of troubleshooting and issues, and learned a few things about it in the meantime.  I have noticed the lack of resources to put in place an extensive documentation, and I sympathize.  I have been writing a few procedures for me, to help me avoid troubles with the installation procedure on my various systems, which I have to say could be improved in your wiki, nothing fancy, just a couple of notes or steps would avoid so much pain for many people, as many others had the same troubles as I did.

Thanks again