Fix bogus HID reports breaking tablet detection
OpenTabletDriver/OpenTabletDriver pull request #965
Opened 2021-04-06 19:07 UTC by BigBrainAFK

This fix prevents devices from aborting the tablet detection prematurely.

The fix mainly applies to cases like #960 where another USB device hands out bogus HID reports with `CanOpen` set to `true`.
So we filter the `IEnumerable<HidDevice>` in `OpenTabletDrivers.Drivers.FindMatches` before we even check for a `CanOpen`.
This way we rule out broken third party devices that are not the tablets we are interested in.

2021-04-06 19:20 UTC, X9VoiD approved these changes
This fixes the issue for most cases, however we'll have to keep in mind that the actual problem is in HidSharpCore. If in the future we encounter a tablet that HidSharpCore can't perform report reconstruction on then it'll crash on those cases.

2021-04-08 03:52 UTC, InfinityGhost commented
> This fixes the issue for most cases, however we'll have to keep in mind that the actual problem is in HidSharpCore. If in the future we encounter a tablet that HidSharpCore can't perform report reconstruction on then it'll crash on those cases.

Should add a try/catch block to handle that situation and report it explicitly into the log for that situation. Hard crashes are always  more difficult to diagnose.

2021-04-08 13:23 UTC, X9VoiD requested changes
As per Infinity's suggestion, probably change the function to this or something similar
```cs
        private IEnumerable<HidDevice> FindMatches(DeviceIdentifier identifier)
        {
            foreach (var device in DeviceList.Local.GetHidDevices())
            {
                try
                {
                    if (identifier.VendorID != device.VendorID
                        || identifier.ProductID != device.ProductID
                        || !device.CanOpen
                        || identifier.InputReportLength != null && identifier.InputReportLength != device.GetMaxInputReportLength()
                        || identifier.OutputReportLength != null && identifier.OutputReportLength != device.GetMaxOutputReportLength()
                        || !DeviceMatchesAllStrings(device, identifier))
                    {
                        continue;
                    }
                }
                catch (Exception e)
                {
                    Log.Exception(e);
                    continue;
                }

                yield return device;
            }
        }
```

2021-04-08 18:30 UTC, X9VoiD approved these changes

2021-04-12 17:39 UTC, InfinityGhost requested changes
I mean, yeah this works but it looks horrible compared to the previous LINQ method. Since the issue is specifically the `HidDevice.CanOpen` property, we should just check that in a separate try/catch block in a private function in the meantime.

2021-04-12 18:53 UTC, BigBrainAFK commented
> 
> 
> I mean, yeah this works but it looks horrible compared to the previous LINQ method. Since the issue is specifically the `HidDevice.CanOpen` property, we should just check that in a separate try/catch block in a private function in the meantime.

I seperated out the `device.CanOpen` and reverted back to the first commit style of LINQ so that the console doesnt get spammed with all the exceptions but will still log errors if needed.

2021-04-12 21:13 UTC, InfinityGhost approved these changes

2021-04-12 21:14 UTC, merged